{{- if and .Values.api.enabled .Values.networkPolicies.api.enabled }}
{{- $api := .Values.networkPolicies.api -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ printf "%s-api-ingress" (include "nemo-platform.fullname" .) | trunc 63 | trimSuffix "-" }}
  labels:
    app.kubernetes.io/component: nmp-api
    {{- include "nemo-platform.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: nmp-api
      {{- include "nemo-platform.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  {{- if or $api.sameReleasePods.enabled $api.managedJobs.enabled $api.extraIngress }}
  ingress:
    {{- if $api.sameReleasePods.enabled }}
    - from:
        - podSelector:
            matchLabels:
              {{- include "nemo-platform.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ default .Values.api.service.port $api.port }}
    {{- end }}
    {{- if $api.managedJobs.enabled }}
    - from:
        - podSelector:
            {{- toYaml $api.managedJobs.podSelector | nindent 12 }}
      ports:
        - protocol: TCP
          port: {{ default .Values.api.service.port $api.port }}
    {{- end }}
    {{- with $api.extraIngress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
