# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

schema-version = "1.14.0"

[install]
open-policy-agent = { pkg-path = "open-policy-agent", version = "1.8.0", pkg-group = "open-policy-agent" }
