# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.platform_secret_admin_rotation_response import PlatformSecretAdminRotationResponse
from .raw_client import AsyncRawSecretsAdminClient, RawSecretsAdminClient


class SecretsAdminClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSecretsAdminClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSecretsAdminClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSecretsAdminClient
        """
        return self._raw_client

    def admin_rotate_encryption_keys(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PlatformSecretAdminRotationResponse:
        """
        Rotate encryption keys for all platform secrets.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PlatformSecretAdminRotationResponse
            Successful Response

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.secrets_admin.admin_rotate_encryption_keys()
        """
        _response = self._raw_client.admin_rotate_encryption_keys(request_options=request_options)
        return _response.data


class AsyncSecretsAdminClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSecretsAdminClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSecretsAdminClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSecretsAdminClient
        """
        return self._raw_client

    async def admin_rotate_encryption_keys(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PlatformSecretAdminRotationResponse:
        """
        Rotate encryption keys for all platform secrets.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PlatformSecretAdminRotationResponse
            Successful Response

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.secrets_admin.admin_rotate_encryption_keys()


        asyncio.run(main())
        """
        _response = await self._raw_client.admin_rotate_encryption_keys(request_options=request_options)
        return _response.data
