# This file was auto-generated by Fern from our API Definition.

import typing

GetTraceApisIntakeV2WorkspacesWorkspaceTracesIdGetRequestMode = typing.Union[
    typing.Literal["summary", "detailed"], typing.Any
]
