# This file was auto-generated by Fern from our API Definition.

import typing

ListTracesApisIntakeV2WorkspacesWorkspaceTracesGetRequestMode = typing.Union[
    typing.Literal["summary", "detailed"], typing.Any
]
