# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

schema-version = "1.14.0"

[install]
osv-scanner = { pkg-path = "osv-scanner", version = "2.3.3", pkg-group = "osv-scanner" }
