# syntax=docker/dockerfile:1
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0


# require >= 1.26.7 for current Go stdlib security fixes
FROM golang:1.26.7 AS build
COPY ./services/core/jobs/jobs-launcher /app/services/jobs-launcher
WORKDIR /app/services/jobs-launcher
RUN go mod download
RUN CGO_ENABLED=0 go build -a -installsuffix cgo -ldflags="-s -w -extldflags '-static'" -trimpath -o jobs-launcher ./main.go
# Verify the binary works
RUN ./jobs-launcher help

FROM scratch AS artifacts
WORKDIR /artifacts
COPY --from=build /app/services/jobs-launcher/jobs-launcher .
# Outputs the static binary to /artifacts/jobs-launcher
