# Default E2E values for running tests in a Kubernetes cluster, for ephemeral testing

postgresql:
  image:
    repository: docker.io/library/postgres
  persistence:
    storageClass: local-path

ingress:
  enabled: false

platformConfig:
  # This is used to enable mock provider mode for E2E tests.
  inference_gateway:
    mock_provider_prefix: igw-mock-
  jobs:
    executors:
      - provider: cpu
        profile: additional-volume
        backend: kubernetes_job
        config:
          service_account_name: '{{ include "nmp-core.jobsServiceAccountName" . }}'
          launcher_image: '{{ include "nmp-core.image" . }}'
          storage:
            pvc_name: '{{ include "nmp-core.persistentVolumeClaim" . }}'
            volume_permissions_image: '{{ .Values.core.storage.volumePermissionsImage }}'
            additional_volumes:
              - name: nmp-additional-volume
                persistent_volume_claim:
                  claim_name: '{{ include "nmp-core.persistentVolumeClaim" . }}'
            additional_volume_mounts:
              - name: nmp-additional-volume
                mount_path: /mnt/additional_storage

core:
  storage:
    storageClass: oci-nfs
    volumePermissionsImage: docker.io/library/busybox
