{{/* SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved. */}}
{{/* SPDX-License-Identifier: Apache-2.0 */}}

{{- if and .Values.clickhouse.enabled (not .Values.clickhouse.auth.existingSecret) }}
{{- $secretName := include "nemo-common.clickhouse.fullname" . }}
{{- $passwordData := randAlphaNum 32 | b64enc }}
{{- with (lookup "v1" "Secret" .Release.Namespace $secretName) }}
{{- $passwordData = index .data "password" | default $passwordData }}
{{- end }}
{{- with .Values.clickhouse.auth.password }}
{{- $passwordData = . | b64enc }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app.kubernetes.io/component: clickhouse
    {{- include "nemo-platform.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ $passwordData | quote }}
{{- end }}
