# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if and (include "nemo-common.clickhouse.enabled" .) .Values.clickhouse.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nemo-common.clickhouse.serviceAccountName" . }}
  labels:
    app.kubernetes.io/component: clickhouse
    {{- include "nemo-platform.labels" . | nindent 4 }}
  {{- with .Values.clickhouse.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.clickhouse.serviceAccount.automount }}
{{- end }}
