{{- if and .Values.clickhouse.enabled (not .Values.clickhouse.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nemo-common.clickhouse.fullname" . }}
  labels:
    app.kubernetes.io/component: clickhouse
    {{- include "nemo-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.clickhouse.auth.password | quote }}
{{- end }}
