# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.open_ai_list_models_resp import OpenAiListModelsResp
from ..types.open_ai_model_resp import OpenAiModelResp
from .raw_client import AsyncRawInferenceGatewayClient, RawInferenceGatewayClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class InferenceGatewayClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawInferenceGatewayClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawInferenceGatewayClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawInferenceGatewayClient
        """
        return self._raw_client

    def gateway_proxy_get(
        self, workspace: str, name: str, trailing_uri: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Proxy requests to model entity inference endpoints.

        All inference requests must resolve to a `VirtualModel`. The platform's
        provider reconciler auto-creates an implicit `autoprovisioned` VirtualModel
        for every served model entity (named after the entity, with
        `default_model_entity` set to the entity ref) so this is the typical case;
        operators can also create custom VirtualModels for routing, plugin chains,
        LoRA escape-hatches, etc. Requests for which no VirtualModel can be found
        return `404`.

        Parameters
        ----------
        workspace : str

        name : str

        trailing_uri : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Proxy GET request to model entity inference endpoint

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.inference_gateway.gateway_proxy_get(
            workspace="workspace",
            name="name",
            trailing_uri="trailing_uri",
        )
        """
        _response = self._raw_client.gateway_proxy_get(workspace, name, trailing_uri, request_options=request_options)
        return _response.data

    def gateway_proxy_post(
        self,
        workspace: str,
        name: str,
        trailing_uri: str,
        *,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Proxy requests to model entity inference endpoints.

        All inference requests must resolve to a `VirtualModel`. The platform's
        provider reconciler auto-creates an implicit `autoprovisioned` VirtualModel
        for every served model entity (named after the entity, with
        `default_model_entity` set to the entity ref) so this is the typical case;
        operators can also create custom VirtualModels for routing, plugin chains,
        LoRA escape-hatches, etc. Requests for which no VirtualModel can be found
        return `404`.

        Parameters
        ----------
        workspace : str

        name : str

        trailing_uri : str

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Proxy POST request to model entity inference endpoint

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.inference_gateway.gateway_proxy_post(
            workspace="workspace",
            name="name",
            trailing_uri="trailing_uri",
            request={"key": "value"},
        )
        """
        _response = self._raw_client.gateway_proxy_post(
            workspace, name, trailing_uri, request=request, request_options=request_options
        )
        return _response.data

    def gateway_proxy_put(
        self,
        workspace: str,
        name: str,
        trailing_uri: str,
        *,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Proxy requests to model entity inference endpoints.

        All inference requests must resolve to a `VirtualModel`. The platform's
        provider reconciler auto-creates an implicit `autoprovisioned` VirtualModel
        for every served model entity (named after the entity, with
        `default_model_entity` set to the entity ref) so this is the typical case;
        operators can also create custom VirtualModels for routing, plugin chains,
        LoRA escape-hatches, etc. Requests for which no VirtualModel can be found
        return `404`.

        Parameters
        ----------
        workspace : str

        name : str

        trailing_uri : str

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Proxy PUT request to model entity inference endpoint

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.inference_gateway.gateway_proxy_put(
            workspace="workspace",
            name="name",
            trailing_uri="trailing_uri",
            request={"key": "value"},
        )
        """
        _response = self._raw_client.gateway_proxy_put(
            workspace, name, trailing_uri, request=request, request_options=request_options
        )
        return _response.data

    def gateway_proxy_delete(
        self, workspace: str, name: str, trailing_uri: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Proxy requests to model entity inference endpoints.

        All inference requests must resolve to a `VirtualModel`. The platform's
        provider reconciler auto-creates an implicit `autoprovisioned` VirtualModel
        for every served model entity (named after the entity, with
        `default_model_entity` set to the entity ref) so this is the typical case;
        operators can also create custom VirtualModels for routing, plugin chains,
        LoRA escape-hatches, etc. Requests for which no VirtualModel can be found
        return `404`.

        Parameters
        ----------
        workspace : str

        name : str

        trailing_uri : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Proxy DELETE request to model entity inference endpoint

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.inference_gateway.gateway_proxy_delete(
            workspace="workspace",
            name="name",
            trailing_uri="trailing_uri",
        )
        """
        _response = self._raw_client.gateway_proxy_delete(
            workspace, name, trailing_uri, request_options=request_options
        )
        return _response.data

    def gateway_proxy_patch(
        self,
        workspace: str,
        name: str,
        trailing_uri: str,
        *,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Proxy requests to model entity inference endpoints.

        All inference requests must resolve to a `VirtualModel`. The platform's
        provider reconciler auto-creates an implicit `autoprovisioned` VirtualModel
        for every served model entity (named after the entity, with
        `default_model_entity` set to the entity ref) so this is the typical case;
        operators can also create custom VirtualModels for routing, plugin chains,
        LoRA escape-hatches, etc. Requests for which no VirtualModel can be found
        return `404`.

        Parameters
        ----------
        workspace : str

        name : str

        trailing_uri : str

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Proxy PATCH request to model entity inference endpoint

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.inference_gateway.gateway_proxy_patch(
            workspace="workspace",
            name="name",
            trailing_uri="trailing_uri",
            request={"key": "value"},
        )
        """
        _response = self._raw_client.gateway_proxy_patch(
            workspace, name, trailing_uri, request=request, request_options=request_options
        )
        return _response.data

    def openai_proxy_list_models(
        self, workspace: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OpenAiListModelsResp:
        """
        This endpoint aggregates models from all model entities and returns them
        in OpenAI's list models format. Each model ID is the model entity identifier
        in format workspace/model_entity_name.

        Parameters
        ----------
        workspace : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OpenAiListModelsResp
            List models request to OpenAI-compatible endpoint

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.inference_gateway.openai_proxy_list_models(
            workspace="workspace",
        )
        """
        _response = self._raw_client.openai_proxy_list_models(workspace, request_options=request_options)
        return _response.data

    def openai_proxy_get_model(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OpenAiModelResp:
        """
        Retrieve information about a specific OpenAI-compatible model.
        Workspace is always taken from the URL path; name may be model_entity_name
        or workspace/model_entity_name (workspace prefix is ignored).

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OpenAiModelResp
            Get model request to OpenAI-compatible endpoint

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.inference_gateway.openai_proxy_get_model(
            workspace="workspace",
            name="name",
        )
        """
        _response = self._raw_client.openai_proxy_get_model(workspace, name, request_options=request_options)
        return _response.data

    def openai_proxy_get(
        self, workspace: str, trailing_uri: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Proxy requests to OpenAI-compatible inference endpoints.

        All inference requests must resolve to a `VirtualModel`. The platform's
        provider reconciler auto-creates an implicit `autoprovisioned` VirtualModel
        for every served model entity (named after the entity, with
        `default_model_entity` set to the entity ref) so this is the typical case;
        operators can also create custom VirtualModels for routing, plugin chains,
        LoRA escape-hatches, etc. Requests for which no VirtualModel can be found
        return `404`.

        Parameters
        ----------
        workspace : str

        trailing_uri : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Proxy GET request to OpenAI-compatible endpoint

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.inference_gateway.openai_proxy_get(
            workspace="workspace",
            trailing_uri="trailing_uri",
        )
        """
        _response = self._raw_client.openai_proxy_get(workspace, trailing_uri, request_options=request_options)
        return _response.data

    def openai_proxy_post(
        self,
        workspace: str,
        trailing_uri: str,
        *,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Proxy requests to OpenAI-compatible inference endpoints.

        All inference requests must resolve to a `VirtualModel`. The platform's
        provider reconciler auto-creates an implicit `autoprovisioned` VirtualModel
        for every served model entity (named after the entity, with
        `default_model_entity` set to the entity ref) so this is the typical case;
        operators can also create custom VirtualModels for routing, plugin chains,
        LoRA escape-hatches, etc. Requests for which no VirtualModel can be found
        return `404`.

        Parameters
        ----------
        workspace : str

        trailing_uri : str

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Proxy POST request to OpenAI-compatible endpoint

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.inference_gateway.openai_proxy_post(
            workspace="workspace",
            trailing_uri="trailing_uri",
            request={"key": "value"},
        )
        """
        _response = self._raw_client.openai_proxy_post(
            workspace, trailing_uri, request=request, request_options=request_options
        )
        return _response.data

    def openai_proxy_put(
        self,
        workspace: str,
        trailing_uri: str,
        *,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Proxy requests to OpenAI-compatible inference endpoints.

        All inference requests must resolve to a `VirtualModel`. The platform's
        provider reconciler auto-creates an implicit `autoprovisioned` VirtualModel
        for every served model entity (named after the entity, with
        `default_model_entity` set to the entity ref) so this is the typical case;
        operators can also create custom VirtualModels for routing, plugin chains,
        LoRA escape-hatches, etc. Requests for which no VirtualModel can be found
        return `404`.

        Parameters
        ----------
        workspace : str

        trailing_uri : str

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Proxy PUT request to OpenAI-compatible endpoint

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.inference_gateway.openai_proxy_put(
            workspace="workspace",
            trailing_uri="trailing_uri",
            request={"key": "value"},
        )
        """
        _response = self._raw_client.openai_proxy_put(
            workspace, trailing_uri, request=request, request_options=request_options
        )
        return _response.data

    def openai_proxy_delete(
        self, workspace: str, trailing_uri: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Proxy requests to OpenAI-compatible inference endpoints.

        All inference requests must resolve to a `VirtualModel`. The platform's
        provider reconciler auto-creates an implicit `autoprovisioned` VirtualModel
        for every served model entity (named after the entity, with
        `default_model_entity` set to the entity ref) so this is the typical case;
        operators can also create custom VirtualModels for routing, plugin chains,
        LoRA escape-hatches, etc. Requests for which no VirtualModel can be found
        return `404`.

        Parameters
        ----------
        workspace : str

        trailing_uri : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Proxy DELETE request to OpenAI-compatible endpoint

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.inference_gateway.openai_proxy_delete(
            workspace="workspace",
            trailing_uri="trailing_uri",
        )
        """
        _response = self._raw_client.openai_proxy_delete(workspace, trailing_uri, request_options=request_options)
        return _response.data

    def openai_proxy_patch(
        self,
        workspace: str,
        trailing_uri: str,
        *,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Proxy requests to OpenAI-compatible inference endpoints.

        All inference requests must resolve to a `VirtualModel`. The platform's
        provider reconciler auto-creates an implicit `autoprovisioned` VirtualModel
        for every served model entity (named after the entity, with
        `default_model_entity` set to the entity ref) so this is the typical case;
        operators can also create custom VirtualModels for routing, plugin chains,
        LoRA escape-hatches, etc. Requests for which no VirtualModel can be found
        return `404`.

        Parameters
        ----------
        workspace : str

        trailing_uri : str

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Proxy PATCH request to OpenAI-compatible endpoint

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.inference_gateway.openai_proxy_patch(
            workspace="workspace",
            trailing_uri="trailing_uri",
            request={"key": "value"},
        )
        """
        _response = self._raw_client.openai_proxy_patch(
            workspace, trailing_uri, request=request, request_options=request_options
        )
        return _response.data

    def provider_proxy_get(
        self, workspace: str, name: str, trailing_uri: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Proxy requests to provider inference endpoints.

        Parameters
        ----------
        workspace : str

        name : str

        trailing_uri : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Proxy GET request to provider inference endpoint

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.inference_gateway.provider_proxy_get(
            workspace="workspace",
            name="name",
            trailing_uri="trailing_uri",
        )
        """
        _response = self._raw_client.provider_proxy_get(workspace, name, trailing_uri, request_options=request_options)
        return _response.data

    def provider_proxy_post(
        self,
        workspace: str,
        name: str,
        trailing_uri: str,
        *,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Proxy requests to provider inference endpoints.

        Parameters
        ----------
        workspace : str

        name : str

        trailing_uri : str

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Proxy POST request to provider inference endpoint

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.inference_gateway.provider_proxy_post(
            workspace="workspace",
            name="name",
            trailing_uri="trailing_uri",
            request={"key": "value"},
        )
        """
        _response = self._raw_client.provider_proxy_post(
            workspace, name, trailing_uri, request=request, request_options=request_options
        )
        return _response.data

    def provider_proxy_put(
        self,
        workspace: str,
        name: str,
        trailing_uri: str,
        *,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Proxy requests to provider inference endpoints.

        Parameters
        ----------
        workspace : str

        name : str

        trailing_uri : str

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Proxy PUT request to provider inference endpoint

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.inference_gateway.provider_proxy_put(
            workspace="workspace",
            name="name",
            trailing_uri="trailing_uri",
            request={"key": "value"},
        )
        """
        _response = self._raw_client.provider_proxy_put(
            workspace, name, trailing_uri, request=request, request_options=request_options
        )
        return _response.data

    def provider_proxy_delete(
        self, workspace: str, name: str, trailing_uri: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Proxy requests to provider inference endpoints.

        Parameters
        ----------
        workspace : str

        name : str

        trailing_uri : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Proxy DELETE request to provider inference endpoint

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.inference_gateway.provider_proxy_delete(
            workspace="workspace",
            name="name",
            trailing_uri="trailing_uri",
        )
        """
        _response = self._raw_client.provider_proxy_delete(
            workspace, name, trailing_uri, request_options=request_options
        )
        return _response.data

    def provider_proxy_patch(
        self,
        workspace: str,
        name: str,
        trailing_uri: str,
        *,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Proxy requests to provider inference endpoints.

        Parameters
        ----------
        workspace : str

        name : str

        trailing_uri : str

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Proxy PATCH request to provider inference endpoint

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.inference_gateway.provider_proxy_patch(
            workspace="workspace",
            name="name",
            trailing_uri="trailing_uri",
            request={"key": "value"},
        )
        """
        _response = self._raw_client.provider_proxy_patch(
            workspace, name, trailing_uri, request=request, request_options=request_options
        )
        return _response.data

    def provider_ready(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Check if a model provider is registered in the gateway's cache.

        This is a lightweight endpoint that only checks the gateway's internal state,
        without making any requests to the actual provider backend. Use this to verify
        the gateway is ready to route requests to a provider after deployment.

        Returns:
            200 OK with provider info if the provider is registered
            404 Not Found if the provider is not yet in the gateway's cache

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Check if the gateway can route to a provider

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.inference_gateway.provider_ready(
            workspace="workspace",
            name="name",
        )
        """
        _response = self._raw_client.provider_ready(workspace, name, request_options=request_options)
        return _response.data


class AsyncInferenceGatewayClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawInferenceGatewayClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawInferenceGatewayClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawInferenceGatewayClient
        """
        return self._raw_client

    async def gateway_proxy_get(
        self, workspace: str, name: str, trailing_uri: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Proxy requests to model entity inference endpoints.

        All inference requests must resolve to a `VirtualModel`. The platform's
        provider reconciler auto-creates an implicit `autoprovisioned` VirtualModel
        for every served model entity (named after the entity, with
        `default_model_entity` set to the entity ref) so this is the typical case;
        operators can also create custom VirtualModels for routing, plugin chains,
        LoRA escape-hatches, etc. Requests for which no VirtualModel can be found
        return `404`.

        Parameters
        ----------
        workspace : str

        name : str

        trailing_uri : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Proxy GET request to model entity inference endpoint

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.inference_gateway.gateway_proxy_get(
                workspace="workspace",
                name="name",
                trailing_uri="trailing_uri",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.gateway_proxy_get(
            workspace, name, trailing_uri, request_options=request_options
        )
        return _response.data

    async def gateway_proxy_post(
        self,
        workspace: str,
        name: str,
        trailing_uri: str,
        *,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Proxy requests to model entity inference endpoints.

        All inference requests must resolve to a `VirtualModel`. The platform's
        provider reconciler auto-creates an implicit `autoprovisioned` VirtualModel
        for every served model entity (named after the entity, with
        `default_model_entity` set to the entity ref) so this is the typical case;
        operators can also create custom VirtualModels for routing, plugin chains,
        LoRA escape-hatches, etc. Requests for which no VirtualModel can be found
        return `404`.

        Parameters
        ----------
        workspace : str

        name : str

        trailing_uri : str

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Proxy POST request to model entity inference endpoint

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.inference_gateway.gateway_proxy_post(
                workspace="workspace",
                name="name",
                trailing_uri="trailing_uri",
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.gateway_proxy_post(
            workspace, name, trailing_uri, request=request, request_options=request_options
        )
        return _response.data

    async def gateway_proxy_put(
        self,
        workspace: str,
        name: str,
        trailing_uri: str,
        *,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Proxy requests to model entity inference endpoints.

        All inference requests must resolve to a `VirtualModel`. The platform's
        provider reconciler auto-creates an implicit `autoprovisioned` VirtualModel
        for every served model entity (named after the entity, with
        `default_model_entity` set to the entity ref) so this is the typical case;
        operators can also create custom VirtualModels for routing, plugin chains,
        LoRA escape-hatches, etc. Requests for which no VirtualModel can be found
        return `404`.

        Parameters
        ----------
        workspace : str

        name : str

        trailing_uri : str

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Proxy PUT request to model entity inference endpoint

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.inference_gateway.gateway_proxy_put(
                workspace="workspace",
                name="name",
                trailing_uri="trailing_uri",
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.gateway_proxy_put(
            workspace, name, trailing_uri, request=request, request_options=request_options
        )
        return _response.data

    async def gateway_proxy_delete(
        self, workspace: str, name: str, trailing_uri: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Proxy requests to model entity inference endpoints.

        All inference requests must resolve to a `VirtualModel`. The platform's
        provider reconciler auto-creates an implicit `autoprovisioned` VirtualModel
        for every served model entity (named after the entity, with
        `default_model_entity` set to the entity ref) so this is the typical case;
        operators can also create custom VirtualModels for routing, plugin chains,
        LoRA escape-hatches, etc. Requests for which no VirtualModel can be found
        return `404`.

        Parameters
        ----------
        workspace : str

        name : str

        trailing_uri : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Proxy DELETE request to model entity inference endpoint

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.inference_gateway.gateway_proxy_delete(
                workspace="workspace",
                name="name",
                trailing_uri="trailing_uri",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.gateway_proxy_delete(
            workspace, name, trailing_uri, request_options=request_options
        )
        return _response.data

    async def gateway_proxy_patch(
        self,
        workspace: str,
        name: str,
        trailing_uri: str,
        *,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Proxy requests to model entity inference endpoints.

        All inference requests must resolve to a `VirtualModel`. The platform's
        provider reconciler auto-creates an implicit `autoprovisioned` VirtualModel
        for every served model entity (named after the entity, with
        `default_model_entity` set to the entity ref) so this is the typical case;
        operators can also create custom VirtualModels for routing, plugin chains,
        LoRA escape-hatches, etc. Requests for which no VirtualModel can be found
        return `404`.

        Parameters
        ----------
        workspace : str

        name : str

        trailing_uri : str

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Proxy PATCH request to model entity inference endpoint

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.inference_gateway.gateway_proxy_patch(
                workspace="workspace",
                name="name",
                trailing_uri="trailing_uri",
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.gateway_proxy_patch(
            workspace, name, trailing_uri, request=request, request_options=request_options
        )
        return _response.data

    async def openai_proxy_list_models(
        self, workspace: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OpenAiListModelsResp:
        """
        This endpoint aggregates models from all model entities and returns them
        in OpenAI's list models format. Each model ID is the model entity identifier
        in format workspace/model_entity_name.

        Parameters
        ----------
        workspace : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OpenAiListModelsResp
            List models request to OpenAI-compatible endpoint

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.inference_gateway.openai_proxy_list_models(
                workspace="workspace",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.openai_proxy_list_models(workspace, request_options=request_options)
        return _response.data

    async def openai_proxy_get_model(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OpenAiModelResp:
        """
        Retrieve information about a specific OpenAI-compatible model.
        Workspace is always taken from the URL path; name may be model_entity_name
        or workspace/model_entity_name (workspace prefix is ignored).

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OpenAiModelResp
            Get model request to OpenAI-compatible endpoint

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.inference_gateway.openai_proxy_get_model(
                workspace="workspace",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.openai_proxy_get_model(workspace, name, request_options=request_options)
        return _response.data

    async def openai_proxy_get(
        self, workspace: str, trailing_uri: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Proxy requests to OpenAI-compatible inference endpoints.

        All inference requests must resolve to a `VirtualModel`. The platform's
        provider reconciler auto-creates an implicit `autoprovisioned` VirtualModel
        for every served model entity (named after the entity, with
        `default_model_entity` set to the entity ref) so this is the typical case;
        operators can also create custom VirtualModels for routing, plugin chains,
        LoRA escape-hatches, etc. Requests for which no VirtualModel can be found
        return `404`.

        Parameters
        ----------
        workspace : str

        trailing_uri : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Proxy GET request to OpenAI-compatible endpoint

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.inference_gateway.openai_proxy_get(
                workspace="workspace",
                trailing_uri="trailing_uri",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.openai_proxy_get(workspace, trailing_uri, request_options=request_options)
        return _response.data

    async def openai_proxy_post(
        self,
        workspace: str,
        trailing_uri: str,
        *,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Proxy requests to OpenAI-compatible inference endpoints.

        All inference requests must resolve to a `VirtualModel`. The platform's
        provider reconciler auto-creates an implicit `autoprovisioned` VirtualModel
        for every served model entity (named after the entity, with
        `default_model_entity` set to the entity ref) so this is the typical case;
        operators can also create custom VirtualModels for routing, plugin chains,
        LoRA escape-hatches, etc. Requests for which no VirtualModel can be found
        return `404`.

        Parameters
        ----------
        workspace : str

        trailing_uri : str

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Proxy POST request to OpenAI-compatible endpoint

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.inference_gateway.openai_proxy_post(
                workspace="workspace",
                trailing_uri="trailing_uri",
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.openai_proxy_post(
            workspace, trailing_uri, request=request, request_options=request_options
        )
        return _response.data

    async def openai_proxy_put(
        self,
        workspace: str,
        trailing_uri: str,
        *,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Proxy requests to OpenAI-compatible inference endpoints.

        All inference requests must resolve to a `VirtualModel`. The platform's
        provider reconciler auto-creates an implicit `autoprovisioned` VirtualModel
        for every served model entity (named after the entity, with
        `default_model_entity` set to the entity ref) so this is the typical case;
        operators can also create custom VirtualModels for routing, plugin chains,
        LoRA escape-hatches, etc. Requests for which no VirtualModel can be found
        return `404`.

        Parameters
        ----------
        workspace : str

        trailing_uri : str

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Proxy PUT request to OpenAI-compatible endpoint

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.inference_gateway.openai_proxy_put(
                workspace="workspace",
                trailing_uri="trailing_uri",
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.openai_proxy_put(
            workspace, trailing_uri, request=request, request_options=request_options
        )
        return _response.data

    async def openai_proxy_delete(
        self, workspace: str, trailing_uri: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Proxy requests to OpenAI-compatible inference endpoints.

        All inference requests must resolve to a `VirtualModel`. The platform's
        provider reconciler auto-creates an implicit `autoprovisioned` VirtualModel
        for every served model entity (named after the entity, with
        `default_model_entity` set to the entity ref) so this is the typical case;
        operators can also create custom VirtualModels for routing, plugin chains,
        LoRA escape-hatches, etc. Requests for which no VirtualModel can be found
        return `404`.

        Parameters
        ----------
        workspace : str

        trailing_uri : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Proxy DELETE request to OpenAI-compatible endpoint

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.inference_gateway.openai_proxy_delete(
                workspace="workspace",
                trailing_uri="trailing_uri",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.openai_proxy_delete(workspace, trailing_uri, request_options=request_options)
        return _response.data

    async def openai_proxy_patch(
        self,
        workspace: str,
        trailing_uri: str,
        *,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Proxy requests to OpenAI-compatible inference endpoints.

        All inference requests must resolve to a `VirtualModel`. The platform's
        provider reconciler auto-creates an implicit `autoprovisioned` VirtualModel
        for every served model entity (named after the entity, with
        `default_model_entity` set to the entity ref) so this is the typical case;
        operators can also create custom VirtualModels for routing, plugin chains,
        LoRA escape-hatches, etc. Requests for which no VirtualModel can be found
        return `404`.

        Parameters
        ----------
        workspace : str

        trailing_uri : str

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Proxy PATCH request to OpenAI-compatible endpoint

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.inference_gateway.openai_proxy_patch(
                workspace="workspace",
                trailing_uri="trailing_uri",
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.openai_proxy_patch(
            workspace, trailing_uri, request=request, request_options=request_options
        )
        return _response.data

    async def provider_proxy_get(
        self, workspace: str, name: str, trailing_uri: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Proxy requests to provider inference endpoints.

        Parameters
        ----------
        workspace : str

        name : str

        trailing_uri : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Proxy GET request to provider inference endpoint

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.inference_gateway.provider_proxy_get(
                workspace="workspace",
                name="name",
                trailing_uri="trailing_uri",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.provider_proxy_get(
            workspace, name, trailing_uri, request_options=request_options
        )
        return _response.data

    async def provider_proxy_post(
        self,
        workspace: str,
        name: str,
        trailing_uri: str,
        *,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Proxy requests to provider inference endpoints.

        Parameters
        ----------
        workspace : str

        name : str

        trailing_uri : str

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Proxy POST request to provider inference endpoint

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.inference_gateway.provider_proxy_post(
                workspace="workspace",
                name="name",
                trailing_uri="trailing_uri",
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.provider_proxy_post(
            workspace, name, trailing_uri, request=request, request_options=request_options
        )
        return _response.data

    async def provider_proxy_put(
        self,
        workspace: str,
        name: str,
        trailing_uri: str,
        *,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Proxy requests to provider inference endpoints.

        Parameters
        ----------
        workspace : str

        name : str

        trailing_uri : str

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Proxy PUT request to provider inference endpoint

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.inference_gateway.provider_proxy_put(
                workspace="workspace",
                name="name",
                trailing_uri="trailing_uri",
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.provider_proxy_put(
            workspace, name, trailing_uri, request=request, request_options=request_options
        )
        return _response.data

    async def provider_proxy_delete(
        self, workspace: str, name: str, trailing_uri: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Any:
        """
        Proxy requests to provider inference endpoints.

        Parameters
        ----------
        workspace : str

        name : str

        trailing_uri : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Any
            Proxy DELETE request to provider inference endpoint

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.inference_gateway.provider_proxy_delete(
                workspace="workspace",
                name="name",
                trailing_uri="trailing_uri",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.provider_proxy_delete(
            workspace, name, trailing_uri, request_options=request_options
        )
        return _response.data

    async def provider_proxy_patch(
        self,
        workspace: str,
        name: str,
        trailing_uri: str,
        *,
        request: typing.Dict[str, typing.Any],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> typing.Dict[str, typing.Any]:
        """
        Proxy requests to provider inference endpoints.

        Parameters
        ----------
        workspace : str

        name : str

        trailing_uri : str

        request : typing.Dict[str, typing.Any]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Proxy PATCH request to provider inference endpoint

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.inference_gateway.provider_proxy_patch(
                workspace="workspace",
                name="name",
                trailing_uri="trailing_uri",
                request={"key": "value"},
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.provider_proxy_patch(
            workspace, name, trailing_uri, request=request, request_options=request_options
        )
        return _response.data

    async def provider_ready(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Check if a model provider is registered in the gateway's cache.

        This is a lightweight endpoint that only checks the gateway's internal state,
        without making any requests to the actual provider backend. Use this to verify
        the gateway is ready to route requests to a provider after deployment.

        Returns:
            200 OK with provider info if the provider is registered
            404 Not Found if the provider is not yet in the gateway's cache

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Check if the gateway can route to a provider

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.inference_gateway.provider_ready(
                workspace="workspace",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.provider_ready(workspace, name, request_options=request_options)
        return _response.data
