# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

[project]
name = "nmp-gym-tasks"
version = "0.0.0"
requires-python = ">=3.13.14,<3.14"
dependencies = [
    "nemo-gym==0.5.0",
    "tiktoken==0.13.0",
]

[tool.uv]
constraint-dependencies = [
    "mlflow>=3.15.0,<3.16.0",
    "mlflow-skinny>=3.15.0,<3.16.0",
    "sqlparse>=0.6.0,<0.7",
    "wandb>=0.29.0",
]
required-version = ">=0.9.14,<0.10.0"
environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
    "sys_platform == 'linux' and platform_machine == 'aarch64'",
]
