# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.delete_response import DeleteResponse
from ..types.role_binding import RoleBinding
from ..types.role_binding_filter import RoleBindingFilter
from ..types.role_bindings_page import RoleBindingsPage
from .raw_client import AsyncRawIamClient, RawIamClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class IamClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawIamClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawIamClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawIamClient
        """
        return self._raw_client

    def list_role_bindings(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort: typing.Optional[str] = None,
        filter: typing.Optional[RoleBindingFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RoleBindingsPage:
        """
        List all role bindings (Platform Admin only)

        Parameters
        ----------
        page : typing.Optional[int]
            Page number.

        page_size : typing.Optional[int]
            Page size.

        sort : typing.Optional[str]
            The field to sort by. To sort in decreasing order, use `-` in front of the field name.

        filter : typing.Optional[RoleBindingFilter]
            Filter role bindings by principal, workspace, role, granted_by, is_active, granted_at, and revoked_at.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RoleBindingsPage
            Successful Response

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.iam.list_role_bindings()
        """
        _response = self._raw_client.list_role_bindings(
            page=page, page_size=page_size, sort=sort, filter=filter, request_options=request_options
        )
        return _response.data

    def create_role_binding(
        self,
        *,
        principal: str,
        role: str,
        wait_role_propagation: typing.Optional[bool] = None,
        workspace: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RoleBinding:
        """
        Create a new role binding (Platform Admin only)

        Parameters
        ----------
        principal : str
            The principal identifier (email, user ID, or group ID)

        role : str
            The role name (e.g., 'Viewer', 'Editor', 'Admin')

        wait_role_propagation : typing.Optional[bool]
            If true, wait for role to propagate before returning (default: true). Set to false for bulk operations.

        workspace : typing.Optional[str]
            The workspace this binding applies to. None for platform-level roles.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RoleBinding
            Successful Response

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.iam.create_role_binding(
            principal="principal",
            role="role",
        )
        """
        _response = self._raw_client.create_role_binding(
            principal=principal,
            role=role,
            wait_role_propagation=wait_role_propagation,
            workspace=workspace,
            request_options=request_options,
        )
        return _response.data

    def get_role_binding(self, name: str, *, request_options: typing.Optional[RequestOptions] = None) -> RoleBinding:
        """
        Get a specific role binding (Platform Admin only)

        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RoleBinding
            Successful Response

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.iam.get_role_binding(
            name="name",
        )
        """
        _response = self._raw_client.get_role_binding(name, request_options=request_options)
        return _response.data

    def revoke_role_binding(
        self,
        name: str,
        *,
        wait_role_propagation: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteResponse:
        """
        Revoke a role binding (Platform Admin only)

        Parameters
        ----------
        name : str

        wait_role_propagation : typing.Optional[bool]
            If true, wait for role to propagate before returning (default: true). Set to false for bulk operations.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteResponse
            Successful Response

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.iam.revoke_role_binding(
            name="name",
        )
        """
        _response = self._raw_client.revoke_role_binding(
            name, wait_role_propagation=wait_role_propagation, request_options=request_options
        )
        return _response.data


class AsyncIamClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawIamClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawIamClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawIamClient
        """
        return self._raw_client

    async def list_role_bindings(
        self,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort: typing.Optional[str] = None,
        filter: typing.Optional[RoleBindingFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RoleBindingsPage:
        """
        List all role bindings (Platform Admin only)

        Parameters
        ----------
        page : typing.Optional[int]
            Page number.

        page_size : typing.Optional[int]
            Page size.

        sort : typing.Optional[str]
            The field to sort by. To sort in decreasing order, use `-` in front of the field name.

        filter : typing.Optional[RoleBindingFilter]
            Filter role bindings by principal, workspace, role, granted_by, is_active, granted_at, and revoked_at.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RoleBindingsPage
            Successful Response

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.iam.list_role_bindings()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_role_bindings(
            page=page, page_size=page_size, sort=sort, filter=filter, request_options=request_options
        )
        return _response.data

    async def create_role_binding(
        self,
        *,
        principal: str,
        role: str,
        wait_role_propagation: typing.Optional[bool] = None,
        workspace: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> RoleBinding:
        """
        Create a new role binding (Platform Admin only)

        Parameters
        ----------
        principal : str
            The principal identifier (email, user ID, or group ID)

        role : str
            The role name (e.g., 'Viewer', 'Editor', 'Admin')

        wait_role_propagation : typing.Optional[bool]
            If true, wait for role to propagate before returning (default: true). Set to false for bulk operations.

        workspace : typing.Optional[str]
            The workspace this binding applies to. None for platform-level roles.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RoleBinding
            Successful Response

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.iam.create_role_binding(
                principal="principal",
                role="role",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_role_binding(
            principal=principal,
            role=role,
            wait_role_propagation=wait_role_propagation,
            workspace=workspace,
            request_options=request_options,
        )
        return _response.data

    async def get_role_binding(
        self, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RoleBinding:
        """
        Get a specific role binding (Platform Admin only)

        Parameters
        ----------
        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RoleBinding
            Successful Response

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.iam.get_role_binding(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_role_binding(name, request_options=request_options)
        return _response.data

    async def revoke_role_binding(
        self,
        name: str,
        *,
        wait_role_propagation: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteResponse:
        """
        Revoke a role binding (Platform Admin only)

        Parameters
        ----------
        name : str

        wait_role_propagation : typing.Optional[bool]
            If true, wait for role to propagate before returning (default: true). Set to false for bulk operations.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteResponse
            Successful Response

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.iam.revoke_role_binding(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.revoke_role_binding(
            name, wait_role_propagation=wait_role_propagation, request_options=request_options
        )
        return _response.data
