apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-07-09T17:31:22Z"
  labels:
    managed-by: nemo-deployments
    nemo.nvidia.com/backoff-limit: "6"
    nemo.nvidia.com/deployment-config: smoke-http-cfg
    nemo.nvidia.com/deployment-name: smoke-http-svc
    nemo.nvidia.com/deployment-workspace: default
    nemo.nvidia.com/restart-policy: Always
  name: dep-default-smoke-http-svc-86cdfab7
  namespace: tbray-dev
  resourceVersion: "286258073"
  uid: 5f8564f2-759a-4989-bc49-ba86d879c35e
spec:
  clusterIP: 10.96.13.231
  clusterIPs:
  - 10.96.13.231
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: dep-default-smoke-http-svc-86cdfab7
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
