{{/*
SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nemo-zitadel-workload-token-reviewer
  labels:
    {{- include "nemo-platform-zitadel.labels" . | nindent 4 }}
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nemo-zitadel-workload-token-reviewer
  labels:
    {{- include "nemo-platform-zitadel.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nemo-zitadel-workload-token-reviewer
subjects:
  - kind: ServiceAccount
    name: {{ .Values.integration.nemoPlatform.apiServiceAccountName }}
    namespace: {{ include "nemo-platform-zitadel.namespace" . }}
