# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.fileset_file_output import FilesetFileOutput
from ..types.fileset_filter import FilesetFilter
from ..types.fileset_metadata_input import FilesetMetadataInput
from ..types.fileset_output import FilesetOutput
from ..types.fileset_outputs_page import FilesetOutputsPage
from ..types.fileset_purpose import FilesetPurpose
from ..types.generic_sort_field import GenericSortField
from ..types.list_fileset_files_response import ListFilesetFilesResponse
from .raw_client import AsyncRawFilesClient, RawFilesClient
from .types.create_fileset_request_storage import CreateFilesetRequestStorage

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class FilesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawFilesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawFilesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawFilesClient
        """
        return self._raw_client

    def list_filesets(
        self,
        workspace: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort: typing.Optional[GenericSortField] = None,
        filter: typing.Optional[FilesetFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FilesetOutputsPage:
        """
        List Filesets endpoint with filtering and pagination.

        Supports filtering by name, description, purpose, storage_type, created_at, and updated_at via query parameters.
        Returns paginated results with sorting options.

        Parameters
        ----------
        workspace : str

        page : typing.Optional[int]
            Page number.

        page_size : typing.Optional[int]
            Page size.

        sort : typing.Optional[GenericSortField]
            The field to sort by. To sort in decreasing order, use `-` in front of the field name.

        filter : typing.Optional[FilesetFilter]
            Filter filesets by name, description, purpose, storage_type, created_at, and updated_at.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FilesetOutputsPage
            Successful Response

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.files.list_filesets(
            workspace="workspace",
        )
        """
        _response = self._raw_client.list_filesets(
            workspace, page=page, page_size=page_size, sort=sort, filter=filter, request_options=request_options
        )
        return _response.data

    def create_fileset(
        self,
        workspace: str,
        *,
        name: str,
        description: typing.Optional[str] = OMIT,
        project: typing.Optional[str] = OMIT,
        storage: typing.Optional[CreateFilesetRequestStorage] = OMIT,
        purpose: typing.Optional[FilesetPurpose] = OMIT,
        metadata: typing.Optional[FilesetMetadataInput] = OMIT,
        custom_fields: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        cache: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FilesetOutput:
        """
        Create a new fileset.

        If no storage configuration is provided, the default storage backend will be used.

        Parameters
        ----------
        workspace : str

        name : str
            The name of the fileset. Allowed characters: letters (a-z, A-Z), digits (0-9), underscores, hyphens, and dots.

        description : typing.Optional[str]
            The description of the fileset.

        project : typing.Optional[str]
            The name of the project associated with this fileset.

        storage : typing.Optional[CreateFilesetRequestStorage]
            The storage configuration for the fileset. If not provided, uses default storage.

        purpose : typing.Optional[FilesetPurpose]
            The purpose of the fileset.

        metadata : typing.Optional[FilesetMetadataInput]
            Purpose-specific metadata. Use the purpose as the key (e.g., {dataset: {...}}).

        custom_fields : typing.Optional[typing.Dict[str, typing.Any]]
            Custom fields for the fileset.

        cache : typing.Optional[bool]
            Cache all files after creation. Only applies to external storage.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FilesetOutput
            Successful Response

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.files.create_fileset(
            workspace="workspace",
            name="training-data-v1",
        )
        """
        _response = self._raw_client.create_fileset(
            workspace,
            name=name,
            description=description,
            project=project,
            storage=storage,
            purpose=purpose,
            metadata=metadata,
            custom_fields=custom_fields,
            cache=cache,
            request_options=request_options,
        )
        return _response.data

    def retrieve_fileset(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FilesetOutput:
        """
        Get Fileset by Workspace and Name.

        Returns the details of a specific fileset identified by its workspace and name.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FilesetOutput
            Successful Response

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.files.retrieve_fileset(
            workspace="workspace",
            name="name",
        )
        """
        _response = self._raw_client.retrieve_fileset(workspace, name, request_options=request_options)
        return _response.data

    def delete_fileset(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FilesetOutput:
        """
        Delete Fileset.

        Permanently deletes a fileset from the platform.
        Returns metadata about the deleted fileset.
        For local storage backends, this also deletes the underlying files.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FilesetOutput
            Successful Response

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.files.delete_fileset(
            workspace="workspace",
            name="name",
        )
        """
        _response = self._raw_client.delete_fileset(workspace, name, request_options=request_options)
        return _response.data

    def update_fileset_metadata(
        self,
        workspace: str,
        name: str,
        *,
        description: typing.Optional[str] = OMIT,
        project: typing.Optional[str] = OMIT,
        purpose: typing.Optional[FilesetPurpose] = OMIT,
        metadata: typing.Optional[FilesetMetadataInput] = OMIT,
        custom_fields: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FilesetOutput:
        """
        Update Fileset Metadata.

        Parameters
        ----------
        workspace : str

        name : str

        description : typing.Optional[str]
            The description of the fileset.

        project : typing.Optional[str]
            The name of the project associated with this fileset.

        purpose : typing.Optional[FilesetPurpose]
            The purpose of the fileset.

        metadata : typing.Optional[FilesetMetadataInput]
            Purpose-specific metadata. Use the purpose as the key (e.g., {dataset: {...}}).

        custom_fields : typing.Optional[typing.Dict[str, typing.Any]]
            Custom fields for the fileset.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FilesetOutput
            Successful Response

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.files.update_fileset_metadata(
            workspace="workspace",
            name="name",
        )
        """
        _response = self._raw_client.update_fileset_metadata(
            workspace,
            name,
            description=description,
            project=project,
            purpose=purpose,
            metadata=metadata,
            custom_fields=custom_fields,
            request_options=request_options,
        )
        return _response.data

    def download_file_apis_files_v2workspaces_workspace_filesets_name_path_get(
        self, workspace: str, name: str, path: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[bytes]:
        """
        Download file content from a fileset.

        Supports HTTP Range requests for partial content retrieval (status 206).
        Returns the full file content (status 200) if no Range header is provided.
        For external resources (HuggingFace, NGC), content is cached locally on first access.

        Parameters
        ----------
        workspace : str

        name : str

        path : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            Successful Response

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.files.download_file_apis_files_v2workspaces_workspace_filesets_name_path_get(
            workspace="workspace",
            name="name",
            path="path",
        )
        """
        with self._raw_client.download_file_apis_files_v2workspaces_workspace_filesets_name_path_get(
            workspace, name, path, request_options=request_options
        ) as r:
            yield from r.data

    def upload_file_apis_files_v2workspaces_workspace_filesets_name_path_put(
        self,
        workspace: str,
        name: str,
        path: str,
        *,
        request: typing.Union[bytes, typing.Iterator[bytes], typing.AsyncIterator[bytes]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FilesetFileOutput:
        """
        Upload file content to a fileset.

        Parameters
        ----------
        workspace : str

        name : str

        path : str

        request : typing.Union[bytes, typing.Iterator[bytes], typing.AsyncIterator[bytes]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FilesetFileOutput
            Successful Response
        """
        _response = self._raw_client.upload_file_apis_files_v2workspaces_workspace_filesets_name_path_put(
            workspace, name, path, request=request, request_options=request_options
        )
        return _response.data

    def delete_file_apis_files_v2workspaces_workspace_filesets_name_path_delete(
        self, workspace: str, name: str, path: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FilesetFileOutput:
        """
        Delete a specific file from a fileset.

        Permanently deletes the file from the storage backend.
        Returns metadata about the deleted file.

        Parameters
        ----------
        workspace : str

        name : str

        path : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FilesetFileOutput
            Successful Response

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.files.delete_file_apis_files_v2workspaces_workspace_filesets_name_path_delete(
            workspace="workspace",
            name="name",
            path="path",
        )
        """
        _response = self._raw_client.delete_file_apis_files_v2workspaces_workspace_filesets_name_path_delete(
            workspace, name, path, request_options=request_options
        )
        return _response.data

    def head_file_apis_files_v2workspaces_workspace_filesets_name_path_head(
        self, workspace: str, name: str, path: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, str]:
        """
        Get file metadata without downloading content.

        HEAD requests are often used before Range GETs to ensure the server
        supports partial downloads (e.g., DuckDB's httpfs).
        Returns Accept-Ranges, Content-Length, and Content-Type headers.

        Parameters
        ----------
        workspace : str

        name : str

        path : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, str]
            Successful Response

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.files.head_file_apis_files_v2workspaces_workspace_filesets_name_path_head(
            workspace="workspace",
            name="name",
            path="path",
        )
        """
        _response = self._raw_client.head_file_apis_files_v2workspaces_workspace_filesets_name_path_head(
            workspace, name, path, request_options=request_options
        )
        return _response.headers

    def list_fileset_files(
        self,
        workspace: str,
        name: str,
        *,
        path: typing.Optional[str] = None,
        include_cache_status: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListFilesetFilesResponse:
        """
        List Files in Fileset.

        Returns a list of files stored in the specified fileset.
        Optionally filter by path prefix to list files under a specific directory.

        Each file includes a cache_status field:
        - "not_cacheable": File is on default storage, caching not applicable
        - "cached": File exists in cache storage
        - "caching": File is currently being downloaded and cached
        - "not_cached": File not in cache, will be cached on next download
        - null: External storage, but cache status not checked (use include_cache_status=true)

        Parameters
        ----------
        workspace : str

        name : str

        path : typing.Optional[str]
            Filter files by path prefix

        include_cache_status : typing.Optional[bool]
            Check and return cache status for each file. When false, storage files return null for cache_status.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListFilesetFilesResponse
            Successful Response

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.files.list_fileset_files(
            workspace="workspace",
            name="name",
        )
        """
        _response = self._raw_client.list_fileset_files(
            workspace, name, path=path, include_cache_status=include_cache_status, request_options=request_options
        )
        return _response.data


class AsyncFilesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawFilesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawFilesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawFilesClient
        """
        return self._raw_client

    async def list_filesets(
        self,
        workspace: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort: typing.Optional[GenericSortField] = None,
        filter: typing.Optional[FilesetFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FilesetOutputsPage:
        """
        List Filesets endpoint with filtering and pagination.

        Supports filtering by name, description, purpose, storage_type, created_at, and updated_at via query parameters.
        Returns paginated results with sorting options.

        Parameters
        ----------
        workspace : str

        page : typing.Optional[int]
            Page number.

        page_size : typing.Optional[int]
            Page size.

        sort : typing.Optional[GenericSortField]
            The field to sort by. To sort in decreasing order, use `-` in front of the field name.

        filter : typing.Optional[FilesetFilter]
            Filter filesets by name, description, purpose, storage_type, created_at, and updated_at.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FilesetOutputsPage
            Successful Response

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.files.list_filesets(
                workspace="workspace",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_filesets(
            workspace, page=page, page_size=page_size, sort=sort, filter=filter, request_options=request_options
        )
        return _response.data

    async def create_fileset(
        self,
        workspace: str,
        *,
        name: str,
        description: typing.Optional[str] = OMIT,
        project: typing.Optional[str] = OMIT,
        storage: typing.Optional[CreateFilesetRequestStorage] = OMIT,
        purpose: typing.Optional[FilesetPurpose] = OMIT,
        metadata: typing.Optional[FilesetMetadataInput] = OMIT,
        custom_fields: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        cache: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FilesetOutput:
        """
        Create a new fileset.

        If no storage configuration is provided, the default storage backend will be used.

        Parameters
        ----------
        workspace : str

        name : str
            The name of the fileset. Allowed characters: letters (a-z, A-Z), digits (0-9), underscores, hyphens, and dots.

        description : typing.Optional[str]
            The description of the fileset.

        project : typing.Optional[str]
            The name of the project associated with this fileset.

        storage : typing.Optional[CreateFilesetRequestStorage]
            The storage configuration for the fileset. If not provided, uses default storage.

        purpose : typing.Optional[FilesetPurpose]
            The purpose of the fileset.

        metadata : typing.Optional[FilesetMetadataInput]
            Purpose-specific metadata. Use the purpose as the key (e.g., {dataset: {...}}).

        custom_fields : typing.Optional[typing.Dict[str, typing.Any]]
            Custom fields for the fileset.

        cache : typing.Optional[bool]
            Cache all files after creation. Only applies to external storage.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FilesetOutput
            Successful Response

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.files.create_fileset(
                workspace="workspace",
                name="training-data-v1",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_fileset(
            workspace,
            name=name,
            description=description,
            project=project,
            storage=storage,
            purpose=purpose,
            metadata=metadata,
            custom_fields=custom_fields,
            cache=cache,
            request_options=request_options,
        )
        return _response.data

    async def retrieve_fileset(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FilesetOutput:
        """
        Get Fileset by Workspace and Name.

        Returns the details of a specific fileset identified by its workspace and name.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FilesetOutput
            Successful Response

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.files.retrieve_fileset(
                workspace="workspace",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve_fileset(workspace, name, request_options=request_options)
        return _response.data

    async def delete_fileset(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FilesetOutput:
        """
        Delete Fileset.

        Permanently deletes a fileset from the platform.
        Returns metadata about the deleted fileset.
        For local storage backends, this also deletes the underlying files.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FilesetOutput
            Successful Response

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.files.delete_fileset(
                workspace="workspace",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_fileset(workspace, name, request_options=request_options)
        return _response.data

    async def update_fileset_metadata(
        self,
        workspace: str,
        name: str,
        *,
        description: typing.Optional[str] = OMIT,
        project: typing.Optional[str] = OMIT,
        purpose: typing.Optional[FilesetPurpose] = OMIT,
        metadata: typing.Optional[FilesetMetadataInput] = OMIT,
        custom_fields: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FilesetOutput:
        """
        Update Fileset Metadata.

        Parameters
        ----------
        workspace : str

        name : str

        description : typing.Optional[str]
            The description of the fileset.

        project : typing.Optional[str]
            The name of the project associated with this fileset.

        purpose : typing.Optional[FilesetPurpose]
            The purpose of the fileset.

        metadata : typing.Optional[FilesetMetadataInput]
            Purpose-specific metadata. Use the purpose as the key (e.g., {dataset: {...}}).

        custom_fields : typing.Optional[typing.Dict[str, typing.Any]]
            Custom fields for the fileset.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FilesetOutput
            Successful Response

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.files.update_fileset_metadata(
                workspace="workspace",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_fileset_metadata(
            workspace,
            name,
            description=description,
            project=project,
            purpose=purpose,
            metadata=metadata,
            custom_fields=custom_fields,
            request_options=request_options,
        )
        return _response.data

    async def download_file_apis_files_v2workspaces_workspace_filesets_name_path_get(
        self, workspace: str, name: str, path: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[bytes]:
        """
        Download file content from a fileset.

        Supports HTTP Range requests for partial content retrieval (status 206).
        Returns the full file content (status 200) if no Range header is provided.
        For external resources (HuggingFace, NGC), content is cached locally on first access.

        Parameters
        ----------
        workspace : str

        name : str

        path : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            Successful Response

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.files.download_file_apis_files_v2workspaces_workspace_filesets_name_path_get(
                workspace="workspace",
                name="name",
                path="path",
            )


        asyncio.run(main())
        """
        async with self._raw_client.download_file_apis_files_v2workspaces_workspace_filesets_name_path_get(
            workspace, name, path, request_options=request_options
        ) as r:
            async for _chunk in r.data:
                yield _chunk

    async def upload_file_apis_files_v2workspaces_workspace_filesets_name_path_put(
        self,
        workspace: str,
        name: str,
        path: str,
        *,
        request: typing.Union[bytes, typing.Iterator[bytes], typing.AsyncIterator[bytes]],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> FilesetFileOutput:
        """
        Upload file content to a fileset.

        Parameters
        ----------
        workspace : str

        name : str

        path : str

        request : typing.Union[bytes, typing.Iterator[bytes], typing.AsyncIterator[bytes]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FilesetFileOutput
            Successful Response
        """
        _response = await self._raw_client.upload_file_apis_files_v2workspaces_workspace_filesets_name_path_put(
            workspace, name, path, request=request, request_options=request_options
        )
        return _response.data

    async def delete_file_apis_files_v2workspaces_workspace_filesets_name_path_delete(
        self, workspace: str, name: str, path: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> FilesetFileOutput:
        """
        Delete a specific file from a fileset.

        Permanently deletes the file from the storage backend.
        Returns metadata about the deleted file.

        Parameters
        ----------
        workspace : str

        name : str

        path : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        FilesetFileOutput
            Successful Response

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.files.delete_file_apis_files_v2workspaces_workspace_filesets_name_path_delete(
                workspace="workspace",
                name="name",
                path="path",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_file_apis_files_v2workspaces_workspace_filesets_name_path_delete(
            workspace, name, path, request_options=request_options
        )
        return _response.data

    async def head_file_apis_files_v2workspaces_workspace_filesets_name_path_head(
        self, workspace: str, name: str, path: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, str]:
        """
        Get file metadata without downloading content.

        HEAD requests are often used before Range GETs to ensure the server
        supports partial downloads (e.g., DuckDB's httpfs).
        Returns Accept-Ranges, Content-Length, and Content-Type headers.

        Parameters
        ----------
        workspace : str

        name : str

        path : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, str]
            Successful Response

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.files.head_file_apis_files_v2workspaces_workspace_filesets_name_path_head(
                workspace="workspace",
                name="name",
                path="path",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.head_file_apis_files_v2workspaces_workspace_filesets_name_path_head(
            workspace, name, path, request_options=request_options
        )
        return _response.headers

    async def list_fileset_files(
        self,
        workspace: str,
        name: str,
        *,
        path: typing.Optional[str] = None,
        include_cache_status: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListFilesetFilesResponse:
        """
        List Files in Fileset.

        Returns a list of files stored in the specified fileset.
        Optionally filter by path prefix to list files under a specific directory.

        Each file includes a cache_status field:
        - "not_cacheable": File is on default storage, caching not applicable
        - "cached": File exists in cache storage
        - "caching": File is currently being downloaded and cached
        - "not_cached": File not in cache, will be cached on next download
        - null: External storage, but cache status not checked (use include_cache_status=true)

        Parameters
        ----------
        workspace : str

        name : str

        path : typing.Optional[str]
            Filter files by path prefix

        include_cache_status : typing.Optional[bool]
            Check and return cache status for each file. When false, storage files return null for cache_status.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListFilesetFilesResponse
            Successful Response

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.files.list_fileset_files(
                workspace="workspace",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_fileset_files(
            workspace, name, path=path, include_cache_status=include_cache_status, request_options=request_options
        )
        return _response.data
