# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

guardrails:
  models:
    fake-model:
      refusal_text: "I'm sorry, I can't respond to that"
      config_ids:
      - default/nemoguard
    # add more models below
