// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import { isVersionConflictError } from '@nemo/common/src/api/common/utils';
import {
  entitiesCreateEntity,
  entitiesDeleteEntityByName,
  entitiesGetEntityById,
  entitiesGetEntityByName,
  entitiesListEntities,
  entitiesUpdateEntityByName,
} from '@nemo/sdk/generated/platform/entity-store';
import { guardrailsCheck } from '@nemo/sdk/generated/platform/guardrails';
import type {
  EntitiesListEntitiesParams,
  GuardrailCheckRequest,
  GuardrailCheckResponse,
  RailsConfig,
} from '@nemo/sdk/generated/platform/schema';
import {
  GUARDRAIL_CHECKS_ENTITY_TYPE,
  type GuardrailCheckData,
  type GuardrailCheckDataInput,
  type GuardrailCheckEntity,
  type GuardrailChecksPage,
  type RunRecord,
} from '@studio/api/guardrail-checks/types';
// Layering wrinkle: this reaches into the components layer. Deliberate — it keeps one
// definition of guardrail identity shared with the config editor's detector catalog.
import { getActivatedGuardrails } from '@studio/components/sidePanels/GuardrailCheckDetailSidePanel/railLabels';
import { getMainModelName } from '@studio/routes/guardrails/GuardrailConfigTab/mainModel';

// ---------------------------------------------------------------------------
// Query keys
// ---------------------------------------------------------------------------

/** Query key for a (optionally filtered/paginated) list of guardrail checks. */
export const getGuardrailChecksQueryKey = (
  workspace: string,
  params?: EntitiesListEntitiesParams
) => ['guardrail-checks', workspace, ...(params ? [params] : [])] as const;

/**
 * Query key for a single guardrail check. `parent` is included when known (it
 * uniquely scopes the check); omit it to build a prefix that matches the check
 * across parents — used for cache invalidation.
 */
export const getGuardrailCheckQueryKey = (workspace: string, name: string, parent?: string) =>
  ['guardrail-check', workspace, name, ...(parent ? [parent] : [])] as const;

/** Build the entity-store `filter` expression that scopes a list to one parent config. */
export const guardrailChecksForConfigFilter = (configId: string): string =>
  JSON.stringify({ parent: configId });

// ---------------------------------------------------------------------------
// CRUD (thin wrappers over the generic entity-store endpoints)
// ---------------------------------------------------------------------------

/** List guardrail checks in a workspace, optionally filtered and paginated. */
export async function listGuardrailChecks(
  workspace: string,
  params?: EntitiesListEntitiesParams,
  signal?: AbortSignal
): Promise<GuardrailChecksPage> {
  const page = await entitiesListEntities(workspace, GUARDRAIL_CHECKS_ENTITY_TYPE, params, signal);
  return { ...page, data: page.data as GuardrailCheckEntity[] };
}

/** Primary access pattern: the checks belonging to a single guardrail config. */
export function listGuardrailChecksForConfig(
  workspace: string,
  configId: string,
  params?: Omit<EntitiesListEntitiesParams, 'filter'>,
  signal?: AbortSignal
): Promise<GuardrailChecksPage> {
  return listGuardrailChecks(
    workspace,
    { ...params, filter: guardrailChecksForConfigFilter(configId) },
    signal
  );
}

/**
 * Fetch a single guardrail check by name. Checks are hard children of a config,
 * so the lookup must be scoped by `parent` (the owning config's entity id) —
 * otherwise a name collision across configs could resolve the wrong entity.
 */
export async function getGuardrailCheck(
  workspace: string,
  name: string,
  parent: string,
  signal?: AbortSignal
): Promise<GuardrailCheckEntity> {
  const entity = await entitiesGetEntityByName(
    workspace,
    GUARDRAIL_CHECKS_ENTITY_TYPE,
    name,
    { parent },
    signal
  );
  return entity as GuardrailCheckEntity;
}

export interface CreateGuardrailCheckInput {
  /** Optional name — auto-generated by the entity-store if omitted. */
  name?: string;
  /** REQUIRED: owning guardrail-config entity id (checks are hard children). */
  parent: string;
  project?: string;
  data: GuardrailCheckDataInput;
}

/** Create a guardrail check as a child of its owning config (`input.parent`). */
export async function createGuardrailCheck(
  workspace: string,
  input: CreateGuardrailCheckInput
): Promise<GuardrailCheckEntity> {
  const data: GuardrailCheckData = { ...input.data, runs: input.data.runs ?? [] };
  const entity = await entitiesCreateEntity(workspace, GUARDRAIL_CHECKS_ENTITY_TYPE, {
    name: input.name,
    parent: input.parent,
    project: input.project,
    data,
  });
  return entity as GuardrailCheckEntity;
}

export interface UpdateGuardrailCheckPatch {
  new_name?: string;
  project?: string;
  data: GuardrailCheckData;
  /** Optimistic-lock token; update fails on mismatch. */
  expected_db_version?: number;
  /** Owning config entity id — required to address child checks by name. */
  parent?: string;
}

/** Update a guardrail check by name (scoped by `patch.parent` when set). */
export async function updateGuardrailCheck(
  workspace: string,
  name: string,
  patch: UpdateGuardrailCheckPatch
): Promise<GuardrailCheckEntity> {
  const entity = await entitiesUpdateEntityByName(
    workspace,
    GUARDRAIL_CHECKS_ENTITY_TYPE,
    name,
    {
      new_name: patch.new_name,
      project: patch.project,
      data: patch.data,
      expected_db_version: patch.expected_db_version,
    },
    patch.parent ? { parent: patch.parent } : undefined
  );
  return entity as GuardrailCheckEntity;
}

/**
 * Delete a guardrail check by name. Requires `parent` (the owning config's entity id)
 * so the correct child entity is addressed when names collide across configs.
 */
export async function deleteGuardrailCheck(
  workspace: string,
  name: string,
  parent: string
): Promise<void> {
  await entitiesDeleteEntityByName(workspace, GUARDRAIL_CHECKS_ENTITY_TYPE, name, { parent });
}

// ---------------------------------------------------------------------------
// Execution / orchestration
// ---------------------------------------------------------------------------

/**
 * Resolve the model to run a check against from its parent config's model list.
 *
 * Only the `main` entry is eligible. Every other entry is a task LLM that a specific rail
 * addresses by `$model=` — sending `system/nemoguard-8b-content-safety` as the generation
 * model would produce a run that looks fine and means nothing.
 *
 * Studio-specific by design: the service reads `request.model`, not the config
 * (`nemo_guardrails_plugin/rails.py:236` — "model name: always request_body['model']"), and
 * injects a placeholder when a `main` entry omits one. Storing the name on the config and
 * reading it back here is how Studio remembers the user's choice; it is not how the
 * service routes. Do not delete the config field on the grounds that the service ignores it.
 */
export function resolveConfigModel(config: RailsConfig | undefined, configLabel: string): string {
  const model = getMainModelName(config?.models);
  if (!model) {
    throw new Error(
      `Guardrail config '${configLabel}' has no main model. Set one on the Configuration tab.`
    );
  }
  return model;
}

/** What the run targeted, for stamping onto the record. */
export interface RunRecordContext {
  /** Parent config db_version. Omitted for a draft run — a draft has no version. */
  configVersion?: number;
  /** True when the run targeted an unsaved draft. */
  isDraft?: boolean;
  /** The config that actually ran, for the activated-guardrail snapshot. */
  config?: RailsConfig;
}

/** Map a /checks response to a persisted run record. */
export function responseToRunRecord(
  response: GuardrailCheckResponse,
  runAt: string,
  context: RunRecordContext = {}
): RunRecord {
  return {
    run_at: runAt,
    status: response.status,
    rails_status: response.rails_status,
    config_ids: response.guardrails_data?.config_ids,
    config_version: context.configVersion,
    ...(context.isDraft ? { is_draft: true } : {}),
    // Resolved now, not at render time: the config that produced this run may be edited
    // (or, for a draft, cease to exist) before anyone opens the result panel.
    activated_guardrails: getActivatedGuardrails(context.config, response.rails_status),
  };
}

/** Low-level: run a request against /checks and return the raw response. Does NOT persist. */
export function executeGuardrailCheck(
  workspace: string,
  request: GuardrailCheckRequest,
  signal?: AbortSignal
): Promise<GuardrailCheckResponse> {
  return guardrailsCheck(workspace, request, signal);
}

/**
 * High-level: resolve the model from the check's parent config, execute against /checks,
 * append the RunRecord, and persist (read-modify-write with optimistic locking).
 *
 * Takes the check entity directly (rather than re-fetching by name) because checks are
 * child entities — name-based lookups must be scoped by `parent`, which the entity carries.
 *
 * `draftConfig` runs the check against an unsaved edit instead of the saved config: it is
 * sent inline (the /checks endpoint accepts a whole RailsConfig, not just an id) and the
 * resulting record is marked as a draft run with no config version.
 */
export async function runGuardrailCheck(
  workspace: string,
  check: GuardrailCheckEntity,
  draftConfig?: RailsConfig
): Promise<{ entity: GuardrailCheckEntity; run: RunRecord }> {
  if (!check.parent) {
    throw new Error(
      `Guardrail check '${check.name}' has no parent config to resolve a model from.`
    );
  }

  const configEntity = await entitiesGetEntityById(check.parent);
  // A guardrail_config entity nests the rails config under `data.data`
  // (`data` also carries the config's description).
  const savedData = (configEntity.data as { data?: RailsConfig }).data;
  // Still fetched on the draft path: `persistRun` needs the entity, and its name is the
  // label in error messages.
  const effectiveConfig = draftConfig ?? savedData;
  const model = resolveConfigModel(effectiveConfig, configEntity.name);

  const request: GuardrailCheckRequest = {
    model,
    messages: check.data.messages,
    // A draft has no id to reference, so it travels whole. Never both: the service's
    // validator nulls out `config_ids` when `config` is an object, which would make the
    // request's meaning non-obvious from the wire.
    //
    // Draft wins over a check's stored `guardrails`: the user explicitly chose the target,
    // and silently running something else would be worse than ignoring the override.
    guardrails: draftConfig
      ? { config: draftConfig }
      : (check.data.guardrails ?? { config_ids: [configEntity.name] }),
  };

  const response = await executeGuardrailCheck(workspace, request);
  const run = responseToRunRecord(response, new Date().toISOString(), {
    configVersion: draftConfig ? undefined : configEntity.db_version,
    isDraft: Boolean(draftConfig),
    config: effectiveConfig,
  });

  const entity = await persistRun(workspace, check, run);

  return { entity, run };
}

// A 409 only means `data.runs` came from a stale snapshot, so re-read and re-append rather
// than discard a run that already cost an LLM round trip.
async function persistRun(
  workspace: string,
  check: GuardrailCheckEntity,
  run: RunRecord
): Promise<GuardrailCheckEntity> {
  const write = (base: GuardrailCheckEntity) =>
    updateGuardrailCheck(workspace, base.name, {
      data: { ...base.data, runs: [...base.data.runs, run] },
      expected_db_version: base.db_version,
      parent: base.parent,
    });

  try {
    return await write(check);
  } catch (error) {
    if (!isVersionConflictError(error) || !check.parent) throw error;
    const latest = await getGuardrailCheck(workspace, check.name, check.parent);
    return write(latest);
  }
}

/** Batch execution — backs the "Re-run N Tests" action. Failures are captured per check. */
export function runGuardrailChecks(
  workspace: string,
  checks: GuardrailCheckEntity[],
  draftConfig?: RailsConfig
): Promise<Array<{ name: string; run: RunRecord } | { name: string; error: Error }>> {
  return Promise.all(
    checks.map(async (check) => {
      try {
        const { run } = await runGuardrailCheck(workspace, check, draftConfig);
        return { name: check.name, run };
      } catch (error) {
        return {
          name: check.name,
          error: error instanceof Error ? error : new Error(String(error)),
        };
      }
    })
  );
}
