// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import {
  entitiesCreateEntity,
  entitiesDeleteEntityByName,
  entitiesGetEntityById,
  entitiesGetEntityByName,
  entitiesListEntities,
  entitiesUpdateEntityByName,
  guardrailsCheck,
} from '@nemo/sdk/generated/platform/api';
import type {
  EntitiesListEntitiesParams,
  GuardrailCheckRequest,
  GuardrailCheckResponse,
  RailsConfigOutput,
} from '@nemo/sdk/generated/platform/schema';
import {
  GUARDRAIL_CHECKS_ENTITY_TYPE,
  type GuardrailCheckData,
  type GuardrailCheckDataInput,
  type GuardrailCheckEntity,
  type GuardrailChecksPage,
  type RunRecord,
} from '@studio/api/guardrail-checks/types';

// ---------------------------------------------------------------------------
// Query keys
// ---------------------------------------------------------------------------

/** Query key for a (optionally filtered/paginated) list of guardrail checks. */
export const getGuardrailChecksQueryKey = (
  workspace: string,
  params?: EntitiesListEntitiesParams
) => ['guardrail-checks', workspace, ...(params ? [params] : [])] as const;

/**
 * Query key for a single guardrail check. `parent` is included when known (it
 * uniquely scopes the check); omit it to build a prefix that matches the check
 * across parents — used for cache invalidation.
 */
export const getGuardrailCheckQueryKey = (workspace: string, name: string, parent?: string) =>
  ['guardrail-check', workspace, name, ...(parent ? [parent] : [])] as const;

/** Build the entity-store `filter` expression that scopes a list to one parent config. */
export const guardrailChecksForConfigFilter = (configId: string): string =>
  JSON.stringify({ parent: configId });

// ---------------------------------------------------------------------------
// CRUD (thin wrappers over the generic entity-store endpoints)
// ---------------------------------------------------------------------------

/** List guardrail checks in a workspace, optionally filtered and paginated. */
export async function listGuardrailChecks(
  workspace: string,
  params?: EntitiesListEntitiesParams,
  signal?: AbortSignal
): Promise<GuardrailChecksPage> {
  const page = await entitiesListEntities(workspace, GUARDRAIL_CHECKS_ENTITY_TYPE, params, signal);
  return { ...page, data: page.data as GuardrailCheckEntity[] };
}

/** Primary access pattern: the checks belonging to a single guardrail config. */
export function listGuardrailChecksForConfig(
  workspace: string,
  configId: string,
  params?: Omit<EntitiesListEntitiesParams, 'filter'>,
  signal?: AbortSignal
): Promise<GuardrailChecksPage> {
  return listGuardrailChecks(
    workspace,
    { ...params, filter: guardrailChecksForConfigFilter(configId) },
    signal
  );
}

/**
 * Fetch a single guardrail check by name. Checks are hard children of a config,
 * so the lookup must be scoped by `parent` (the owning config's entity id) —
 * otherwise a name collision across configs could resolve the wrong entity.
 */
export async function getGuardrailCheck(
  workspace: string,
  name: string,
  parent: string,
  signal?: AbortSignal
): Promise<GuardrailCheckEntity> {
  const entity = await entitiesGetEntityByName(
    workspace,
    GUARDRAIL_CHECKS_ENTITY_TYPE,
    name,
    { parent },
    signal
  );
  return entity as GuardrailCheckEntity;
}

export interface CreateGuardrailCheckInput {
  /** Optional name — auto-generated by the entity-store if omitted. */
  name?: string;
  /** REQUIRED: owning guardrail-config entity id (checks are hard children). */
  parent: string;
  project?: string;
  data: GuardrailCheckDataInput;
}

/** Create a guardrail check as a child of its owning config (`input.parent`). */
export async function createGuardrailCheck(
  workspace: string,
  input: CreateGuardrailCheckInput
): Promise<GuardrailCheckEntity> {
  const data: GuardrailCheckData = { ...input.data, runs: input.data.runs ?? [] };
  const entity = await entitiesCreateEntity(workspace, GUARDRAIL_CHECKS_ENTITY_TYPE, {
    name: input.name,
    parent: input.parent,
    project: input.project,
    data,
  });
  return entity as GuardrailCheckEntity;
}

export interface UpdateGuardrailCheckPatch {
  new_name?: string;
  project?: string;
  data: GuardrailCheckData;
  /** Optimistic-lock token; update fails on mismatch. */
  expected_db_version?: number;
  /** Owning config entity id — required to address child checks by name. */
  parent?: string;
}

/** Update a guardrail check by name (scoped by `patch.parent` when set). */
export async function updateGuardrailCheck(
  workspace: string,
  name: string,
  patch: UpdateGuardrailCheckPatch
): Promise<GuardrailCheckEntity> {
  const entity = await entitiesUpdateEntityByName(
    workspace,
    GUARDRAIL_CHECKS_ENTITY_TYPE,
    name,
    {
      new_name: patch.new_name,
      project: patch.project,
      data: patch.data,
      expected_db_version: patch.expected_db_version,
    },
    patch.parent ? { parent: patch.parent } : undefined
  );
  return entity as GuardrailCheckEntity;
}

/**
 * Delete a guardrail check by name. Requires `parent` (the owning config's entity id)
 * so the correct child entity is addressed when names collide across configs.
 */
export async function deleteGuardrailCheck(
  workspace: string,
  name: string,
  parent: string
): Promise<void> {
  await entitiesDeleteEntityByName(workspace, GUARDRAIL_CHECKS_ENTITY_TYPE, name, { parent });
}

// ---------------------------------------------------------------------------
// Execution / orchestration
// ---------------------------------------------------------------------------

/**
 * Resolve the model to run a check against from its parent config's model list.
 * NeMo Guardrails configs mark the primary generation model with `type: 'main'`;
 * we fall back to the first model that declares a `model` reference.
 */
export function resolveConfigModel(
  config: RailsConfigOutput | undefined,
  configLabel: string
): string {
  const models = config?.models ?? [];
  const main = models.find((m) => m.type === 'main' && m.model);
  const chosen = main ?? models.find((m) => m.model);
  if (!chosen?.model) {
    throw new Error(`Guardrail config '${configLabel}' has no usable model to run checks against.`);
  }
  return chosen.model;
}

/** Map a /checks response to a persisted run record. */
export function responseToRunRecord(
  response: GuardrailCheckResponse,
  runAt: string,
  configVersion?: number
): RunRecord {
  return {
    run_at: runAt,
    status: response.status,
    rails_status: response.rails_status,
    config_ids: response.guardrails_data?.config_ids,
    config_version: configVersion,
  };
}

/** Low-level: run a request against /checks and return the raw response. Does NOT persist. */
export function executeGuardrailCheck(
  workspace: string,
  request: GuardrailCheckRequest,
  signal?: AbortSignal
): Promise<GuardrailCheckResponse> {
  return guardrailsCheck(workspace, request, signal);
}

/**
 * High-level: resolve the model from the check's parent config, execute against /checks,
 * append the RunRecord, and persist (read-modify-write with optimistic locking).
 *
 * Takes the check entity directly (rather than re-fetching by name) because checks are
 * child entities — name-based lookups must be scoped by `parent`, which the entity carries.
 */
export async function runGuardrailCheck(
  workspace: string,
  check: GuardrailCheckEntity
): Promise<{ entity: GuardrailCheckEntity; run: RunRecord }> {
  if (!check.parent) {
    throw new Error(
      `Guardrail check '${check.name}' has no parent config to resolve a model from.`
    );
  }

  const configEntity = await entitiesGetEntityById(check.parent);
  // A guardrail_config entity nests the rails config under `data.data`
  // (`data` also carries the config's description).
  const configData = (configEntity.data as { data?: RailsConfigOutput }).data;
  const model = resolveConfigModel(configData, configEntity.name);

  const request: GuardrailCheckRequest = {
    model,
    messages: check.data.messages,
    // The check references its config by name (the /checks endpoint resolves config_ids to
    // `workspace/name`), unless the check carries explicit guardrails options.
    guardrails: check.data.guardrails ?? { config_ids: [configEntity.name] },
  };

  const response = await executeGuardrailCheck(workspace, request);
  const run = responseToRunRecord(response, new Date().toISOString(), configEntity.db_version);

  const entity = await updateGuardrailCheck(workspace, check.name, {
    data: { ...check.data, runs: [...check.data.runs, run] },
    expected_db_version: check.db_version,
    parent: check.parent,
  });

  return { entity, run };
}

/** Batch execution — backs the "Re-run N Tests" action. Failures are captured per check. */
export function runGuardrailChecks(
  workspace: string,
  checks: GuardrailCheckEntity[]
): Promise<Array<{ name: string; run: RunRecord } | { name: string; error: Error }>> {
  return Promise.all(
    checks.map(async (check) => {
      try {
        const { run } = await runGuardrailCheck(workspace, check);
        return { name: check.name, run };
      } catch (error) {
        return {
          name: check.name,
          error: error instanceof Error ? error : new Error(String(error)),
        };
      }
    })
  );
}
