# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .guardrail_check_request_function_call import GuardrailCheckRequestFunctionCall
    from .guardrail_check_request_messages_item import (
        GuardrailCheckRequestMessagesItem,
        GuardrailCheckRequestMessagesItem_Assistant,
        GuardrailCheckRequestMessagesItem_Function,
        GuardrailCheckRequestMessagesItem_System,
        GuardrailCheckRequestMessagesItem_Tool,
        GuardrailCheckRequestMessagesItem_User,
    )
    from .guardrail_check_request_stop import GuardrailCheckRequestStop
    from .guardrail_check_request_tool_choice import GuardrailCheckRequestToolChoice
_dynamic_imports: typing.Dict[str, str] = {
    "GuardrailCheckRequestFunctionCall": ".guardrail_check_request_function_call",
    "GuardrailCheckRequestMessagesItem": ".guardrail_check_request_messages_item",
    "GuardrailCheckRequestMessagesItem_Assistant": ".guardrail_check_request_messages_item",
    "GuardrailCheckRequestMessagesItem_Function": ".guardrail_check_request_messages_item",
    "GuardrailCheckRequestMessagesItem_System": ".guardrail_check_request_messages_item",
    "GuardrailCheckRequestMessagesItem_Tool": ".guardrail_check_request_messages_item",
    "GuardrailCheckRequestMessagesItem_User": ".guardrail_check_request_messages_item",
    "GuardrailCheckRequestStop": ".guardrail_check_request_stop",
    "GuardrailCheckRequestToolChoice": ".guardrail_check_request_tool_choice",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "GuardrailCheckRequestFunctionCall",
    "GuardrailCheckRequestMessagesItem",
    "GuardrailCheckRequestMessagesItem_Assistant",
    "GuardrailCheckRequestMessagesItem_Function",
    "GuardrailCheckRequestMessagesItem_System",
    "GuardrailCheckRequestMessagesItem_Tool",
    "GuardrailCheckRequestMessagesItem_User",
    "GuardrailCheckRequestStop",
    "GuardrailCheckRequestToolChoice",
]
