# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.conflict_error import ConflictError
from ..errors.not_found_error import NotFoundError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.container_executor_config import ContainerExecutorConfig
from ..types.engine import Engine
from ..types.model_deployment_config import ModelDeploymentConfig
from ..types.model_deployment_config_filter import ModelDeploymentConfigFilter
from ..types.model_deployment_config_model_spec import ModelDeploymentConfigModelSpec
from ..types.model_deployment_configs_page import ModelDeploymentConfigsPage
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawModelDeploymentConfigsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_deployment_configs(
        self,
        workspace: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort: typing.Optional[str] = None,
        filter: typing.Optional[ModelDeploymentConfigFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ModelDeploymentConfigsPage]:
        """
        List ModelDeploymentConfigs for a specific workspace.
        Returns only the latest version of each config.

        Parameters
        ----------
        workspace : str

        page : typing.Optional[int]
            Page number.

        page_size : typing.Optional[int]
            Page size.

        sort : typing.Optional[str]
            The field to sort by. To sort in decreasing order, use `-` in front of the field name.

        filter : typing.Optional[ModelDeploymentConfigFilter]
            Filter deployment configs by workspace, project, model_entity_id, name, description, created_at, and updated_at.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ModelDeploymentConfigsPage]
            Return model deployment configurations for a workspace
        """
        _response = self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployment-configs",
            method="GET",
            params={
                "page": page,
                "page_size": page_size,
                "sort": sort,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=ModelDeploymentConfigFilter, direction="write"
                ),
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDeploymentConfigsPage,
                    parse_obj_as(
                        type_=ModelDeploymentConfigsPage,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_deployment_config(
        self,
        workspace: str,
        *,
        name: str,
        engine: Engine,
        model_spec: ModelDeploymentConfigModelSpec,
        executor_config: ContainerExecutorConfig,
        project: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        model_entity_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ModelDeploymentConfig]:
        """
        Create a new ModelDeploymentConfig (version 1).

        Parameters
        ----------
        workspace : str

        name : str
            Name of the deployment configuration. Allowed characters: letters (a-z, A-Z), digits (0-9), underscores, hyphens, and dots.

        engine : Engine
            Inference engine selecting the compiler path (nim/vllm/generic)

        model_spec : ModelDeploymentConfigModelSpec
            What model to serve and how -- independent of the executor it runs on

        executor_config : ContainerExecutorConfig
            Compute + container settings for the executor the deployment runs on

        project : typing.Optional[str]
            The URN of the project associated with this deployment configuration

        description : typing.Optional[str]
            Optional description of the deployment configuration

        model_entity_id : typing.Optional[str]
            Optional reference to the base model entity ID for this deployment

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ModelDeploymentConfig]
            Create a new model deployment configuration
        """
        _response = self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployment-configs",
            method="POST",
            json={
                "name": name,
                "project": project,
                "description": description,
                "engine": engine,
                "model_spec": convert_and_respect_annotation_metadata(
                    object_=model_spec, annotation=ModelDeploymentConfigModelSpec, direction="write"
                ),
                "executor_config": convert_and_respect_annotation_metadata(
                    object_=executor_config, annotation=ContainerExecutorConfig, direction="write"
                ),
                "model_entity_id": model_entity_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDeploymentConfig,
                    parse_obj_as(
                        type_=ModelDeploymentConfig,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_deployment_config_version(
        self, workspace: str, config: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ModelDeploymentConfig]:
        """
        Get a specific version of a ModelDeploymentConfig.

        Parameters
        ----------
        workspace : str

        config : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ModelDeploymentConfig]
            Return a specific version of a model deployment configuration
        """
        _response = self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployment-configs/{encode_path_param(config)}/versions/{encode_path_param(name)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDeploymentConfig,
                    parse_obj_as(
                        type_=ModelDeploymentConfig,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_deployment_config_version(
        self, workspace: str, config: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[None]:
        """
        Delete a specific version of a ModelDeploymentConfig.

        This operation will fail with 409 Conflict if any ModelDeployments currently
        reference this specific version and are not in DELETED status. Delete or wait for
        dependent deployments to reach DELETED status before deleting the config version.

        Parameters
        ----------
        workspace : str

        config : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployment-configs/{encode_path_param(config)}/versions/{encode_path_param(name)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_latest_deployment_config(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ModelDeploymentConfig]:
        """
        Get the latest version of a ModelDeploymentConfig.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ModelDeploymentConfig]
            Return the latest version of a model deployment configuration
        """
        _response = self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployment-configs/{encode_path_param(name)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDeploymentConfig,
                    parse_obj_as(
                        type_=ModelDeploymentConfig,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_deployment_config(
        self,
        workspace: str,
        name: str,
        *,
        engine: Engine,
        model_spec: ModelDeploymentConfigModelSpec,
        executor_config: ContainerExecutorConfig,
        description: typing.Optional[str] = OMIT,
        model_entity_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ModelDeploymentConfig]:
        """
        Update a ModelDeploymentConfig (creates a new immutable version).

        Parameters
        ----------
        workspace : str

        name : str

        engine : Engine
            Inference engine selecting the compiler path (nim/vllm/generic)

        model_spec : ModelDeploymentConfigModelSpec
            What model to serve and how -- independent of the executor it runs on

        executor_config : ContainerExecutorConfig
            Compute + container settings for the executor the deployment runs on

        description : typing.Optional[str]
            Optional description of the deployment configuration

        model_entity_id : typing.Optional[str]
            Optional reference to the base model entity ID for this deployment

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ModelDeploymentConfig]
            Update a model deployment configuration (creates new version)
        """
        _response = self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployment-configs/{encode_path_param(name)}",
            method="POST",
            json={
                "description": description,
                "engine": engine,
                "model_spec": convert_and_respect_annotation_metadata(
                    object_=model_spec, annotation=ModelDeploymentConfigModelSpec, direction="write"
                ),
                "executor_config": convert_and_respect_annotation_metadata(
                    object_=executor_config, annotation=ContainerExecutorConfig, direction="write"
                ),
                "model_entity_id": model_entity_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDeploymentConfig,
                    parse_obj_as(
                        type_=ModelDeploymentConfig,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_all_deployment_config_versions(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[None]:
        """
        Delete all versions of a ModelDeploymentConfig.

        This operation will fail with 409 Conflict if any ModelDeployments currently
        reference this config and are not in DELETED status. Delete or wait for
        dependent deployments to reach DELETED status before deleting the config.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[None]
        """
        _response = self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployment-configs/{encode_path_param(name)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return HttpResponse(response=_response, data=None)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_deployment_config_versions(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.List[ModelDeploymentConfig]]:
        """
        List all versions of a ModelDeploymentConfig.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[ModelDeploymentConfig]]
            Return all versions of a model deployment configuration
        """
        _response = self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployment-configs/{encode_path_param(name)}/versions",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[ModelDeploymentConfig],
                    parse_obj_as(
                        type_=typing.List[ModelDeploymentConfig],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawModelDeploymentConfigsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_deployment_configs(
        self,
        workspace: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort: typing.Optional[str] = None,
        filter: typing.Optional[ModelDeploymentConfigFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ModelDeploymentConfigsPage]:
        """
        List ModelDeploymentConfigs for a specific workspace.
        Returns only the latest version of each config.

        Parameters
        ----------
        workspace : str

        page : typing.Optional[int]
            Page number.

        page_size : typing.Optional[int]
            Page size.

        sort : typing.Optional[str]
            The field to sort by. To sort in decreasing order, use `-` in front of the field name.

        filter : typing.Optional[ModelDeploymentConfigFilter]
            Filter deployment configs by workspace, project, model_entity_id, name, description, created_at, and updated_at.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ModelDeploymentConfigsPage]
            Return model deployment configurations for a workspace
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployment-configs",
            method="GET",
            params={
                "page": page,
                "page_size": page_size,
                "sort": sort,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=ModelDeploymentConfigFilter, direction="write"
                ),
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDeploymentConfigsPage,
                    parse_obj_as(
                        type_=ModelDeploymentConfigsPage,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_deployment_config(
        self,
        workspace: str,
        *,
        name: str,
        engine: Engine,
        model_spec: ModelDeploymentConfigModelSpec,
        executor_config: ContainerExecutorConfig,
        project: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        model_entity_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ModelDeploymentConfig]:
        """
        Create a new ModelDeploymentConfig (version 1).

        Parameters
        ----------
        workspace : str

        name : str
            Name of the deployment configuration. Allowed characters: letters (a-z, A-Z), digits (0-9), underscores, hyphens, and dots.

        engine : Engine
            Inference engine selecting the compiler path (nim/vllm/generic)

        model_spec : ModelDeploymentConfigModelSpec
            What model to serve and how -- independent of the executor it runs on

        executor_config : ContainerExecutorConfig
            Compute + container settings for the executor the deployment runs on

        project : typing.Optional[str]
            The URN of the project associated with this deployment configuration

        description : typing.Optional[str]
            Optional description of the deployment configuration

        model_entity_id : typing.Optional[str]
            Optional reference to the base model entity ID for this deployment

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ModelDeploymentConfig]
            Create a new model deployment configuration
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployment-configs",
            method="POST",
            json={
                "name": name,
                "project": project,
                "description": description,
                "engine": engine,
                "model_spec": convert_and_respect_annotation_metadata(
                    object_=model_spec, annotation=ModelDeploymentConfigModelSpec, direction="write"
                ),
                "executor_config": convert_and_respect_annotation_metadata(
                    object_=executor_config, annotation=ContainerExecutorConfig, direction="write"
                ),
                "model_entity_id": model_entity_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDeploymentConfig,
                    parse_obj_as(
                        type_=ModelDeploymentConfig,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_deployment_config_version(
        self, workspace: str, config: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ModelDeploymentConfig]:
        """
        Get a specific version of a ModelDeploymentConfig.

        Parameters
        ----------
        workspace : str

        config : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ModelDeploymentConfig]
            Return a specific version of a model deployment configuration
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployment-configs/{encode_path_param(config)}/versions/{encode_path_param(name)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDeploymentConfig,
                    parse_obj_as(
                        type_=ModelDeploymentConfig,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_deployment_config_version(
        self, workspace: str, config: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Delete a specific version of a ModelDeploymentConfig.

        This operation will fail with 409 Conflict if any ModelDeployments currently
        reference this specific version and are not in DELETED status. Delete or wait for
        dependent deployments to reach DELETED status before deleting the config version.

        Parameters
        ----------
        workspace : str

        config : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployment-configs/{encode_path_param(config)}/versions/{encode_path_param(name)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_latest_deployment_config(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ModelDeploymentConfig]:
        """
        Get the latest version of a ModelDeploymentConfig.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ModelDeploymentConfig]
            Return the latest version of a model deployment configuration
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployment-configs/{encode_path_param(name)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDeploymentConfig,
                    parse_obj_as(
                        type_=ModelDeploymentConfig,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_deployment_config(
        self,
        workspace: str,
        name: str,
        *,
        engine: Engine,
        model_spec: ModelDeploymentConfigModelSpec,
        executor_config: ContainerExecutorConfig,
        description: typing.Optional[str] = OMIT,
        model_entity_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ModelDeploymentConfig]:
        """
        Update a ModelDeploymentConfig (creates a new immutable version).

        Parameters
        ----------
        workspace : str

        name : str

        engine : Engine
            Inference engine selecting the compiler path (nim/vllm/generic)

        model_spec : ModelDeploymentConfigModelSpec
            What model to serve and how -- independent of the executor it runs on

        executor_config : ContainerExecutorConfig
            Compute + container settings for the executor the deployment runs on

        description : typing.Optional[str]
            Optional description of the deployment configuration

        model_entity_id : typing.Optional[str]
            Optional reference to the base model entity ID for this deployment

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ModelDeploymentConfig]
            Update a model deployment configuration (creates new version)
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployment-configs/{encode_path_param(name)}",
            method="POST",
            json={
                "description": description,
                "engine": engine,
                "model_spec": convert_and_respect_annotation_metadata(
                    object_=model_spec, annotation=ModelDeploymentConfigModelSpec, direction="write"
                ),
                "executor_config": convert_and_respect_annotation_metadata(
                    object_=executor_config, annotation=ContainerExecutorConfig, direction="write"
                ),
                "model_entity_id": model_entity_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDeploymentConfig,
                    parse_obj_as(
                        type_=ModelDeploymentConfig,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_all_deployment_config_versions(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[None]:
        """
        Delete all versions of a ModelDeploymentConfig.

        This operation will fail with 409 Conflict if any ModelDeployments currently
        reference this config and are not in DELETED status. Delete or wait for
        dependent deployments to reach DELETED status before deleting the config.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[None]
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployment-configs/{encode_path_param(name)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return AsyncHttpResponse(response=_response, data=None)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 409:
                raise ConflictError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_deployment_config_versions(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.List[ModelDeploymentConfig]]:
        """
        List all versions of a ModelDeploymentConfig.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[ModelDeploymentConfig]]
            Return all versions of a model deployment configuration
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployment-configs/{encode_path_param(name)}/versions",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[ModelDeploymentConfig],
                    parse_obj_as(
                        type_=typing.List[ModelDeploymentConfig],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
