# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AiDefenseRailConfig(UniversalBaseModel):
    """
    Configuration data for the Cisco AI Defense API
    """

    timeout: typing.Optional[float] = pydantic.Field(default=None)
    """
    Timeout in seconds for API requests to AI Defense service
    """

    fail_open: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If True, allow content when AI Defense API call fails (fail open). If False, block content when API call fails (fail closed). Does not affect missing configuration validation.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
