# This file was auto-generated by Fern from our API Definition.

import typing

AtifImageSourceMediaType = typing.Union[
    typing.Literal["image/jpeg", "image/png", "image/gif", "image/webp"], typing.Any
]
