# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AuthContext(UniversalBaseModel):
    """
    Auth context captured at resource creation for delegated access.

    Stores a snapshot of the creating principal's identity so that controllers
    can later act on their behalf (e.g., accessing secrets).
    """

    principal_id: str = pydantic.Field()
    """
    The principal's unique identifier
    """

    principal_email: typing.Optional[str] = pydantic.Field(default=None)
    """
    The principal's email address
    """

    principal_groups: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Groups the principal belongs to
    """

    principal_on_behalf_of: typing.Optional[str] = pydantic.Field(default=None)
    """
    If acting on behalf of another principal, their principal ID
    """

    principal_on_behalf_of_groups: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Groups the on-behalf-of principal belongs to
    """

    principal_on_behalf_of_email: typing.Optional[str] = pydantic.Field(default=None)
    """
    The on-behalf-of principal's email address
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
