# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class AutoAlignOptions(UniversalBaseModel):
    """
    List of guardrails that are activated
    """

    guardrails_config: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    The guardrails configuration that is passed to the AutoAlign endpoint
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
