# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .base_model_filter_name import BaseModelFilterName


class BaseModelFilter(UniversalBaseModel):
    """
    Filter for base model properties.
    """

    name: typing.Optional[BaseModelFilterName] = pydantic.Field(default=None)
    """
    Filter by name of the base model.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
