# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .chat_message_role import ChatMessageRole


class CapturedChatMessage(UniversalBaseModel):
    """
    A flexible message model that requires a valid role field but allows provider-specific fields.
    """

    role: ChatMessageRole = pydantic.Field()
    """
    The role of the message sender.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
