# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .chat_completion_message_tool_call_param import ChatCompletionMessageToolCallParam
from .function_call import FunctionCall


class ChatCompletionAssistantMessageParam(UniversalBaseModel):
    """
    Assistant message parameter for chat completion.
    """

    content: typing.Optional[str] = pydantic.Field(default=None)
    """
    The contents of the assistant message.
    """

    function_call: typing.Optional[FunctionCall] = pydantic.Field(default=None)
    """
    Deprecated and replaced by `tool_calls`.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    An optional name for the participant.
    """

    tool_calls: typing.Optional[typing.List[ChatCompletionMessageToolCallParam]] = pydantic.Field(default=None)
    """
    The tool calls generated by the model, such as function calls.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
