# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .multilingual_config import MultilingualConfig
from .reasoning_config import ReasoningConfig


class ContentSafetyConfig(UniversalBaseModel):
    """
    Configuration data for content safety rails.
    """

    multilingual: typing.Optional[MultilingualConfig] = None
    reasoning: typing.Optional[ReasoningConfig] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
