# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .docker_volume_mount import DockerVolumeMount


class DockerJobStorageConfig(UniversalBaseModel):
    """
    Configuration for persistent storage in Docker jobs.
    """

    volume_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the Docker volume for persistent storage
    """

    volume_permissions_image: typing.Optional[str] = pydantic.Field(default=None)
    """
    Docker image used to set permissions on the volume
    """

    additional_volume_mounts: typing.Optional[typing.List[DockerVolumeMount]] = pydantic.Field(default=None)
    """
    List of additional Docker volume mounts for the job
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
