# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .datetime_filter import DatetimeFilter
from .fileset_filter_description import FilesetFilterDescription
from .fileset_filter_name import FilesetFilterName
from .fileset_purpose import FilesetPurpose
from .storage_config_type import StorageConfigType


class FilesetFilter(UniversalBaseModel):
    """
    Filter schema for listing filesets.
    """

    name: typing.Optional[FilesetFilterName] = pydantic.Field(default=None)
    """
    Filter by fileset name.
    """

    description: typing.Optional[FilesetFilterDescription] = pydantic.Field(default=None)
    """
    Filter by fileset description.
    """

    purpose: typing.Optional[FilesetPurpose] = pydantic.Field(default=None)
    """
    Filter by the purpose of the fileset (e.g., 'dataset', 'generic').
    """

    storage_type: typing.Optional[StorageConfigType] = pydantic.Field(default=None)
    """
    Filter by the storage backend type (e.g., 'local', 'ngc').
    """

    created_at: typing.Optional[DatetimeFilter] = pydantic.Field(default=None)
    """
    Filter by creation date. Supports '$gte' (on or after) and '$lte' (on or before) datetime filters.
    """

    updated_at: typing.Optional[DatetimeFilter] = pydantic.Field(default=None)
    """
    Filter by update date. Supports '$gte' (on or after) and '$lte' (on or before) datetime filters.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
