# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .finetuning_type import FinetuningType


class FinetuningTypeFilter(UniversalBaseModel):
    """
    Filter for PEFT-related properties.
    """

    finetuning_type: typing.Optional[FinetuningType] = pydantic.Field(default=None)
    """
    Filter models with adapters with this fine-tuning type.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
