# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class FloatFilter(UniversalBaseModel):
    gte: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="$gte"),
        pydantic.Field(alias="$gte", description="Filter for results greater than or equal to this value."),
    ] = None
    lte: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="$lte"),
        pydantic.Field(alias="$lte", description="Filter for results less than or equal to this value."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
