# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class GenerationLogOptions(UniversalBaseModel):
    """
    Options for what should be included in the generation log.
    """

    activated_rails: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Include detailed information about the rails that were activated during generation.
    """

    llm_calls: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Include information about all the LLM calls that were made. This includes: prompt, completion, token usage, raw response, etc.
    """

    internal_events: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Include the array of internal generated events.
    """

    colang_history: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Include the history of the conversation in Colang format.
    """

    stats: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Include generation statistics — rail durations, LLM call counts, and token usage.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
