# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .generation_rails_options_input import GenerationRailsOptionsInput
from .generation_rails_options_output import GenerationRailsOptionsOutput
from .generation_rails_options_retrieval import GenerationRailsOptionsRetrieval


class GenerationRailsOptions(UniversalBaseModel):
    """
    Options for what rails should be used during the generation.
    """

    input: typing.Optional[GenerationRailsOptionsInput] = pydantic.Field(default=None)
    """
    Whether the input rails are enabled or not. If a list of names is specified, then only the specified input rails will be applied.
    """

    output: typing.Optional[GenerationRailsOptionsOutput] = pydantic.Field(default=None)
    """
    Whether the output rails are enabled or not. If a list of names is specified, then only the specified output rails will be applied.
    """

    retrieval: typing.Optional[GenerationRailsOptionsRetrieval] = pydantic.Field(default=None)
    """
    Whether the retrieval rails are enabled or not. If a list of names is specified, then only the specified retrieval rails will be applied.
    """

    dialog: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the dialog rails are enabled or not.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
