# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .guardrails_ai_validator_config import GuardrailsAiValidatorConfig


class GuardrailsAiRailConfig(UniversalBaseModel):
    """
    Configuration data for Guardrails AI integration.
    """

    validators: typing.Optional[typing.List[GuardrailsAiValidatorConfig]] = pydantic.Field(default=None)
    """
    List of Guardrails AI validators to apply. Each validator can have its own parameters and metadata.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
