# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .guardrails_data_output import GuardrailsDataOutput
from .rail_status import RailStatus
from .status_enum import StatusEnum


class GuardrailCheckResponse(UniversalBaseModel):
    status: StatusEnum = pydantic.Field()
    """
    Overall status indicating if all rails passed or if any failed.
    """

    rails_status: typing.Dict[str, RailStatus] = pydantic.Field()
    """
    Dictionary mapping each rail to its status.
    """

    guardrails_data: typing.Optional[GuardrailsDataOutput] = pydantic.Field(default=None)
    """
    Additional data related to guardrails.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
