# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .image_url_detail import ImageUrlDetail


class ImageUrl(UniversalBaseModel):
    """
    Image URL for vision requests.
    """

    url: str = pydantic.Field()
    """
    Either a URL of the image or the base64 encoded image data.
    """

    detail: typing.Optional[ImageUrlDetail] = pydantic.Field(default=None)
    """
    Specifies the detail level of the image.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
