# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .kubernetes_job_execution_profile_config import KubernetesJobExecutionProfileConfig


class KubernetesJobExecutionProfile(UniversalBaseModel):
    """
    Execution configuration for a Kubernetes Job.
    This is used to define the executor type, provider, profile, and any additional configuration
    required for the executor to run the job on Kubernetes
    """

    provider: typing.Optional[str] = pydantic.Field(default=None)
    """
    The compute provider for the executor, e.g., cpu, gpu
    """

    profile: typing.Optional[str] = pydantic.Field(default=None)
    """
    The profile name for the executor, e.g., high_priority_a100, low_priority, etc.
    """

    config: KubernetesJobExecutionProfileConfig = pydantic.Field()
    """
    Additional configuration for the kubernetes executor
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
