# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .compute_resources import ComputeResources
from .image_pull_secret import ImagePullSecret
from .kubernetes_job_storage_config import KubernetesJobStorageConfig
from .kubernetes_object_metadata import KubernetesObjectMetadata


class KubernetesJobExecutionProfileConfig(UniversalBaseModel):
    """
    Configuration for Kubernetes execution environment.
    """

    ttl_seconds_before_active: typing.Optional[int] = None
    ttl_seconds_active: typing.Optional[int] = None
    ttl_seconds_after_finished: typing.Optional[int] = None
    cleanup_completed_jobs_immediately: typing.Optional[bool] = None
    launcher_tool_path: typing.Optional[str] = pydantic.Field(default=None)
    """
    Path to the jobs launcher tool
    """

    env: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Optional env vars applied to all jobs (e.g. HOME=/tmp). Keys must not conflict with platform-reserved names. Job steps may override these variables.
    """

    namespace: typing.Optional[str] = pydantic.Field(default=None)
    """
    Kubernetes namespace to submit the job to. If not set, it will be determined from the environment.
    """

    service_account_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Kubernetes service account name for job pods. Uses the Kubernetes default service account when set to 'default'.
    """

    tolerations: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = pydantic.Field(default=None)
    """
    Tolerations for the Kubernetes job pods.
    """

    node_selector: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Node selector for the Kubernetes job pods.
    """

    affinity: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Affinity for the Kubernetes job pods.
    """

    resources: typing.Optional[ComputeResources] = pydantic.Field(default=None)
    """
    Resource requests and limits for the Kubernetes job pods.
    """

    pod_security_context: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Pod security context for the Kubernetes job pods.
    """

    image_pull_secrets: typing.Optional[typing.List[ImagePullSecret]] = pydantic.Field(default=None)
    """
    Image pull secrets for the Kubernetes job pods.
    """

    job_metadata: typing.Optional[KubernetesObjectMetadata] = pydantic.Field(default=None)
    """
    Metadata to add to each job object in the Kubernetes job.
    """

    pod_metadata: typing.Optional[KubernetesObjectMetadata] = pydantic.Field(default=None)
    """
    Metadata to add to each pod in the Kubernetes job.
    """

    storage: typing.Optional[KubernetesJobStorageConfig] = pydantic.Field(default=None)
    """
    Storage configuration for the Kubernetes job pods.
    """

    num_gpus: typing.Optional[int] = pydantic.Field(default=None)
    """
    Number of GPUs to request for the job
    """

    scheduler_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The scheduler name to use for the pod spec. When non-empty, this value is applied to the pod's schedulerName field, enabling custom schedulers such as KAI Scheduler. Empty string omits schedulerName so the cluster default scheduler is used.
    """

    launcher_image: typing.Optional[str] = pydantic.Field(default=None)
    """
    Container image that contains the jobs-launcher binary.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
