# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class KubernetesEmptyDirVolume(UniversalBaseModel):
    """
    Kubernetes EmptyDir Volume definition.
    """

    medium: typing.Optional[str] = pydantic.Field(default=None)
    """
    The medium of the emptyDir volume (e.g., 'Memory')
    """

    size_limit: typing.Optional[str] = pydantic.Field(default=None)
    """
    The size limit of the emptyDir volume (e.g., '1Gi')
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
