# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class KubernetesPersistentVolumeClaim(UniversalBaseModel):
    """
    Kubernetes Persistent Volume Claim definition.
    """

    claim_name: str = pydantic.Field()
    """
    Persistent Volume Claim Name
    """

    read_only: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the volume is mounted read-only
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
