# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .kubernetes_volume import KubernetesVolume
from .kubernetes_volume_mount import KubernetesVolumeMount


class KubernetesJobStorageConfig(UniversalBaseModel):
    """
    Configuration for persistent storage in Kubernetes jobs.
    """

    pvc_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Persistent Volume Claim Name to use for job storage.
    """

    volume_permissions_image: typing.Optional[str] = pydantic.Field(default=None)
    """
    Image used to set volume permissions
    """

    additional_volumes: typing.Optional[typing.List[KubernetesVolume]] = pydantic.Field(default=None)
    """
    Additional volumes to mount
    """

    additional_volume_mounts: typing.Optional[typing.List[KubernetesVolumeMount]] = pydantic.Field(default=None)
    """
    Additional volume mounts
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
