# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .cache_stats_config import CacheStatsConfig


class ModelCacheConfig(UniversalBaseModel):
    """
    Configuration for model caching.
    """

    enabled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether caching is enabled (default: False - no caching)
    """

    maxsize: typing.Optional[int] = pydantic.Field(default=None)
    """
    Maximum number of entries in the cache per model
    """

    stats: typing.Optional[CacheStatsConfig] = pydantic.Field(default=None)
    """
    Configuration for cache statistics tracking and logging
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
