# This file was auto-generated by Fern from our API Definition.

import typing

ModelProviderStatus = typing.Union[
    typing.Literal["UNKNOWN", "CREATED", "PENDING", "READY", "ERROR", "DELETING", "DELETED", "LOST"], typing.Any
]
