# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .container_executor_config import ContainerExecutorConfig
from .engine import Engine
from .model_deployment_config_model_spec import ModelDeploymentConfigModelSpec


class ModelDeploymentConfig(UniversalBaseModel):
    """
    ModelDeploymentConfig stores the configuration details for deploying a model.
    These objects are immutable with automatic versioning.

    The unique identifier is the combination of workspace/name/entity_version.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for the deployment config
    """

    name: str = pydantic.Field()
    """
    Name of the entity. Name/workspace combo must be unique across all entities. Allowed characters: letters (a-z, A-Z), digits (0-9), underscores, hyphens, and dots.
    """

    workspace: str = pydantic.Field()
    """
    The workspace of the entity. Allowed characters: letters (a-z, A-Z), digits (0-9), underscores, hyphens, and dots.
    """

    project: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URN of the project associated with this entity.
    """

    created_at: dt.datetime = pydantic.Field()
    """
    The timestamp of model entity creation
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    The timestamp of the last model entity update
    """

    entity_version: int = pydantic.Field()
    """
    Version of this deployment config. Automatically managed.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional description of the deployment configuration
    """

    engine: Engine = pydantic.Field()
    """
    Inference engine selecting the compiler path (nim/vllm/generic)
    """

    model_spec: ModelDeploymentConfigModelSpec = pydantic.Field()
    """
    What model to serve and how -- independent of the executor it runs on
    """

    executor_config: ContainerExecutorConfig = pydantic.Field()
    """
    Compute + container settings for the executor the deployment runs on
    """

    model_entity_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional reference to the base model entity ID for this deployment
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
