# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .model_type import ModelType
from .tool_call_config import ToolCallConfig


class ModelDeploymentConfigModelSpec(UniversalBaseModel):
    """
    What model to serve and how -- independent of the executor it runs on.

    Executor-invariant facts about the model. The compiler resolves the weight
    source per engine; serving fields override the model entity spec when set.
    """

    model_type: typing.Optional[ModelType] = pydantic.Field(default=None)
    """
    Type of model being deployed
    """

    model_namespace: typing.Optional[str] = pydantic.Field(default=None)
    """
    Model repository namespace - organization/user namespace as it exists in repo_id.
    """

    model_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Model name - model repository name for model weights.
    """

    model_revision: typing.Optional[str] = pydantic.Field(default=None)
    """
    Model revision (branch, tag, or commit). If not specified, parsed from model_name @revision suffix or defaults to 'main'
    """

    chat_template: typing.Optional[str] = pydantic.Field(default=None)
    """
    Jinja2 chat template string for the model. Overrides the chat_template from ModelEntity.spec if both are set. Used by the engine to format chat completions.
    """

    tool_call_config: typing.Optional[ToolCallConfig] = pydantic.Field(default=None)
    """
    Tool calling configuration for the deployment. Overrides tool_call_config from ModelEntity.spec if both are set. Controls how the model handles function/tool calling.
    """

    lora_enabled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to enable LoRA support
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
