# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .model_cache_config import ModelCacheConfig
from .model_mode import ModelMode
from .model_parameters import ModelParameters


class Model(UniversalBaseModel):
    """
    Configuration of a model used by the rails engine.

    If using Inference Gateway, the `model` field should be a Model Entity reference ('workspace/model_name').
    """

    type: str
    engine: str
    model: typing.Optional[str] = pydantic.Field(default=None)
    """
    The model name. If using Inference Gateway, this should be the Model Entity reference ('workspace/model_name').
    """

    parameters: typing.Optional[ModelParameters] = pydantic.Field(default=None)
    """
    Additional parameters to configure how to interact with the model.
    """

    mode: typing.Optional[ModelMode] = pydantic.Field(default=None)
    """
    Whether the mode is 'text' completion or 'chat' completion. Allowed values are 'chat' or 'text'.
    """

    cache: typing.Optional[ModelCacheConfig] = pydantic.Field(default=None)
    """
    Cache configuration for this specific model (primarily used for content safety models)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
