# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .model_deployment_status import ModelDeploymentStatus


class ModelDeploymentStatusHistoryItem(UniversalBaseModel):
    """
    Record of a status change in ModelDeployment history.
    """

    timestamp: dt.datetime = pydantic.Field()
    """
    When this status was recorded
    """

    status: ModelDeploymentStatus = pydantic.Field()
    """
    The status at this point in time
    """

    status_message: typing.Optional[str] = pydantic.Field(default=None)
    """
    Status message
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
