# This file was auto-generated by Fern from our API Definition.

import typing

ModelProviderSort = typing.Union[
    typing.Literal["name", "created_at", "-created_at", "updated_at", "-updated_at", "status"], typing.Any
]
