# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class MultilingualConfig(UniversalBaseModel):
    """
    Configuration for multilingual refusal messages.
    """

    enabled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If True, detect the language of user input and return refusal messages in the same language. Supported languages: en (English), es (Spanish), zh (Chinese), de (German), fr (French), hi (Hindi), ja (Japanese), ar (Arabic), th (Thai).
    """

    refusal_messages: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Custom refusal messages per language code. If not specified, built-in defaults are used. Example: {'en': 'Sorry, I cannot help.', 'es': 'Lo siento, no puedo ayudar.'}
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
