# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class NoteAnnotationInput(UniversalBaseModel):
    """
    Free-text note attached to a span or session.
    """

    span_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Id of the span this annotation applies to. Omit to annotate the whole session instead of a specific span.
    """

    session_id: str = pydantic.Field()
    """
    Id of the session this annotation belongs to. Always required.
    """

    text: str = pydantic.Field()
    """
    The note content. 1 to 10,000 characters.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
