# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class NumericFilter(UniversalBaseModel):
    """
    Range filter for numeric annotation values.

    At least one of `$gte` or `$lte` must be supplied — an empty `{}` is not a
    meaningful filter and is rejected.
    """

    gte: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="$gte"),
        pydantic.Field(alias="$gte", description="Include only values greater than or equal to this number."),
    ] = None
    lte: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="$lte"),
        pydantic.Field(alias="$lte", description="Include only values less than or equal to this number."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
