# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class OidcDiscoveryResponse(UniversalBaseModel):
    """
    OIDC discovery response for CLI/SDK.
    """

    issuer: str
    authorization_endpoint: typing.Optional[str] = None
    token_endpoint: typing.Optional[str] = None
    device_authorization_endpoint: typing.Optional[str] = None
    userinfo_endpoint: typing.Optional[str] = None
    client_id: str
    default_scopes: typing.Optional[str] = None
    scope_prefix: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
