# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .patronus_evaluate_config_output import PatronusEvaluateConfigOutput


class PatronusRailConfigOutput(UniversalBaseModel):
    """
    Configuration data for the Patronus Evaluate API
    """

    input: typing.Optional[PatronusEvaluateConfigOutput] = pydantic.Field(default=None)
    """
    Patronus Evaluate API configuration for an Input Guardrail
    """

    output: typing.Optional[PatronusEvaluateConfigOutput] = pydantic.Field(default=None)
    """
    Patronus Evaluate API configuration for an Output Guardrail
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
