# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .compute_resources import ComputeResources
from .container_spec import ContainerSpec


class PlatformJobStepSpecInputExecutor_Cpu(UniversalBaseModel):
    """
    The executor for the step
    """

    provider: typing.Literal["cpu"] = "cpu"
    profile: typing.Optional[str] = None
    container: ContainerSpec
    resources: typing.Optional[ComputeResources] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class PlatformJobStepSpecInputExecutor_Gpu(UniversalBaseModel):
    """
    The executor for the step
    """

    provider: typing.Literal["gpu"] = "gpu"
    profile: typing.Optional[str] = None
    container: ContainerSpec
    resources: typing.Optional[ComputeResources] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class PlatformJobStepSpecInputExecutor_GpuDistributed(UniversalBaseModel):
    """
    The executor for the step
    """

    provider: typing.Literal["gpu_distributed"] = "gpu_distributed"
    profile: typing.Optional[str] = None
    container: ContainerSpec
    resources: typing.Optional[ComputeResources] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


class PlatformJobStepSpecInputExecutor_Subprocess(UniversalBaseModel):
    """
    The executor for the step
    """

    provider: typing.Literal["subprocess"] = "subprocess"
    profile: typing.Optional[str] = None
    command: typing.List[str]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow


PlatformJobStepSpecInputExecutor = typing_extensions.Annotated[
    typing.Union[
        PlatformJobStepSpecInputExecutor_Cpu,
        PlatformJobStepSpecInputExecutor_Gpu,
        PlatformJobStepSpecInputExecutor_GpuDistributed,
        PlatformJobStepSpecInputExecutor_Subprocess,
    ],
    pydantic.Field(discriminator="provider"),
]
