# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .auth_context import AuthContext
from .platform_job_status import PlatformJobStatus
from .platform_job_step_spec_output import PlatformJobStepSpecOutput


class PlatformJobStepWithContext(UniversalBaseModel):
    """
    Step with additional context from parent job/attempt.
    """

    id: str
    job: str
    attempt_id: str
    fileset: str
    workspace: str
    name: str
    step_spec: typing.Optional[PlatformJobStepSpecOutput] = None
    status: typing.Optional[PlatformJobStatus] = None
    status_details: typing.Optional[typing.Dict[str, typing.Any]] = None
    error_details: typing.Optional[typing.Dict[str, typing.Any]] = None
    auth_context: typing.Optional[AuthContext] = pydantic.Field(default=None)
    """
    Auth context for task execution
    """

    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
