# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .platform_job_status import PlatformJobStatus
from .platform_job_step_status_response import PlatformJobStepStatusResponse


class PlatformJobStatusResponse(UniversalBaseModel):
    id: str
    name: str
    status: PlatformJobStatus
    status_details: typing.Dict[str, typing.Any]
    error_details: typing.Dict[str, typing.Any]
    steps: typing.List[PlatformJobStepStatusResponse]
    created_at: dt.datetime
    updated_at: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
