# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .platform_job_status import PlatformJobStatus


class PlatformJobStepsListFilter(UniversalBaseModel):
    """
    Filter options for listing platform job steps.
    """

    job: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the job to filter steps by.
    """

    status: typing.Optional[typing.List[PlatformJobStatus]] = pydantic.Field(default=None)
    """
    The list of statuses to filter steps by.
    """

    source: typing.Optional[str] = pydantic.Field(default=None)
    """
    The source of the job steps.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
