# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .platform_job_status import PlatformJobStatus


class PlatformJobStep(UniversalBaseModel):
    """
    A single step within an attempt.

    Parent-scoped: unique within (workspace, entity_type, parent=attempt_id).
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Entity name within the workspace
    """

    workspace: str = pydantic.Field()
    """
    Workspace identifier
    """

    project: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the project associated with this entity.
    """

    attempt_id: str = pydantic.Field()
    """
    Parent attempt ID
    """

    config: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Configuration for the step
    """

    status: typing.Optional[PlatformJobStatus] = pydantic.Field(default=None)
    """
    Step status
    """

    status_details: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Status details
    """

    error_details: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Error details if applicable
    """

    id: typing.Optional[str] = None
    created_at: typing.Optional[dt.datetime] = None
    created_by: typing.Optional[str] = None
    updated_at: typing.Optional[dt.datetime] = None
    updated_by: typing.Optional[str] = None
    entity_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Alias for id for backwards compatibility.
    """

    parent: typing.Optional[str] = pydantic.Field(default=None)
    """
    Parent entity ID for nested entities.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
