# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Project(UniversalBaseModel):
    """
    Schema for Project responses.
    """

    id: str = pydantic.Field()
    """
    Unique identifier
    """

    name: str = pydantic.Field()
    """
    Project name
    """

    workspace: str = pydantic.Field()
    """
    Workspace identifier
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Project description
    """

    created_at: dt.datetime = pydantic.Field()
    """
    Creation timestamp
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    Last update timestamp
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
