# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .inference_params import InferenceParams


class PromptData(UniversalBaseModel):
    """
    Configuration for prompt engineering.
    """

    system_prompt: typing.Optional[str] = pydantic.Field(default=None)
    """
    System prompt template
    """

    icl_few_shot_examples: typing.Optional[str] = pydantic.Field(default=None)
    """
    In-context learning examples
    """

    inference_params: typing.Optional[InferenceParams] = pydantic.Field(default=None)
    """
    Inference parameters that should be overridden.
    """

    system_prompt_template: typing.Optional[str] = pydantic.Field(default=None)
    """
    The template which will be used to compile the final prompt used for prompting the LLM. Currently supports only {{icl_few_shot_examples}}
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
