# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .action_rails import ActionRails
from .dialog_rails import DialogRails
from .input_rails import InputRails
from .output_rails import OutputRails
from .rails_config_data_input import RailsConfigDataInput
from .retrieval_rails import RetrievalRails
from .tool_input_rails import ToolInputRails
from .tool_output_rails import ToolOutputRails


class RailsInput(UniversalBaseModel):
    """
    Configuration of specific rails.
    """

    config: typing.Optional[RailsConfigDataInput] = pydantic.Field(default=None)
    """
    Configuration data for specific rails that are supported out-of-the-box.
    """

    input: typing.Optional[InputRails] = pydantic.Field(default=None)
    """
    Configuration of the input rails.
    """

    output: typing.Optional[OutputRails] = pydantic.Field(default=None)
    """
    Configuration of the output rails.
    """

    retrieval: typing.Optional[RetrievalRails] = pydantic.Field(default=None)
    """
    Configuration of the retrieval rails.
    """

    dialog: typing.Optional[DialogRails] = pydantic.Field(default=None)
    """
    Configuration of the dialog rails.
    """

    actions: typing.Optional[ActionRails] = pydantic.Field(default=None)
    """
    Configuration of action rails.
    """

    tool_output: typing.Optional[ToolOutputRails] = pydantic.Field(default=None)
    """
    Configuration of tool output rails.
    """

    tool_input: typing.Optional[ToolInputRails] = pydantic.Field(default=None)
    """
    Configuration of tool input rails.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
