# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .date_range_filter import DateRangeFilter
from .role_binding_filter_granted_by import RoleBindingFilterGrantedBy
from .role_binding_filter_principal import RoleBindingFilterPrincipal
from .role_binding_filter_role import RoleBindingFilterRole


class RoleBindingFilter(UniversalBaseModel):
    """
    Filter for role bindings.
    """

    principal: typing.Optional[RoleBindingFilterPrincipal] = pydantic.Field(default=None)
    """
    Filter by principal ID
    """

    workspace: typing.Optional[str] = pydantic.Field(default=None)
    """
    Filter by workspace
    """

    role: typing.Optional[RoleBindingFilterRole] = pydantic.Field(default=None)
    """
    Filter by role
    """

    granted_by: typing.Optional[RoleBindingFilterGrantedBy] = pydantic.Field(default=None)
    """
    Filter by who granted the role
    """

    is_active: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Filter for active (True) or revoked (False) bindings
    """

    granted_at: typing.Optional[DateRangeFilter] = pydantic.Field(default=None)
    """
    Filter by granted date range
    """

    revoked_at: typing.Optional[DateRangeFilter] = pydantic.Field(default=None)
    """
    Filter by revoked date range
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
