# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .sensitive_data_detection_options import SensitiveDataDetectionOptions


class SensitiveDataDetection(UniversalBaseModel):
    """
    Configuration of what sensitive data should be detected.
    """

    recognizers: typing.Optional[typing.List[typing.Dict[str, typing.Any]]] = pydantic.Field(default=None)
    """
    Additional custom recognizers. Check out https://microsoft.github.io/presidio/tutorial/08_no_code/ for more details.
    """

    input: typing.Optional[SensitiveDataDetectionOptions] = pydantic.Field(default=None)
    """
    Configuration of the entities to be detected on the user input.
    """

    output: typing.Optional[SensitiveDataDetectionOptions] = pydantic.Field(default=None)
    """
    Configuration of the entities to be detected on the bot output.
    """

    retrieval: typing.Optional[SensitiveDataDetectionOptions] = pydantic.Field(default=None)
    """
    Configuration of the entities to be detected on retrieved relevant chunks.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
