# This file was auto-generated by Fern from our API Definition.

import typing

SpanKind = typing.Union[
    typing.Literal[
        "LLM", "CHAIN", "TOOL", "RETRIEVER", "EMBEDDING", "AGENT", "RERANKER", "EVALUATOR", "GUARDRAIL", "UNKNOWN"
    ],
    typing.Any,
]
