# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class SubprocessJobExecutionProfileConfig(UniversalBaseModel):
    ttl_seconds_before_active: typing.Optional[int] = None
    ttl_seconds_active: typing.Optional[int] = None
    ttl_seconds_after_finished: typing.Optional[int] = None
    cleanup_completed_jobs_immediately: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Keep subprocess working directories by default so runs remain inspectable.
    """

    launcher_tool_path: typing.Optional[str] = pydantic.Field(default=None)
    """
    Path to the jobs launcher tool
    """

    env: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Optional env vars applied to all jobs (e.g. HOME=/tmp). Keys must not conflict with platform-reserved names. Job steps may override these variables.
    """

    working_directory: typing.Optional[str] = pydantic.Field(default=None)
    """
    Root directory for subprocess job state, config, storage, and logs.
    """

    graceful_shutdown_timeout_seconds: typing.Optional[int] = pydantic.Field(default=None)
    """
    How long to wait after SIGTERM before force killing the process group.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
