# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .task_prompt_messages_item import TaskPromptMessagesItem


class TaskPrompt(UniversalBaseModel):
    """
    Configuration for prompts that will be used for a specific task.
    """

    task: str = pydantic.Field()
    """
    The id of the task associated with this prompt.
    """

    content: typing.Optional[str] = pydantic.Field(default=None)
    """
    The content of the prompt, if it's a string.
    """

    messages: typing.Optional[typing.List[TaskPromptMessagesItem]] = pydantic.Field(default=None)
    """
    The list of messages included in the prompt. Used for chat models.
    """

    models: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    If specified, the prompt will be used only for the given LLM engines/models. The format is a list of strings with the format: <engine> or <engine>/<model>.
    """

    output_parser: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the output parser to use for this prompt.
    """

    max_length: typing.Optional[int] = pydantic.Field(default=None)
    """
    The maximum length of the prompt in number of characters.
    """

    mode: typing.Optional[str] = pydantic.Field(default=None)
    """
    Corresponds to the `prompting_mode` for which this prompt is fetched. Default is 'standard'.
    """

    stop: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    If specified, will be configure stop tokens for models that support this.
    """

    max_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    The maximum number of tokens that can be generated in the chat completion.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
