# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ToolCallingMetadataContent(UniversalBaseModel):
    """
    Content for tool-calling configuration on model filesets.

    Stores chat template and tool calling settings that are merged into
    the ModelSpec during checkpoint analysis.
    """

    chat_template: typing.Optional[str] = pydantic.Field(default=None)
    """
    Jinja2 chat template for the model.
    """

    tool_call_parser: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the tool call parser (e.g., 'openai', 'hermes', 'pythonic', 'llama3_json', 'mistral').
    """

    tool_call_plugin: typing.Optional[str] = pydantic.Field(default=None)
    """
    Reference to a fileset containing a custom tool call plugin Python file. Expected format: '{workspace}/{fileset_name}'.
    """

    auto_tool_choice: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether to enable automatic tool choice.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
