# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class TrendMicroRailConfig(UniversalBaseModel):
    """
    Configuration data for the Trend Micro AI Guard API
    """

    v1url: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="v1_url"),
        pydantic.Field(
            alias="v1_url",
            description="The endpoint for the Trend Micro AI Guard API. For other regions, use: https://api.{region}.xdr.trendmicro.com/v3.0/aiSecurity/applyGuardrails where region is eu, jp, au, in, sg, or mea.",
        ),
    ] = None
    api_key_env_var: typing.Optional[str] = pydantic.Field(default=None)
    """
    Environment variable containing API key for Trend Micro AI Guard
    """

    application_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Application name for TMV1-Application-Name header (REQUIRED). Must contain only letters, numbers, hyphens, and underscores, with a maximum length of 64 characters.
    """

    detailed_response: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If True, returns detailed AI Guard results with confidence scores (Prefer: return=representation). If False, returns minimal response with only action and reasons (Prefer: return=minimal).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
