# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .middleware_call import MiddlewareCall
from .virtual_model_inference_config import VirtualModelInferenceConfig


class VirtualModel(UniversalBaseModel):
    """
    Logical inference route.

    Maps a user-facing model name to an optional default model entity and
    defines ordered middleware pipelines for the request, response, and
    post-response phases.

    When a caller sets ``model: "workspace/my-virtual-model"`` in an inference
    request, IGW resolves the ``VirtualModel`` instead of a ``ModelEntity``
    directly. If ``default_model_entity`` is set, IGW writes it into
    ``request["model"]`` before the request middleware pipeline runs. Middleware
    may mutate ``request["model"]`` freely. After the pipeline completes, IGW
    reads ``request["model"]``, resolves it to a ``ModelProvider`` via the
    ``ModelCache``, and proxies.

    The ``ModelProviderReconciler`` auto-creates a passthrough ``VirtualModel``
    for each discovered model (same workspace and name as the ``ModelEntity``,
    empty middleware lists, ``default_model_entity`` pointing to that entity).
    All existing inference requests continue to work without changes.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Entity name within the workspace
    """

    workspace: str = pydantic.Field()
    """
    Workspace identifier
    """

    project: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the project associated with this entity.
    """

    default_model_entity: typing.Optional[str] = None
    autoprovisioned: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Marks this VirtualModel as controller-managed. The Models controller will delete it once no ModelProvider serves the matching entity. Setting this manually opts the VirtualModel into that cleanup behavior.
    """

    models: typing.Optional[typing.List[VirtualModelInferenceConfig]] = None
    request_middleware: typing.Optional[typing.List[MiddlewareCall]] = None
    response_middleware: typing.Optional[typing.List[MiddlewareCall]] = None
    post_response_middleware: typing.Optional[typing.List[MiddlewareCall]] = None
    override_proxy: typing.Optional[str] = None
    id: typing.Optional[str] = None
    created_at: typing.Optional[dt.datetime] = None
    created_by: typing.Optional[str] = None
    updated_at: typing.Optional[dt.datetime] = None
    updated_by: typing.Optional[str] = None
    entity_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Alias for id for backwards compatibility.
    """

    parent: typing.Optional[str] = pydantic.Field(default=None)
    """
    Parent entity ID for nested entities.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
