# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Workspace(UniversalBaseModel):
    """
    Workspace schema for API responses.
    """

    id: str = pydantic.Field()
    """
    System-generated UUID
    """

    name: str = pydantic.Field()
    """
    Workspace name (user-provided)
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional description
    """

    created_at: dt.datetime = pydantic.Field()
    """
    Timestamp of workspace creation
    """

    created_by: typing.Optional[str] = pydantic.Field(default=None)
    """
    Principal id for workspace creator
    """

    updated_at: dt.datetime = pydantic.Field()
    """
    Timestamp of last workspace update
    """

    updated_by: typing.Optional[str] = pydantic.Field(default=None)
    """
    Principal id for last workspace update
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
