# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Test GCP Kyverno policy for multi-node GPU training with TCP-X

multinodeNetworking:
  gcp:
    enabled: true
