// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import { generateDefaultName } from '@nemo/common/src/utils/generateDefaultName';
import {
  entitiesCreateEntity,
  entitiesDeleteEntityByName,
  entitiesGetEntityByName,
  entitiesListEntities,
  entitiesUpdateEntityByName,
} from '@nemo/sdk/generated/platform/entity-store';
import type { EntitiesListEntitiesParams } from '@nemo/sdk/generated/platform/schema';
import {
  CUSTOMIZATION_JOB_TEMPLATE_ENTITY_TYPE,
  type CustomizationJobTemplateData,
  type CustomizationJobTemplateDataInput,
  type CustomizationJobTemplateEntity,
  type CustomizationJobTemplatesPage,
} from '@studio/api/customization-job-templates/types';
import type { CustomizationBackend } from '@studio/util/customizationBackend';
import { coerceToFormFields, type CustomizationFormFields } from '@studio/util/forms/customization';

// ---------------------------------------------------------------------------
// Query keys
// ---------------------------------------------------------------------------

/** Query key for a (optionally filtered/paginated) list of job templates. */
export const getCustomizationJobTemplatesQueryKey = (
  workspace: string,
  params?: EntitiesListEntitiesParams
) => ['customization-job-templates', workspace, ...(params ? [params] : [])] as const;

/** Query key for a single job template. */
export const getCustomizationJobTemplateQueryKey = (workspace: string, name: string) =>
  ['customization-job-template', workspace, name] as const;

/**
 * Build the entity-store `filter` expression that scopes a list to one backend.
 * The entity-store supports `data.<key>` paths in JSON filters, so this narrows
 * server-side rather than in the browser.
 */
export const customizationJobTemplatesForBackendFilter = (backend: CustomizationBackend): string =>
  JSON.stringify({ 'data.backend': backend });

// ---------------------------------------------------------------------------
// CRUD (thin wrappers over the generic entity-store endpoints)
// ---------------------------------------------------------------------------

/** List job templates in a workspace, optionally filtered and paginated. */
export async function listCustomizationJobTemplates(
  workspace: string,
  params?: EntitiesListEntitiesParams,
  signal?: AbortSignal
): Promise<CustomizationJobTemplatesPage> {
  const page = await entitiesListEntities(
    workspace,
    CUSTOMIZATION_JOB_TEMPLATE_ENTITY_TYPE,
    params,
    signal
  );
  return { ...page, data: page.data as CustomizationJobTemplateEntity[] };
}

/** List only the templates targeting a single customization backend. */
export function listCustomizationJobTemplatesForBackend(
  workspace: string,
  backend: CustomizationBackend,
  params?: Omit<EntitiesListEntitiesParams, 'filter'>,
  signal?: AbortSignal
): Promise<CustomizationJobTemplatesPage> {
  return listCustomizationJobTemplates(
    workspace,
    { ...params, filter: customizationJobTemplatesForBackendFilter(backend) },
    signal
  );
}

/**
 * Fetch a single job template by name. Templates are top-level entities (no `parent`),
 * so the name is unique within the workspace and no scoping param is needed.
 */
export async function getCustomizationJobTemplate(
  workspace: string,
  name: string,
  signal?: AbortSignal
): Promise<CustomizationJobTemplateEntity> {
  const entity = await entitiesGetEntityByName(
    workspace,
    CUSTOMIZATION_JOB_TEMPLATE_ENTITY_TYPE,
    name,
    undefined,
    signal
  );
  return entity as CustomizationJobTemplateEntity;
}

export interface CreateCustomizationJobTemplateInput {
  /** Optional name — auto-generated by the entity-store if omitted. */
  name?: string;
  project?: string;
  data: CustomizationJobTemplateDataInput;
}

/** Create a job template. `data.backend` is derived from the captured form fields. */
export async function createCustomizationJobTemplate(
  workspace: string,
  input: CreateCustomizationJobTemplateInput
): Promise<CustomizationJobTemplateEntity> {
  const data: CustomizationJobTemplateData = {
    ...input.data,
    backend: input.data.backend ?? input.data.fields.backend,
  };
  const entity = await entitiesCreateEntity(workspace, CUSTOMIZATION_JOB_TEMPLATE_ENTITY_TYPE, {
    name: input.name,
    project: input.project,
    data,
  });
  return entity as CustomizationJobTemplateEntity;
}

export interface UpdateCustomizationJobTemplatePatch {
  new_name?: string;
  project?: string;
  data: CustomizationJobTemplateData;
  /** Optimistic-lock token; update fails on mismatch. */
  expected_db_version?: number;
}

/** Update a job template by name. */
export async function updateCustomizationJobTemplate(
  workspace: string,
  name: string,
  patch: UpdateCustomizationJobTemplatePatch
): Promise<CustomizationJobTemplateEntity> {
  const entity = await entitiesUpdateEntityByName(
    workspace,
    CUSTOMIZATION_JOB_TEMPLATE_ENTITY_TYPE,
    name,
    {
      new_name: patch.new_name,
      project: patch.project,
      data: patch.data,
      expected_db_version: patch.expected_db_version,
    }
  );
  return entity as CustomizationJobTemplateEntity;
}

/** Delete a job template by name. */
export async function deleteCustomizationJobTemplate(
  workspace: string,
  name: string
): Promise<void> {
  await entitiesDeleteEntityByName(workspace, CUSTOMIZATION_JOB_TEMPLATE_ENTITY_TYPE, name);
}

// ---------------------------------------------------------------------------
// Form <-> template mapping
// ---------------------------------------------------------------------------

/** Capture the current form state as a template payload. */
export function formFieldsToTemplateData(
  fields: CustomizationFormFields,
  description?: string
): CustomizationJobTemplateDataInput {
  return { description, backend: fields.backend, fields };
}

/**
 * Turn a stored template back into form state for `NewCustomizationForm`'s `initialValues`.
 *
 * Delegates the defaults-merge to `coerceToFormFields`, which tolerates a template written
 * by an older Studio build that is missing whole sections. Returns `undefined` when the
 * payload is unusable (e.g. an unknown `backend`).
 *
 * `outputName` is always regenerated rather than restored, so applying one template twice
 * doesn't try to produce two output models with the same name.
 */
export function templateToFormFields(
  template: CustomizationJobTemplateEntity
): CustomizationFormFields | undefined {
  const fields = coerceToFormFields(template.data?.fields);
  return fields ? { ...fields, outputName: generateDefaultName() } : undefined;
}
