apiVersion: v2
name: nemo-platform
maintainers:
  - name: NVIDIA, Inc.
    url: https://www.nvidia.com
description: NeMo Platform Helm Chart
type: application
# version is the version of the Helm chart, and can be different from the appVersion.
version: 0.1.0
# appVersion is the version of the application deployed in the chart.
appVersion: "0.3.0"
home: https://nvidia.com
