# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Authentication and authorization utilities for NeMo Platform."""

from nmp.common.config import AuthConfig

from .access_keys import (
    ACCESS_KEY_JWKS_PATH,
    ACCESS_KEY_TOKEN_TYPE,
    AccessKeyIssuerService,
    validate_access_key_token,
)
from .client import AuthClient, AuthorizationResult
from .dependencies import (
    auth_as_service,
    auth_client_context,
    build_service_principal_headers,
    get_auth_client,
    get_principal_auth_headers,
)
from .exceptions import AuthorizationError, InvalidPermissionFormatError, InvalidScopeFormatError
from .middleware import AuthorizationMiddleware
from .models import NMP_PRINCIPAL_ENVVAR, AuthContext, Principal
from .permissions import ALL_WORKSPACES, compute_accessible_workspaces
from .tasks import principal_from_env
from .workload_delegations import (
    DOCKER_OPAQUE_WORKLOAD_PROOF_TOKEN_TYPE,
    JWT_WORKLOAD_SUBJECT_TOKEN_TYPE,
    KUBERNETES_POD_UID_REFERENCE_NAME,
    OPAQUE_DOCKER_PROOF_PREFIX,
    WORKLOAD_DELEGATION_ENTITY_TYPE,
    InvalidWorkloadProofTokenError,
    ParsedOpaqueDockerProofToken,
    SyncWorkloadDelegationStore,
    WorkloadDelegationConflictError,
    WorkloadDelegationEntity,
    WorkloadDelegationError,
    WorkloadDelegationLookupScope,
    WorkloadDelegationScope,
    WorkloadDelegationStore,
    WorkloadDelegationValidationError,
    as_aware_utc,
    create_opaque_docker_proof_token,
    docker_delegation_name,
    docker_deployment_delegation_name,
    docker_workload_delegation_name,
    kubernetes_pod_uid_delegation_name,
    parse_opaque_docker_proof_token,
    reference_delegation_name,
    subject_token_type_for_exchange,
    verify_opaque_docker_proof_token_hash,
)
from .workload_identity import (
    DEFAULT_WORKLOAD_AUDIENCE,
    WORKLOAD_DELEGATION_TTL_BUFFER_SECONDS,
    WORKLOAD_IDENTITY_TOKEN_FILE_ENVVAR,
    WORKLOAD_IDENTITY_TOKEN_FILE_PATH,
    WORKLOAD_IDENTITY_VOLUME_NAME,
    WORKLOAD_IDENTITY_VOLUME_PATH,
    WorkloadIdentityConfigError,
    build_docker_opaque_workload_delegation,
    build_kubernetes_pod_uid_workload_delegation,
    build_token_archive,
    get_workload_delegation_audience,
    get_workload_identity_token_audience,
    is_workload_identity_token_exchange_enabled,
    kubernetes_service_account_subject,
    workload_delegation_expires_at,
    workload_identity_env,
)

# Testing utilities are NOT exported here to avoid importing dev dependencies (respx)
# at runtime. Import directly from nmp.common.auth.testing when needed in tests.

__all__ = [
    "ALL_WORKSPACES",
    "AuthClient",
    "AuthContext",
    "AuthConfig",
    "AuthorizationError",
    "InvalidPermissionFormatError",
    "InvalidScopeFormatError",
    "AuthorizationMiddleware",
    "AuthorizationResult",
    "ACCESS_KEY_JWKS_PATH",
    "ACCESS_KEY_TOKEN_TYPE",
    "AccessKeyIssuerService",
    "DOCKER_OPAQUE_WORKLOAD_PROOF_TOKEN_TYPE",
    "JWT_WORKLOAD_SUBJECT_TOKEN_TYPE",
    "KUBERNETES_POD_UID_REFERENCE_NAME",
    "OPAQUE_DOCKER_PROOF_PREFIX",
    "WORKLOAD_DELEGATION_ENTITY_TYPE",
    "WORKLOAD_IDENTITY_VOLUME_PATH",
    "WORKLOAD_IDENTITY_VOLUME_NAME",
    "WORKLOAD_IDENTITY_TOKEN_FILE_PATH",
    "WORKLOAD_IDENTITY_TOKEN_FILE_ENVVAR",
    "WORKLOAD_DELEGATION_TTL_BUFFER_SECONDS",
    "DEFAULT_WORKLOAD_AUDIENCE",
    "InvalidWorkloadProofTokenError",
    "NMP_PRINCIPAL_ENVVAR",
    "ParsedOpaqueDockerProofToken",
    "Principal",
    "SyncWorkloadDelegationStore",
    "WorkloadDelegationConflictError",
    "WorkloadDelegationEntity",
    "WorkloadDelegationError",
    "WorkloadDelegationLookupScope",
    "WorkloadDelegationScope",
    "WorkloadDelegationStore",
    "WorkloadDelegationValidationError",
    "WorkloadIdentityConfigError",
    "as_aware_utc",
    "auth_as_service",
    "auth_client_context",
    "build_service_principal_headers",
    "create_opaque_docker_proof_token",
    "workload_identity_env",
    "workload_delegation_expires_at",
    "kubernetes_service_account_subject",
    "kubernetes_pod_uid_delegation_name",
    "is_workload_identity_token_exchange_enabled",
    "get_workload_identity_token_audience",
    "get_workload_delegation_audience",
    "docker_workload_delegation_name",
    "docker_deployment_delegation_name",
    "build_token_archive",
    "build_kubernetes_pod_uid_workload_delegation",
    "build_docker_opaque_workload_delegation",
    "docker_delegation_name",
    "principal_from_env",
    "parse_opaque_docker_proof_token",
    "reference_delegation_name",
    "subject_token_type_for_exchange",
    "compute_accessible_workspaces",
    "get_auth_client",
    "get_principal_auth_headers",
    "validate_access_key_token",
    "verify_opaque_docker_proof_token_hash",
]
