# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.annotation import Annotation
from ..types.annotation_filter import AnnotationFilter
from ..types.annotation_input import AnnotationInput
from ..types.annotation_sort_field import AnnotationSortField
from ..types.annotations_page import AnnotationsPage
from .raw_client import AsyncRawAnnotationsClient, RawAnnotationsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AnnotationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAnnotationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAnnotationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAnnotationsClient
        """
        return self._raw_client

    def list_annotations(
        self,
        workspace: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort: typing.Optional[AnnotationSortField] = None,
        filter: typing.Optional[AnnotationFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AnnotationsPage:
        """
        Parameters
        ----------
        workspace : str

        page : typing.Optional[int]
            Page number.

        page_size : typing.Optional[int]
            Page size.

        sort : typing.Optional[AnnotationSortField]

        filter : typing.Optional[AnnotationFilter]
            Filter annotations by span_id, session_id, kind, name, created_by, and created_at range.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AnnotationsPage
            Successful Response

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.annotations.list_annotations(
            workspace="workspace",
        )
        """
        _response = self._raw_client.list_annotations(
            workspace, page=page, page_size=page_size, sort=sort, filter=filter, request_options=request_options
        )
        return _response.data

    def create_annotation(
        self, workspace: str, *, request: AnnotationInput, request_options: typing.Optional[RequestOptions] = None
    ) -> Annotation:
        """
        Parameters
        ----------
        workspace : str

        request : AnnotationInput

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Annotation
            Successful Response

        Examples
        --------
        from nvidia import AnnotationInput_Feedback, NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.annotations.create_annotation(
            workspace="workspace",
            request=AnnotationInput_Feedback(
                session_id="session_id",
                value="positive",
            ),
        )
        """
        _response = self._raw_client.create_annotation(workspace, request=request, request_options=request_options)
        return _response.data

    def get_annotation(
        self, workspace: str, annotation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Annotation:
        """
        Parameters
        ----------
        workspace : str

        annotation_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Annotation
            Successful Response

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.annotations.get_annotation(
            workspace="workspace",
            annotation_id="annotation_id",
        )
        """
        _response = self._raw_client.get_annotation(workspace, annotation_id, request_options=request_options)
        return _response.data

    def delete_annotation(
        self, workspace: str, annotation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        workspace : str

        annotation_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.annotations.delete_annotation(
            workspace="workspace",
            annotation_id="annotation_id",
        )
        """
        _response = self._raw_client.delete_annotation(workspace, annotation_id, request_options=request_options)
        return _response.data


class AsyncAnnotationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAnnotationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAnnotationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAnnotationsClient
        """
        return self._raw_client

    async def list_annotations(
        self,
        workspace: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort: typing.Optional[AnnotationSortField] = None,
        filter: typing.Optional[AnnotationFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AnnotationsPage:
        """
        Parameters
        ----------
        workspace : str

        page : typing.Optional[int]
            Page number.

        page_size : typing.Optional[int]
            Page size.

        sort : typing.Optional[AnnotationSortField]

        filter : typing.Optional[AnnotationFilter]
            Filter annotations by span_id, session_id, kind, name, created_by, and created_at range.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AnnotationsPage
            Successful Response

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.annotations.list_annotations(
                workspace="workspace",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_annotations(
            workspace, page=page, page_size=page_size, sort=sort, filter=filter, request_options=request_options
        )
        return _response.data

    async def create_annotation(
        self, workspace: str, *, request: AnnotationInput, request_options: typing.Optional[RequestOptions] = None
    ) -> Annotation:
        """
        Parameters
        ----------
        workspace : str

        request : AnnotationInput

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Annotation
            Successful Response

        Examples
        --------
        import asyncio

        from nvidia import AnnotationInput_Feedback, AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.annotations.create_annotation(
                workspace="workspace",
                request=AnnotationInput_Feedback(
                    session_id="session_id",
                    value="positive",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_annotation(
            workspace, request=request, request_options=request_options
        )
        return _response.data

    async def get_annotation(
        self, workspace: str, annotation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Annotation:
        """
        Parameters
        ----------
        workspace : str

        annotation_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Annotation
            Successful Response

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.annotations.get_annotation(
                workspace="workspace",
                annotation_id="annotation_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_annotation(workspace, annotation_id, request_options=request_options)
        return _response.data

    async def delete_annotation(
        self, workspace: str, annotation_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Parameters
        ----------
        workspace : str

        annotation_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.annotations.delete_annotation(
                workspace="workspace",
                annotation_id="annotation_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_annotation(workspace, annotation_id, request_options=request_options)
        return _response.data
