// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import {
  Button,
  Flex,
  FormField,
  Stack,
  Switch,
  Tag,
  Text,
  TextArea,
  TextInput,
} from '@nvidia/foundations-react-core';
import type { RailScope } from '@studio/routes/guardrails/rails/types';
import { Plus, X } from 'lucide-react';
import { type FC, useRef, useState } from 'react';

/**
 * One stage of an LLM-judged rail: whether it runs, and the prompt that decides the
 * verdict. Shared by every such rail — self check, content safety, topic control — so the
 * stage explanations stay identical wherever they appear.
 */

const SCOPE_TITLES: Record<RailScope, string> = {
  input: 'Input Prompt',
  output: 'Output Prompt',
  retrieval: 'Retrieval Prompt',
};

const SCOPE_DESCRIPTIONS: Record<RailScope, string> = {
  input:
    'Applied to the user input. An input rail can reject the input, stopping any additional processing, or alter the input—such as masking potentially sensitive data—to rephrase.',
  output:
    'Applied to the output generated by the LLM. An output rail can reject the output, preventing it from being returned to the user, or alter it, such as removing sensitive data.',
  retrieval:
    'Applied to chunks retrieved from the knowledge base. A retrieval rail can reject or alter a chunk before it reaches the LLM.',
};

export interface PromptScopeSectionProps {
  scope: RailScope;
  enabled: boolean;
  onEnabledChange: (enabled: boolean) => void;
  prompt: string;
  onPromptChange: (prompt: string) => void;
  /** Template variables this stage can reference, e.g. `{{ user_input }}`. */
  variables: readonly string[];
  /** Caps the check's response length. Library default (1024) applies when unset. */
  maxTokens: number | undefined;
  onMaxTokensChange: (maxTokens: number | undefined) => void;
  /** Caps the prompt length in characters before it's sent. Library default (16000)
   * applies when unset. */
  maxLength: number | undefined;
  onMaxLengthChange: (maxLength: number | undefined) => void;
  /** Sequences that stop generation early when the model produces one. */
  stop: readonly string[];
  onStopChange: (stop: string[]) => void;
}

export const PromptScopeSection: FC<PromptScopeSectionProps> = ({
  scope,
  enabled,
  onEnabledChange,
  prompt,
  onPromptChange,
  variables,
  maxTokens,
  onMaxTokensChange,
  maxLength,
  onMaxLengthChange,
  stop,
  onStopChange,
}) => {
  const promptRef = useRef<HTMLTextAreaElement>(null);
  const [stopDraft, setStopDraft] = useState('');
  const title = SCOPE_TITLES[scope];

  const addStop = () => {
    const value = stopDraft.trim();
    if (!value || stop.includes(value)) return;
    onStopChange([...stop, value]);
    setStopDraft('');
  };

  /**
   * Insert at the caret rather than appending: a variable almost always belongs mid-
   * sentence, and the caret is where the user was last typing.
   */
  const insertVariable = (variable: string) => {
    const textarea = promptRef.current;
    if (!textarea) {
      onPromptChange(`${prompt}${variable}`);
      return;
    }
    const start = textarea.selectionStart ?? prompt.length;
    const end = textarea.selectionEnd ?? prompt.length;
    onPromptChange(`${prompt.slice(0, start)}${variable}${prompt.slice(end)}`);
    // Restore focus and drop the caret after what we inserted, so typing continues there.
    requestAnimationFrame(() => {
      textarea.focus();
      const caret = start + variable.length;
      textarea.setSelectionRange(caret, caret);
    });
  };

  return (
    <Stack gap="density-md">
      <Flex align="center" justify="between" gap="density-md">
        <Text kind="label/bold/lg">{title}</Text>
        <Flex align="center" gap="density-sm">
          <Text kind="body/regular/sm" className="text-text-secondary">
            Enabled
          </Text>
          <Switch
            checked={enabled}
            onCheckedChange={onEnabledChange}
            attributes={{ SwitchInput: { 'aria-label': `${title} enabled` } }}
          />
        </Flex>
      </Flex>

      <Text kind="body/regular/sm" className="text-text-secondary">
        {SCOPE_DESCRIPTIONS[scope]}
      </Text>

      <FormField slotLabel="Prompt">
        <TextArea
          ref={promptRef}
          resizeable="auto"
          className="w-full"
          value={prompt}
          onChange={(event) => onPromptChange(event.currentTarget.value)}
          aria-label={`${title} template`}
        />
      </FormField>

      {variables.length ? (
        <Stack gap="density-xs">
          <Text kind="label/bold/sm">Variables</Text>
          <Flex gap="density-sm" wrap="wrap">
            {variables.map((variable) => (
              <Button
                key={variable}
                kind="secondary"
                color="neutral"
                onClick={() => insertVariable(variable)}
                aria-label={`Insert ${variable} into ${title.toLowerCase()}`}
              >
                <Plus size={14} />
                {variable}
              </Button>
            ))}
          </Flex>
        </Stack>
      ) : null}

      <Flex gap="density-md" wrap="wrap">
        <FormField
          slotLabel={`${title} Max Tokens`}
          slotHelp="Caps the length of the check's response. Defaults to 1024 when unset."
          className="min-w-[160px] flex-1"
        >
          <TextInput
            type="number"
            min={1}
            value={maxTokens === undefined ? '' : String(maxTokens)}
            onValueChange={(value) => onMaxTokensChange(value === '' ? undefined : Number(value))}
          />
        </FormField>

        <FormField
          slotLabel={`${title} Max Prompt Length`}
          slotHelp="Caps the prompt length in characters. Defaults to 16000 when unset."
          className="min-w-[160px] flex-1"
        >
          <TextInput
            type="number"
            min={1}
            value={maxLength === undefined ? '' : String(maxLength)}
            onValueChange={(value) => onMaxLengthChange(value === '' ? undefined : Number(value))}
          />
        </FormField>
      </Flex>

      <FormField
        slotLabel={`${title} Stop Sequences`}
        slotHelp="Generation stops early if the model produces one of these."
      >
        <Stack gap="density-sm">
          {stop.length ? (
            <Flex gap="density-sm" wrap="wrap">
              {stop.map((token) => (
                <Tag
                  key={token}
                  color="gray"
                  onClick={() => onStopChange(stop.filter((existing) => existing !== token))}
                  aria-label={`Remove stop sequence ${token}`}
                >
                  {token}
                  <X size={12} />
                </Tag>
              ))}
            </Flex>
          ) : null}
          <TextInput
            value={stopDraft}
            onValueChange={setStopDraft}
            onKeyDown={(event) => {
              if (event.key === 'Enter') {
                event.preventDefault();
                addStop();
              }
            }}
            placeholder="Add a stop sequence and press Enter"
          />
        </Stack>
      </FormField>
    </Stack>
  );
};
