// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import {
  Button,
  Flex,
  FormField,
  Stack,
  Switch,
  Text,
  TextArea,
} from '@nvidia/foundations-react-core';
import type { RailScope } from '@studio/routes/guardrails/rails/types';
import { Plus } from 'lucide-react';
import { type FC, useRef } from 'react';

/**
 * One stage of an LLM-judged rail: whether it runs, and the prompt that decides the
 * verdict. Shared by every such rail — self check, content safety, topic control — so the
 * stage explanations stay identical wherever they appear.
 */

const SCOPE_TITLES: Record<RailScope, string> = {
  input: 'Input Prompt',
  output: 'Output Prompt',
  retrieval: 'Retrieval Prompt',
};

const SCOPE_DESCRIPTIONS: Record<RailScope, string> = {
  input:
    'Applied to the user input. An input rail can reject the input, stopping any additional processing, or alter the input—such as masking potentially sensitive data—to rephrase.',
  output:
    'Applied to the output generated by the LLM. An output rail can reject the output, preventing it from being returned to the user, or alter it, such as removing sensitive data.',
  retrieval:
    'Applied to chunks retrieved from the knowledge base. A retrieval rail can reject or alter a chunk before it reaches the LLM.',
};

export interface PromptScopeSectionProps {
  scope: RailScope;
  enabled: boolean;
  onEnabledChange: (enabled: boolean) => void;
  prompt: string;
  onPromptChange: (prompt: string) => void;
  /** Template variables this stage can reference, e.g. `{{ user_input }}`. */
  variables: readonly string[];
}

export const PromptScopeSection: FC<PromptScopeSectionProps> = ({
  scope,
  enabled,
  onEnabledChange,
  prompt,
  onPromptChange,
  variables,
}) => {
  const promptRef = useRef<HTMLTextAreaElement>(null);
  const title = SCOPE_TITLES[scope];

  /**
   * Insert at the caret rather than appending: a variable almost always belongs mid-
   * sentence, and the caret is where the user was last typing.
   */
  const insertVariable = (variable: string) => {
    const textarea = promptRef.current;
    if (!textarea) {
      onPromptChange(`${prompt}${variable}`);
      return;
    }
    const start = textarea.selectionStart ?? prompt.length;
    const end = textarea.selectionEnd ?? prompt.length;
    onPromptChange(`${prompt.slice(0, start)}${variable}${prompt.slice(end)}`);
    // Restore focus and drop the caret after what we inserted, so typing continues there.
    requestAnimationFrame(() => {
      textarea.focus();
      const caret = start + variable.length;
      textarea.setSelectionRange(caret, caret);
    });
  };

  return (
    <Stack gap="density-md">
      <Flex align="center" justify="between" gap="density-md">
        <Text kind="label/bold/lg">{title}</Text>
        <Flex align="center" gap="density-sm">
          <Text kind="body/regular/sm" className="text-text-secondary">
            Enabled
          </Text>
          <Switch
            checked={enabled}
            onCheckedChange={onEnabledChange}
            attributes={{ SwitchInput: { 'aria-label': `${title} enabled` } }}
          />
        </Flex>
      </Flex>

      <Text kind="body/regular/sm" className="text-text-secondary">
        {SCOPE_DESCRIPTIONS[scope]}
      </Text>

      <FormField slotLabel="Prompt">
        <TextArea
          ref={promptRef}
          resizeable="auto"
          className="w-full"
          value={prompt}
          onChange={(event) => onPromptChange(event.currentTarget.value)}
          aria-label={`${title} template`}
        />
      </FormField>

      {variables.length ? (
        <Stack gap="density-xs">
          <Text kind="label/bold/sm">Variables</Text>
          <Flex gap="density-sm" wrap="wrap">
            {variables.map((variable) => (
              <Button
                key={variable}
                kind="secondary"
                color="neutral"
                onClick={() => insertVariable(variable)}
                aria-label={`Insert ${variable} into ${title.toLowerCase()}`}
              >
                <Plus size={14} />
                {variable}
              </Button>
            ))}
          </Flex>
        </Stack>
      ) : null}
    </Stack>
  );
};
