# This file was auto-generated by Fern from our API Definition.

import typing

ListSpansApisIntakeV2WorkspacesWorkspaceSpansGetRequestMode = typing.Union[
    typing.Literal["summary", "detailed"], typing.Any
]
