name: Build OPA policy WASM
description: >
  Installs Flox, activates the OPA environment, and builds the authorization
  policy WASM asset at
  services/core/auth/src/nmp/core/auth/assets/policy.wasm. Assumes the
  repository has already been checked out.

runs:
  using: composite
  steps:
    - name: Install Flox
      uses: flox/install-flox-action@c94e7e1ab56ae14fe98bae4fd84384fd135f0c2a # v2.4.0
      with:
        disable-metrics: "true"
    - name: Build policy WASM
      uses: flox/activate-action@410568008895a0f2e09a34bbd9523f8ef1f2d292 # v1.1.0
      with:
        dir: ./flox-environments/open-policy-agent
        command: ./script/build_policy_wasm.sh
