schema-version = "1.11.0"

[install]

[vars]

[profile]
common = '''
  test -f .git/hooks/pre-commit || pre-commit install

  gum style "NeMo Platform"
'''

[include]
environments = [
    { dir = "flox-environments/common" },
    { dir = "flox-environments/helm" },
    { dir = "flox-environments/actionlint" },
    { dir = "flox-environments/python" },
    { dir = "flox-environments/web" },
    { dir = "flox-environments/osv-scanner" },
    { dir = "flox-environments/open-policy-agent" },
]
