schema-version = "1.13.0"

[profile]
common = '''
  test -f .git/hooks/pre-commit || pre-commit install

  gum style "NeMo Platform"
'''

[include]
environments = [
    { dir = "tools/common" },
    { dir = "tools/helm" },
    { dir = "tools/actionlint" },
    { dir = "tools/python" },
    { dir = "tools/web" },
    { dir = "tools/osv-scanner" },
    { dir = "tools/open-policy-agent" },
]
