schema-version = "1.13.0"

[install]
actionlint = { pkg-path = "actionlint", version = "1.7.12", pkg-group = "actionlint" }
shellcheck = { pkg-path = "shellcheck", version = "0.11.0", pkg-group = "actionlint" }
