# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

models:
  - type: main
    engine: nim
    model: nvdev/nvidia/nemotron-3-nano-30b-a3b
    parameters:
      base_url: https://integrate.api.nvidia.com/v1

  - type: "content_safety"
    engine: nim
    model: "nvdev/nvidia/llama-3.1-nemoguard-8b-content-safety"
    parameters:
      base_url: https://integrate.api.nvidia.com/v1

rails:
  input:
    flows:
      - content safety check input $model=content_safety
  output:
    flows:
      - content safety check output $model=content_safety
