{{- if not .Values.envFromSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nemo-platform.fullname" . }}-api-env
  labels:
    {{- include "nemo-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  # This is the default encryption key for encrypting secrets on the platform.
  NMP_SECRETS_DEFAULT_ENCRYPTION_KEY: "f4NPSp39YN5oWTwZ3iDX/L3PTvEH8qFvUs1noC/jWuo="
{{- end }}
