{{/*
SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-License-Identifier: Apache-2.0
*/}}

{{- if not .Values.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ngc-api
  labels:
    {{- include "nemo-platform.labels" . | nindent 4 }}
type: Opaque
data:
  NGC_API_KEY: {{ .Values.ngcAPIKey | b64enc }}
{{- end }}
