# Target for downloading datasets from NGC
FROM ubuntu:24.04 AS assets-initial

# Install dependencies
RUN apt update && apt install -y wget unzip

ARG TARGETARCH
# Install the NGC cli tool
RUN case "$TARGETARCH" in \
    "amd64") \
        URL=https://api.ngc.nvidia.com/v2/resources/nvidia/ngc-apps/ngc_cli/versions/4.6.6/files/ngccli_linux.zip ;; \
    "arm64") \
        URL=https://api.ngc.nvidia.com/v2/resources/nvidia/ngc-apps/ngc_cli/versions/4.6.6/files/ngccli_arm64.zip ;; \
    *) \
        echo "Unsupported architecture: $TARGETARCH" && exit 1 ;; \
    esac && \
    wget --content-disposition $URL -O ngccli.zip && unzip ngccli.zip && chmod u+x ngc-cli/ngc

# Build arg to specify which version of the datasets resource in NGC to use.
# Set this to "0.0.x-slim" for faster build (1K-row datasets instead of 1M-row)
ARG NEMOTRON_PERSONAS_DATASETS_VERSION

# Create the final location for the data
RUN mkdir -p /data

# Download the personas datasets resource and move to the expected path
RUN --mount=type=secret,id=NGC_CLI_API_KEY \
    NGC_CLI_API_KEY=$(cat /run/secrets/NGC_CLI_API_KEY) ngc-cli/ngc registry resource download-version --org nvidian nvidian/nemo-llm/nemotron-personas-datasets:$NEMOTRON_PERSONAS_DATASETS_VERSION && \
    mv nemotron-personas-datasets_v$NEMOTRON_PERSONAS_DATASETS_VERSION/datasets /data


FROM root-distroless-base-3-11 AS assets

# Copy datasets from the assets image, split for better pull/push performance
COPY --from=assets-initial --chown=nvs:root --chmod=g=u data/datasets/en_IN.parquet /app/data/data-designer/datasets/en_IN.parquet
COPY --from=assets-initial --chown=nvs:root --chmod=g=u data/datasets/en_US.parquet /app/data/data-designer/datasets/en_US.parquet
COPY --from=assets-initial --chown=nvs:root --chmod=g=u data/datasets/hi_IN.parquet /app/data/data-designer/datasets/hi_IN.parquet
COPY --from=assets-initial --chown=nvs:root --chmod=g=u data/datasets/ja_JP.parquet /app/data/data-designer/datasets/ja_JP.parquet
