# syntax=docker/dockerfile:1.17
# default ARG
ARG ASSETS_IMAGE="gitlab-master.nvidia.com:5005/aire/microservices/nmp/data-designer-assets"
ARG ASSETS_IMAGE_TAG="0.0.6"

# Build stage for the data-designer service
#build-data-designer:
    FROM root-python-3-11 AS build

    # Create the non-root user and adjust permissions
    # This approach works for running in OpenShift and with volume mounts because:
    # 1. OpenShift runs containers with arbitrary UIDs but using the root group (GID 0)
    # 2. We're creating a specific user here, but the UID may be different in OpenShift
    # 3. The important part is setting group permissions correctly
    # We mainly create a user and move some directories, the rest of the permission changes happen below
    RUN adduser --disabled-password --gecos "" nvs && \
        # Create logs directory with appropriate permissions
        mkdir -p /app/services/data-designer/logs && \
        chmod -R g=u /app/services/data-designer/logs && \
        # Copy passwd file to allow user to be recognized in distroless image
        cp /etc/passwd /app/passwd

    # Install dependencies
    COPY --from=root-lib-source-artifacts /artifacts/uv.lock /artifacts/pyproject.toml /app/
    RUN --mount=type=cache,target=/root/.cache/uv \
        uv sync --frozen --no-install-project --no-dev --no-install-workspace --no-editable --package=data-designer-service

    # Copy source code
    COPY --from=root-lib-source-artifacts /artifacts/packages /app/packages
    COPY --from=root-lib-source-artifacts /artifacts/sdk /app/sdk
    COPY --from=root-lib-source-artifacts /artifacts/docs /app/docs
    COPY --from=root-lib-source-artifacts /artifacts/openapi /app/openapi
    COPY . /app/services/data-designer

    # Make run.sh executable
    RUN chmod +x /app/services/data-designer/run.sh

    # Generate constraints file
    RUN uv pip compile services/data-designer/pyproject.toml -o constraints.txt && sed -i '/^-e file/d' constraints.txt
    RUN mv /app/constraints.txt /app/services/data-designer/

    # Copy README
    COPY README.md /app

    # Install the package
    RUN --mount=type=cache,target=/root/.cache/uv \
        uv sync --frozen --no-editable --no-dev --package=data-designer-service

    ENV PATH="/app/.venv/bin:$PATH"

# Common configuration for both production and debug targets
#docker-data-designer:
    FROM gitlab-master.nvidia.com:5005/aire/microservices/nmp/data-designer-base:0.0.6-split AS docker

    ENV DEFAULT_CONFIG_ID=default
    ENV DEFAULT_LLM_PROVIDER=nim
    ENV LOG_LEVEL=INFO
    ENV NEMO_TELEMETRY_ENABLED=False
    ENV NIM_ENDPOINT_URL=https://integrate.api.nvidia.com/v1
    ENV DEMO=False

    ENV PATH="/app/.venv/bin:$PATH"

    # Copy files from build stage with correct permissions
    COPY --from=build --chown=nvs:root --chmod=g=u /app /app
    COPY --from=build --chown=nvs:root --chmod=g=u /tmp /tmp
    COPY --from=build --chown=nvs:root --chmod=g=u /app/passwd /etc/passwd

    COPY fixes/cve-2025-8194/tarfile.py.fix  /usr/local/lib/python3.11/tarfile.py

    # Set user to nvs
    # Note: OpenShift will override this with an arbitrary UID,
    # but the permissions set in build and on copy will ensure it works
    USER nvs

    # Set working directory
    WORKDIR /app/services/data-designer

    # Run the api by default, but support switching to run batch job execution
    ENTRYPOINT ["data-designer-service"]
    CMD ["api"]
