# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.model_deployment import ModelDeployment
from ..types.model_deployment_filter import ModelDeploymentFilter
from ..types.model_deployment_status import ModelDeploymentStatus
from ..types.model_deployments_page import ModelDeploymentsPage
from .raw_client import AsyncRawModelDeploymentsClient, RawModelDeploymentsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ModelDeploymentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawModelDeploymentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawModelDeploymentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawModelDeploymentsClient
        """
        return self._raw_client

    def list_deployments(
        self,
        workspace: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort: typing.Optional[str] = None,
        all_versions: typing.Optional[bool] = None,
        filter: typing.Optional[ModelDeploymentFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ModelDeploymentsPage:
        """
        List ModelDeployments for a specific workspace.

        By default, returns only the latest version of each deployment.

        Parameters
        ----------
        workspace : str

        page : typing.Optional[int]
            Page number.

        page_size : typing.Optional[int]
            Page size.

        sort : typing.Optional[str]
            The field to sort by. To sort in decreasing order, use `-` in front of the field name.

        all_versions : typing.Optional[bool]
            If true, return all versions of each deployment. If false (default), return only the latest version.

        filter : typing.Optional[ModelDeploymentFilter]
            Filter deployments by workspace, project, status, config, model_provider_id, name, status_message, created_at, and updated_at.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ModelDeploymentsPage
            Return model deployments for a workspace

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.model_deployments.list_deployments(
            workspace="workspace",
        )
        """
        _response = self._raw_client.list_deployments(
            workspace,
            page=page,
            page_size=page_size,
            sort=sort,
            all_versions=all_versions,
            filter=filter,
            request_options=request_options,
        )
        return _response.data

    def create_deployment(
        self,
        workspace: str,
        *,
        name: str,
        config: str,
        project: typing.Optional[str] = OMIT,
        config_version: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ModelDeployment:
        """
        Create a new ModelDeployment (version 1).

        Parameters
        ----------
        workspace : str

        name : str
            Name of the deployment. Allowed characters: letters (a-z, A-Z), digits (0-9), underscores, hyphens, and dots.

        config : str
            Reference to the ModelDeploymentConfig name

        project : typing.Optional[str]
            The URN of the project associated with this deployment

        config_version : typing.Optional[int]
            Reference to a specific ModelDeploymentConfig version. If not specified, uses latest.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ModelDeployment
            Create a new model deployment

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.model_deployments.create_deployment(
            workspace="workspace",
            name="llama-deploy-v1",
            config="config",
        )
        """
        _response = self._raw_client.create_deployment(
            workspace,
            name=name,
            config=config,
            project=project,
            config_version=config_version,
            request_options=request_options,
        )
        return _response.data

    def get_deployment_version(
        self, workspace: str, deployment: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ModelDeployment:
        """
        Get a specific version of a ModelDeployment.

        Parameters
        ----------
        workspace : str

        deployment : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ModelDeployment
            Return a specific version of a model deployment

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.model_deployments.get_deployment_version(
            workspace="workspace",
            deployment="deployment",
            name="name",
        )
        """
        _response = self._raw_client.get_deployment_version(
            workspace, deployment, name, request_options=request_options
        )
        return _response.data

    def delete_deployment_version(
        self, workspace: str, deployment: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Delete a specific version of a ModelDeployment.

        If the deployment is in any state other than DELETED, this will set its status to DELETING.
        The models controller will then:
        1. Delete the infrastructure (e.g., K8s NimService)
        2. Update the status to DELETED

        If the deployment is already in DELETED status, calling delete again will permanently
        remove it from the database.

        Returns:
        - 202 Accepted: Deployment version marked for deletion (status set to DELETING)
        - 204 No Content: Deployment version permanently removed from database (was already DELETED)
        - 404 Not Found: Deployment version doesn't exist

        Parameters
        ----------
        workspace : str

        deployment : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Deployment version marked for deletion (DELETING status)

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.model_deployments.delete_deployment_version(
            workspace="workspace",
            deployment="deployment",
            name="name",
        )
        """
        _response = self._raw_client.delete_deployment_version(
            workspace, deployment, name, request_options=request_options
        )
        return _response.data

    def get_latest_deployment(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ModelDeployment:
        """
        Get the latest version of a ModelDeployment.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ModelDeployment
            Return the latest version of a model deployment

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.model_deployments.get_latest_deployment(
            workspace="workspace",
            name="name",
        )
        """
        _response = self._raw_client.get_latest_deployment(workspace, name, request_options=request_options)
        return _response.data

    def update_deployment(
        self,
        workspace: str,
        name: str,
        *,
        config: str,
        config_version: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ModelDeployment:
        """
        Update a ModelDeployment (creates a new immutable version).

        Parameters
        ----------
        workspace : str

        name : str

        config : str
            Reference to the ModelDeploymentConfig name

        config_version : typing.Optional[int]
            Reference to a specific ModelDeploymentConfig version. If not specified, uses latest.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ModelDeployment
            Update a model deployment (creates new version)

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.model_deployments.update_deployment(
            workspace="workspace",
            name="name",
            config="config",
        )
        """
        _response = self._raw_client.update_deployment(
            workspace, name, config=config, config_version=config_version, request_options=request_options
        )
        return _response.data

    def delete_all_deployment_versions(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Delete all versions of a ModelDeployment.

        If the deployment is in any state other than DELETED, this will set its status to DELETING.
        The models controller will then:
        1. Delete the infrastructure (e.g., K8s NimService)
        2. Update the status to DELETED

        If the deployment is already in DELETED status, calling delete again will permanently
        remove it from the database.

        Returns:
        - 202 Accepted: Deployment marked for deletion (status set to DELETING)
        - 204 No Content: Deployment permanently removed from database (was already DELETED)
        - 404 Not Found: Deployment doesn't exist

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Deployment marked for deletion (DELETING status)

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.model_deployments.delete_all_deployment_versions(
            workspace="workspace",
            name="name",
        )
        """
        _response = self._raw_client.delete_all_deployment_versions(workspace, name, request_options=request_options)
        return _response.data

    def get_deployment_models(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get Latest ModelDeployment's Model Entities from Entity Store.
        This provides the API contract that NIMs expect from Entity Store today, for pulling LoRAs,
        but enables us to enforce AuthZ boundaries.

        TODO: Implement model entity retrieval based on deployment config.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Return model entities from Entity Store for the latest deployment

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.model_deployments.get_deployment_models(
            workspace="workspace",
            name="name",
        )
        """
        _response = self._raw_client.get_deployment_models(workspace, name, request_options=request_options)
        return _response.data

    def update_deployment_status(
        self,
        workspace: str,
        name: str,
        *,
        status: ModelDeploymentStatus,
        version: typing.Optional[str] = None,
        status_message: typing.Optional[str] = OMIT,
        model_provider_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ModelDeployment:
        """
        Update the status of a ModelDeployment (mutable operation).
        If version is not specified, updates the latest version.

        Parameters
        ----------
        workspace : str

        name : str

        status : ModelDeploymentStatus
            New status for the deployment

        version : typing.Optional[str]

        status_message : typing.Optional[str]
            Detailed status message

        model_provider_id : typing.Optional[str]
            Optional reference to the auto-created ModelProvider workspace/name (format: workspace/name)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ModelDeployment
            Update ModelDeployment status and status_message

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.model_deployments.update_deployment_status(
            workspace="workspace",
            name="name",
            status="UNKNOWN",
        )
        """
        _response = self._raw_client.update_deployment_status(
            workspace,
            name,
            status=status,
            version=version,
            status_message=status_message,
            model_provider_id=model_provider_id,
            request_options=request_options,
        )
        return _response.data

    def list_deployment_versions(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ModelDeployment]:
        """
        List all versions of a ModelDeployment.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ModelDeployment]
            Return all versions of a model deployment

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.model_deployments.list_deployment_versions(
            workspace="workspace",
            name="name",
        )
        """
        _response = self._raw_client.list_deployment_versions(workspace, name, request_options=request_options)
        return _response.data


class AsyncModelDeploymentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawModelDeploymentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawModelDeploymentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawModelDeploymentsClient
        """
        return self._raw_client

    async def list_deployments(
        self,
        workspace: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort: typing.Optional[str] = None,
        all_versions: typing.Optional[bool] = None,
        filter: typing.Optional[ModelDeploymentFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ModelDeploymentsPage:
        """
        List ModelDeployments for a specific workspace.

        By default, returns only the latest version of each deployment.

        Parameters
        ----------
        workspace : str

        page : typing.Optional[int]
            Page number.

        page_size : typing.Optional[int]
            Page size.

        sort : typing.Optional[str]
            The field to sort by. To sort in decreasing order, use `-` in front of the field name.

        all_versions : typing.Optional[bool]
            If true, return all versions of each deployment. If false (default), return only the latest version.

        filter : typing.Optional[ModelDeploymentFilter]
            Filter deployments by workspace, project, status, config, model_provider_id, name, status_message, created_at, and updated_at.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ModelDeploymentsPage
            Return model deployments for a workspace

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.model_deployments.list_deployments(
                workspace="workspace",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_deployments(
            workspace,
            page=page,
            page_size=page_size,
            sort=sort,
            all_versions=all_versions,
            filter=filter,
            request_options=request_options,
        )
        return _response.data

    async def create_deployment(
        self,
        workspace: str,
        *,
        name: str,
        config: str,
        project: typing.Optional[str] = OMIT,
        config_version: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ModelDeployment:
        """
        Create a new ModelDeployment (version 1).

        Parameters
        ----------
        workspace : str

        name : str
            Name of the deployment. Allowed characters: letters (a-z, A-Z), digits (0-9), underscores, hyphens, and dots.

        config : str
            Reference to the ModelDeploymentConfig name

        project : typing.Optional[str]
            The URN of the project associated with this deployment

        config_version : typing.Optional[int]
            Reference to a specific ModelDeploymentConfig version. If not specified, uses latest.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ModelDeployment
            Create a new model deployment

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.model_deployments.create_deployment(
                workspace="workspace",
                name="llama-deploy-v1",
                config="config",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_deployment(
            workspace,
            name=name,
            config=config,
            project=project,
            config_version=config_version,
            request_options=request_options,
        )
        return _response.data

    async def get_deployment_version(
        self, workspace: str, deployment: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ModelDeployment:
        """
        Get a specific version of a ModelDeployment.

        Parameters
        ----------
        workspace : str

        deployment : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ModelDeployment
            Return a specific version of a model deployment

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.model_deployments.get_deployment_version(
                workspace="workspace",
                deployment="deployment",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_deployment_version(
            workspace, deployment, name, request_options=request_options
        )
        return _response.data

    async def delete_deployment_version(
        self, workspace: str, deployment: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Delete a specific version of a ModelDeployment.

        If the deployment is in any state other than DELETED, this will set its status to DELETING.
        The models controller will then:
        1. Delete the infrastructure (e.g., K8s NimService)
        2. Update the status to DELETED

        If the deployment is already in DELETED status, calling delete again will permanently
        remove it from the database.

        Returns:
        - 202 Accepted: Deployment version marked for deletion (status set to DELETING)
        - 204 No Content: Deployment version permanently removed from database (was already DELETED)
        - 404 Not Found: Deployment version doesn't exist

        Parameters
        ----------
        workspace : str

        deployment : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Deployment version marked for deletion (DELETING status)

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.model_deployments.delete_deployment_version(
                workspace="workspace",
                deployment="deployment",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_deployment_version(
            workspace, deployment, name, request_options=request_options
        )
        return _response.data

    async def get_latest_deployment(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ModelDeployment:
        """
        Get the latest version of a ModelDeployment.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ModelDeployment
            Return the latest version of a model deployment

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.model_deployments.get_latest_deployment(
                workspace="workspace",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_latest_deployment(workspace, name, request_options=request_options)
        return _response.data

    async def update_deployment(
        self,
        workspace: str,
        name: str,
        *,
        config: str,
        config_version: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ModelDeployment:
        """
        Update a ModelDeployment (creates a new immutable version).

        Parameters
        ----------
        workspace : str

        name : str

        config : str
            Reference to the ModelDeploymentConfig name

        config_version : typing.Optional[int]
            Reference to a specific ModelDeploymentConfig version. If not specified, uses latest.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ModelDeployment
            Update a model deployment (creates new version)

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.model_deployments.update_deployment(
                workspace="workspace",
                name="name",
                config="config",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_deployment(
            workspace, name, config=config, config_version=config_version, request_options=request_options
        )
        return _response.data

    async def delete_all_deployment_versions(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Optional[typing.Any]:
        """
        Delete all versions of a ModelDeployment.

        If the deployment is in any state other than DELETED, this will set its status to DELETING.
        The models controller will then:
        1. Delete the infrastructure (e.g., K8s NimService)
        2. Update the status to DELETED

        If the deployment is already in DELETED status, calling delete again will permanently
        remove it from the database.

        Returns:
        - 202 Accepted: Deployment marked for deletion (status set to DELETING)
        - 204 No Content: Deployment permanently removed from database (was already DELETED)
        - 404 Not Found: Deployment doesn't exist

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Optional[typing.Any]
            Deployment marked for deletion (DELETING status)

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.model_deployments.delete_all_deployment_versions(
                workspace="workspace",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_all_deployment_versions(
            workspace, name, request_options=request_options
        )
        return _response.data

    async def get_deployment_models(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Dict[str, typing.Any]:
        """
        Get Latest ModelDeployment's Model Entities from Entity Store.
        This provides the API contract that NIMs expect from Entity Store today, for pulling LoRAs,
        but enables us to enforce AuthZ boundaries.

        TODO: Implement model entity retrieval based on deployment config.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.Dict[str, typing.Any]
            Return model entities from Entity Store for the latest deployment

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.model_deployments.get_deployment_models(
                workspace="workspace",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_deployment_models(workspace, name, request_options=request_options)
        return _response.data

    async def update_deployment_status(
        self,
        workspace: str,
        name: str,
        *,
        status: ModelDeploymentStatus,
        version: typing.Optional[str] = None,
        status_message: typing.Optional[str] = OMIT,
        model_provider_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ModelDeployment:
        """
        Update the status of a ModelDeployment (mutable operation).
        If version is not specified, updates the latest version.

        Parameters
        ----------
        workspace : str

        name : str

        status : ModelDeploymentStatus
            New status for the deployment

        version : typing.Optional[str]

        status_message : typing.Optional[str]
            Detailed status message

        model_provider_id : typing.Optional[str]
            Optional reference to the auto-created ModelProvider workspace/name (format: workspace/name)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ModelDeployment
            Update ModelDeployment status and status_message

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.model_deployments.update_deployment_status(
                workspace="workspace",
                name="name",
                status="UNKNOWN",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_deployment_status(
            workspace,
            name,
            status=status,
            version=version,
            status_message=status_message,
            model_provider_id=model_provider_id,
            request_options=request_options,
        )
        return _response.data

    async def list_deployment_versions(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[ModelDeployment]:
        """
        List all versions of a ModelDeployment.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[ModelDeployment]
            Return all versions of a model deployment

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.model_deployments.list_deployment_versions(
                workspace="workspace",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_deployment_versions(workspace, name, request_options=request_options)
        return _response.data
