# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.not_found_error import NotFoundError
from ..errors.unprocessable_entity_error import UnprocessableEntityError
from ..types.model_deployment import ModelDeployment
from ..types.model_deployment_filter import ModelDeploymentFilter
from ..types.model_deployment_status import ModelDeploymentStatus
from ..types.model_deployments_page import ModelDeploymentsPage
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawModelDeploymentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_deployments(
        self,
        workspace: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort: typing.Optional[str] = None,
        all_versions: typing.Optional[bool] = None,
        filter: typing.Optional[ModelDeploymentFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ModelDeploymentsPage]:
        """
        List ModelDeployments for a specific workspace.

        By default, returns only the latest version of each deployment.

        Parameters
        ----------
        workspace : str

        page : typing.Optional[int]
            Page number.

        page_size : typing.Optional[int]
            Page size.

        sort : typing.Optional[str]
            The field to sort by. To sort in decreasing order, use `-` in front of the field name.

        all_versions : typing.Optional[bool]
            If true, return all versions of each deployment. If false (default), return only the latest version.

        filter : typing.Optional[ModelDeploymentFilter]
            Filter deployments by workspace, project, status, config, model_provider_id, name, status_message, created_at, and updated_at.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ModelDeploymentsPage]
            Return model deployments for a workspace
        """
        _response = self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployments",
            method="GET",
            params={
                "page": page,
                "page_size": page_size,
                "sort": sort,
                "all_versions": all_versions,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=ModelDeploymentFilter, direction="write"
                ),
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDeploymentsPage,
                    parse_obj_as(
                        type_=ModelDeploymentsPage,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_deployment(
        self,
        workspace: str,
        *,
        name: str,
        config: str,
        project: typing.Optional[str] = OMIT,
        config_version: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ModelDeployment]:
        """
        Create a new ModelDeployment (version 1).

        Parameters
        ----------
        workspace : str

        name : str
            Name of the deployment. Allowed characters: letters (a-z, A-Z), digits (0-9), underscores, hyphens, and dots.

        config : str
            Reference to the ModelDeploymentConfig name

        project : typing.Optional[str]
            The URN of the project associated with this deployment

        config_version : typing.Optional[int]
            Reference to a specific ModelDeploymentConfig version. If not specified, uses latest.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ModelDeployment]
            Create a new model deployment
        """
        _response = self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployments",
            method="POST",
            json={
                "name": name,
                "project": project,
                "config": config,
                "config_version": config_version,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDeployment,
                    parse_obj_as(
                        type_=ModelDeployment,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_deployment_version(
        self, workspace: str, deployment: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ModelDeployment]:
        """
        Get a specific version of a ModelDeployment.

        Parameters
        ----------
        workspace : str

        deployment : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ModelDeployment]
            Return a specific version of a model deployment
        """
        _response = self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployments/{encode_path_param(deployment)}/versions/{encode_path_param(name)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDeployment,
                    parse_obj_as(
                        type_=ModelDeployment,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_deployment_version(
        self, workspace: str, deployment: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.Optional[typing.Any]]:
        """
        Delete a specific version of a ModelDeployment.

        If the deployment is in any state other than DELETED, this will set its status to DELETING.
        The models controller will then:
        1. Delete the infrastructure (e.g., K8s NimService)
        2. Update the status to DELETED

        If the deployment is already in DELETED status, calling delete again will permanently
        remove it from the database.

        Returns:
        - 202 Accepted: Deployment version marked for deletion (status set to DELETING)
        - 204 No Content: Deployment version permanently removed from database (was already DELETED)
        - 404 Not Found: Deployment version doesn't exist

        Parameters
        ----------
        workspace : str

        deployment : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Optional[typing.Any]]
            Deployment version marked for deletion (DELETING status)
        """
        _response = self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployments/{encode_path_param(deployment)}/versions/{encode_path_param(name)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_latest_deployment(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ModelDeployment]:
        """
        Get the latest version of a ModelDeployment.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ModelDeployment]
            Return the latest version of a model deployment
        """
        _response = self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployments/{encode_path_param(name)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDeployment,
                    parse_obj_as(
                        type_=ModelDeployment,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_deployment(
        self,
        workspace: str,
        name: str,
        *,
        config: str,
        config_version: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ModelDeployment]:
        """
        Update a ModelDeployment (creates a new immutable version).

        Parameters
        ----------
        workspace : str

        name : str

        config : str
            Reference to the ModelDeploymentConfig name

        config_version : typing.Optional[int]
            Reference to a specific ModelDeploymentConfig version. If not specified, uses latest.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ModelDeployment]
            Update a model deployment (creates new version)
        """
        _response = self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployments/{encode_path_param(name)}",
            method="POST",
            json={
                "config": config,
                "config_version": config_version,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDeployment,
                    parse_obj_as(
                        type_=ModelDeployment,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def delete_all_deployment_versions(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.Optional[typing.Any]]:
        """
        Delete all versions of a ModelDeployment.

        If the deployment is in any state other than DELETED, this will set its status to DELETING.
        The models controller will then:
        1. Delete the infrastructure (e.g., K8s NimService)
        2. Update the status to DELETED

        If the deployment is already in DELETED status, calling delete again will permanently
        remove it from the database.

        Returns:
        - 202 Accepted: Deployment marked for deletion (status set to DELETING)
        - 204 No Content: Deployment permanently removed from database (was already DELETED)
        - 404 Not Found: Deployment doesn't exist

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Optional[typing.Any]]
            Deployment marked for deletion (DELETING status)
        """
        _response = self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployments/{encode_path_param(name)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return HttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def get_deployment_models(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.Dict[str, typing.Any]]:
        """
        Get Latest ModelDeployment's Model Entities from Entity Store.
        This provides the API contract that NIMs expect from Entity Store today, for pulling LoRAs,
        but enables us to enforce AuthZ boundaries.

        TODO: Implement model entity retrieval based on deployment config.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.Dict[str, typing.Any]]
            Return model entities from Entity Store for the latest deployment
        """
        _response = self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployments/{encode_path_param(name)}/models",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Dict[str, typing.Any],
                    parse_obj_as(
                        type_=typing.Dict[str, typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def update_deployment_status(
        self,
        workspace: str,
        name: str,
        *,
        status: ModelDeploymentStatus,
        version: typing.Optional[str] = None,
        status_message: typing.Optional[str] = OMIT,
        model_provider_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ModelDeployment]:
        """
        Update the status of a ModelDeployment (mutable operation).
        If version is not specified, updates the latest version.

        Parameters
        ----------
        workspace : str

        name : str

        status : ModelDeploymentStatus
            New status for the deployment

        version : typing.Optional[str]

        status_message : typing.Optional[str]
            Detailed status message

        model_provider_id : typing.Optional[str]
            Optional reference to the auto-created ModelProvider workspace/name (format: workspace/name)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ModelDeployment]
            Update ModelDeployment status and status_message
        """
        _response = self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployments/{encode_path_param(name)}/status",
            method="POST",
            params={
                "version": version,
            },
            json={
                "status": status,
                "status_message": status_message,
                "model_provider_id": model_provider_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDeployment,
                    parse_obj_as(
                        type_=ModelDeployment,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_deployment_versions(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[typing.List[ModelDeployment]]:
        """
        List all versions of a ModelDeployment.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[typing.List[ModelDeployment]]
            Return all versions of a model deployment
        """
        _response = self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployments/{encode_path_param(name)}/versions",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[ModelDeployment],
                    parse_obj_as(
                        type_=typing.List[ModelDeployment],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawModelDeploymentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_deployments(
        self,
        workspace: str,
        *,
        page: typing.Optional[int] = None,
        page_size: typing.Optional[int] = None,
        sort: typing.Optional[str] = None,
        all_versions: typing.Optional[bool] = None,
        filter: typing.Optional[ModelDeploymentFilter] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ModelDeploymentsPage]:
        """
        List ModelDeployments for a specific workspace.

        By default, returns only the latest version of each deployment.

        Parameters
        ----------
        workspace : str

        page : typing.Optional[int]
            Page number.

        page_size : typing.Optional[int]
            Page size.

        sort : typing.Optional[str]
            The field to sort by. To sort in decreasing order, use `-` in front of the field name.

        all_versions : typing.Optional[bool]
            If true, return all versions of each deployment. If false (default), return only the latest version.

        filter : typing.Optional[ModelDeploymentFilter]
            Filter deployments by workspace, project, status, config, model_provider_id, name, status_message, created_at, and updated_at.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ModelDeploymentsPage]
            Return model deployments for a workspace
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployments",
            method="GET",
            params={
                "page": page,
                "page_size": page_size,
                "sort": sort,
                "all_versions": all_versions,
                "filter": convert_and_respect_annotation_metadata(
                    object_=filter, annotation=ModelDeploymentFilter, direction="write"
                ),
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDeploymentsPage,
                    parse_obj_as(
                        type_=ModelDeploymentsPage,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_deployment(
        self,
        workspace: str,
        *,
        name: str,
        config: str,
        project: typing.Optional[str] = OMIT,
        config_version: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ModelDeployment]:
        """
        Create a new ModelDeployment (version 1).

        Parameters
        ----------
        workspace : str

        name : str
            Name of the deployment. Allowed characters: letters (a-z, A-Z), digits (0-9), underscores, hyphens, and dots.

        config : str
            Reference to the ModelDeploymentConfig name

        project : typing.Optional[str]
            The URN of the project associated with this deployment

        config_version : typing.Optional[int]
            Reference to a specific ModelDeploymentConfig version. If not specified, uses latest.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ModelDeployment]
            Create a new model deployment
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployments",
            method="POST",
            json={
                "name": name,
                "project": project,
                "config": config,
                "config_version": config_version,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDeployment,
                    parse_obj_as(
                        type_=ModelDeployment,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_deployment_version(
        self, workspace: str, deployment: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ModelDeployment]:
        """
        Get a specific version of a ModelDeployment.

        Parameters
        ----------
        workspace : str

        deployment : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ModelDeployment]
            Return a specific version of a model deployment
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployments/{encode_path_param(deployment)}/versions/{encode_path_param(name)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDeployment,
                    parse_obj_as(
                        type_=ModelDeployment,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_deployment_version(
        self, workspace: str, deployment: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.Optional[typing.Any]]:
        """
        Delete a specific version of a ModelDeployment.

        If the deployment is in any state other than DELETED, this will set its status to DELETING.
        The models controller will then:
        1. Delete the infrastructure (e.g., K8s NimService)
        2. Update the status to DELETED

        If the deployment is already in DELETED status, calling delete again will permanently
        remove it from the database.

        Returns:
        - 202 Accepted: Deployment version marked for deletion (status set to DELETING)
        - 204 No Content: Deployment version permanently removed from database (was already DELETED)
        - 404 Not Found: Deployment version doesn't exist

        Parameters
        ----------
        workspace : str

        deployment : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Optional[typing.Any]]
            Deployment version marked for deletion (DELETING status)
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployments/{encode_path_param(deployment)}/versions/{encode_path_param(name)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_latest_deployment(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ModelDeployment]:
        """
        Get the latest version of a ModelDeployment.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ModelDeployment]
            Return the latest version of a model deployment
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployments/{encode_path_param(name)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDeployment,
                    parse_obj_as(
                        type_=ModelDeployment,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_deployment(
        self,
        workspace: str,
        name: str,
        *,
        config: str,
        config_version: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ModelDeployment]:
        """
        Update a ModelDeployment (creates a new immutable version).

        Parameters
        ----------
        workspace : str

        name : str

        config : str
            Reference to the ModelDeploymentConfig name

        config_version : typing.Optional[int]
            Reference to a specific ModelDeploymentConfig version. If not specified, uses latest.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ModelDeployment]
            Update a model deployment (creates new version)
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployments/{encode_path_param(name)}",
            method="POST",
            json={
                "config": config,
                "config_version": config_version,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDeployment,
                    parse_obj_as(
                        type_=ModelDeployment,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def delete_all_deployment_versions(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.Optional[typing.Any]]:
        """
        Delete all versions of a ModelDeployment.

        If the deployment is in any state other than DELETED, this will set its status to DELETING.
        The models controller will then:
        1. Delete the infrastructure (e.g., K8s NimService)
        2. Update the status to DELETED

        If the deployment is already in DELETED status, calling delete again will permanently
        remove it from the database.

        Returns:
        - 202 Accepted: Deployment marked for deletion (status set to DELETING)
        - 204 No Content: Deployment permanently removed from database (was already DELETED)
        - 404 Not Found: Deployment doesn't exist

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Optional[typing.Any]]
            Deployment marked for deletion (DELETING status)
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployments/{encode_path_param(name)}",
            method="DELETE",
            request_options=request_options,
        )
        try:
            if _response is None or not _response.text.strip():
                return AsyncHttpResponse(response=_response, data=None)
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Optional[typing.Any],
                    parse_obj_as(
                        type_=typing.Optional[typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def get_deployment_models(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.Dict[str, typing.Any]]:
        """
        Get Latest ModelDeployment's Model Entities from Entity Store.
        This provides the API contract that NIMs expect from Entity Store today, for pulling LoRAs,
        but enables us to enforce AuthZ boundaries.

        TODO: Implement model entity retrieval based on deployment config.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.Dict[str, typing.Any]]
            Return model entities from Entity Store for the latest deployment
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployments/{encode_path_param(name)}/models",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.Dict[str, typing.Any],
                    parse_obj_as(
                        type_=typing.Dict[str, typing.Any],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def update_deployment_status(
        self,
        workspace: str,
        name: str,
        *,
        status: ModelDeploymentStatus,
        version: typing.Optional[str] = None,
        status_message: typing.Optional[str] = OMIT,
        model_provider_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ModelDeployment]:
        """
        Update the status of a ModelDeployment (mutable operation).
        If version is not specified, updates the latest version.

        Parameters
        ----------
        workspace : str

        name : str

        status : ModelDeploymentStatus
            New status for the deployment

        version : typing.Optional[str]

        status_message : typing.Optional[str]
            Detailed status message

        model_provider_id : typing.Optional[str]
            Optional reference to the auto-created ModelProvider workspace/name (format: workspace/name)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ModelDeployment]
            Update ModelDeployment status and status_message
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployments/{encode_path_param(name)}/status",
            method="POST",
            params={
                "version": version,
            },
            json={
                "status": status,
                "status_message": status_message,
                "model_provider_id": model_provider_id,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelDeployment,
                    parse_obj_as(
                        type_=ModelDeployment,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_deployment_versions(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[typing.List[ModelDeployment]]:
        """
        List all versions of a ModelDeployment.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[typing.List[ModelDeployment]]
            Return all versions of a model deployment
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"apis/models/v2/workspaces/{encode_path_param(workspace)}/deployments/{encode_path_param(name)}/versions",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    typing.List[ModelDeployment],
                    parse_obj_as(
                        type_=typing.List[ModelDeployment],  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 422:
                raise UnprocessableEntityError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
