schema-version = "1.14.0"

[install]
nodejs = { pkg-path = "nodejs_22", version = "22.23.2", pkg-group = "node" }
pnpm = { pkg-path = "pnpm_10", version = "10.34.5", pkg-group = "node" }

[vars]
PNPM_HOME="${FLOX_ENV_CACHE}/pnpm"

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-linux"]
