# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.otel_export_logs_service_response import OtelExportLogsServiceResponse
from ..types.platform_job_log_page import PlatformJobLogPage
from .raw_client import AsyncRawOtlpClient, RawOtlpClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class OtlpClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawOtlpClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawOtlpClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawOtlpClient
        """
        return self._raw_client

    def upload_otlp_logs(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OtelExportLogsServiceResponse:
        """
        Upload OTLP logs to a specified fileset in JSON or Protobuf format.

        Supports both application/json and application/x-protobuf content types.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OtelExportLogsServiceResponse
            Successful Response

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.otlp.upload_otlp_logs(
            workspace="workspace",
            name="name",
        )
        """
        _response = self._raw_client.upload_otlp_logs(workspace, name, request_options=request_options)
        return _response.data

    def query_otlp_logs(
        self,
        workspace: str,
        name: str,
        *,
        filters: typing.Optional[typing.Dict[str, str]] = OMIT,
        limit: typing.Optional[int] = OMIT,
        page_cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PlatformJobLogPage:
        """
        Query logs from parquet files in a fileset.

        This is an internal endpoint that runs DuckDB queries with direct storage
        access.

        Parameters
        ----------
        workspace : str

        name : str

        filters : typing.Optional[typing.Dict[str, str]]
            Key-value filters to apply to the query

        limit : typing.Optional[int]
            Maximum number of results to return

        page_cursor : typing.Optional[str]
            Cursor for pagination

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PlatformJobLogPage
            Successful Response

        Examples
        --------
        from nvidia import NvidiaApi

        client = NvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )
        client.otlp.query_otlp_logs(
            workspace="workspace",
            name="name",
        )
        """
        _response = self._raw_client.query_otlp_logs(
            workspace, name, filters=filters, limit=limit, page_cursor=page_cursor, request_options=request_options
        )
        return _response.data


class AsyncOtlpClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawOtlpClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawOtlpClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawOtlpClient
        """
        return self._raw_client

    async def upload_otlp_logs(
        self, workspace: str, name: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> OtelExportLogsServiceResponse:
        """
        Upload OTLP logs to a specified fileset in JSON or Protobuf format.

        Supports both application/json and application/x-protobuf content types.

        Parameters
        ----------
        workspace : str

        name : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        OtelExportLogsServiceResponse
            Successful Response

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.otlp.upload_otlp_logs(
                workspace="workspace",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.upload_otlp_logs(workspace, name, request_options=request_options)
        return _response.data

    async def query_otlp_logs(
        self,
        workspace: str,
        name: str,
        *,
        filters: typing.Optional[typing.Dict[str, str]] = OMIT,
        limit: typing.Optional[int] = OMIT,
        page_cursor: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PlatformJobLogPage:
        """
        Query logs from parquet files in a fileset.

        This is an internal endpoint that runs DuckDB queries with direct storage
        access.

        Parameters
        ----------
        workspace : str

        name : str

        filters : typing.Optional[typing.Dict[str, str]]
            Key-value filters to apply to the query

        limit : typing.Optional[int]
            Maximum number of results to return

        page_cursor : typing.Optional[str]
            Cursor for pagination

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PlatformJobLogPage
            Successful Response

        Examples
        --------
        import asyncio

        from nvidia import AsyncNvidiaApi

        client = AsyncNvidiaApi(
            base_url="https://yourhost.com/path/to/api",
        )


        async def main() -> None:
            await client.otlp.query_otlp_logs(
                workspace="workspace",
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.query_otlp_logs(
            workspace, name, filters=filters, limit=limit, page_cursor=page_cursor, request_options=request_options
        )
        return _response.data
