{{- if .Values.sharedPostgresql.enabled }}
{{- $nemoPassword := include "nemo-platform-authentik.sharedPostgresql.password" (dict "root" . "secretName" .Values.sharedPostgresql.serviceName "secretKey" "nemo-password" "value" .Values.sharedPostgresql.nemo.password) -}}
apiVersion: v1
kind: Secret
metadata:
  name: shared-postgresql-nemo
  namespace: {{ include "nemo-platform-authentik.namespace" . }}
type: Opaque
stringData:
  password: {{ $nemoPassword | quote }}
{{- end }}
