{{- if and .Values.sharedPostgresql.enabled .Values.sharedPostgresql.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nemo-platform-authentik.sharedPostgresql.serviceAccountName" . }}
  namespace: {{ include "nemo-platform-authentik.namespace" . }}
  labels:
    {{- include "nemo-platform-authentik.labels" . | nindent 4 }}
    app.kubernetes.io/component: shared-postgresql
  {{- with .Values.sharedPostgresql.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.sharedPostgresql.serviceAccount.automount }}
{{- end }}
