apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nemo-authentik-workload-token-reviewer
rules:
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nemo-authentik-workload-token-reviewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nemo-authentik-workload-token-reviewer
subjects:
  - kind: ServiceAccount
    name: {{ .Values.integration.nemoPlatform.apiServiceAccountName }}
    namespace: {{ include "nemo-platform-authentik.namespace" . }}
