{{- if .Values.workloadTokenSigningKey.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nemo-platform-authentik.workloadTokenSigningKey.secretName" . }}
  namespace: {{ include "nemo-platform-authentik.namespace" . }}
  labels:
    app.kubernetes.io/component: workload-token-signing-key
type: Opaque
stringData:
  {{ include "nemo-platform-authentik.workloadTokenSigningKey.key" . }}: |-
{{ include "nemo-platform-authentik.workloadTokenSigningKey.privateKeyPem" . | nindent 4 }}
{{- end }}
