# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "release/*"]
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  secrets-scan:
    name: Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - name: Skip merge queue scan
        if: ${{ github.event_name == 'merge_group' }}
        run: echo "Skipping secrets scan for merge queue"

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        if: ${{ github.event_name != 'merge_group' }}
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: TruffleHog OSS
        if: ${{ github.event_name != 'merge_group' }}
        id: trufflehog
        uses: trufflesecurity/trufflehog@cc1fe982afc515d2991365ce8d4d0dd07170fcad # v3.97.2
        continue-on-error: true
        with:
          path: ./
          version: 3.95.3
          extra_args: --exclude-paths=.github/trufflehog-exclude.txt

      - name: Scan Results Status
        if: ${{ github.event_name != 'merge_group' && steps.trufflehog.outcome == 'failure' }}
        run: exit 1
  codeql:
    name: CodeQL Analyze Codebase
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python', 'javascript-typescript' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Initialize CodeQL
        uses: github/codeql-action/init@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        with:
            languages: ${{matrix.language}}
            config-file: ./.github/codeql/codeql-config.yml
            dependency-caching: false

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4.37.9
        with:
            category: "/language:${{matrix.language}}"
